// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.25 && !go1.26
// +build go1.25,!go1.26

package tls

import (
	q "crypto/tls"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackageLazy("crypto/tls", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "tls",
			Path: "crypto/tls",
			Deps: map[string]string{
				"bytes":                           "bytes",
				"container/list":                  "list",
				"context":                         "context",
				"crypto":                          "crypto",
				"crypto/aes":                      "aes",
				"crypto/cipher":                   "cipher",
				"crypto/des":                      "des",
				"crypto/ecdh":                     "ecdh",
				"crypto/ecdsa":                    "ecdsa",
				"crypto/ed25519":                  "ed25519",
				"crypto/elliptic":                 "elliptic",
				"crypto/hkdf":                     "hkdf",
				"crypto/hmac":                     "hmac",
				"crypto/internal/boring":          "boring",
				"crypto/internal/fips140/aes":     "aes",
				"crypto/internal/fips140/aes/gcm": "gcm",
				"crypto/internal/fips140/mlkem":   "mlkem",
				"crypto/internal/fips140/tls12":   "tls12",
				"crypto/internal/fips140/tls13":   "tls13",
				"crypto/internal/hpke":            "hpke",
				"crypto/md5":                      "md5",
				"crypto/rand":                     "rand",
				"crypto/rc4":                      "rc4",
				"crypto/rsa":                      "rsa",
				"crypto/sha1":                     "sha1",
				"crypto/sha256":                   "sha256",
				"crypto/sha512":                   "sha512",
				"crypto/subtle":                   "subtle",
				"crypto/tls/internal/fips140tls":  "fips140tls",
				"crypto/x509":                     "x509",
				"encoding/pem":                    "pem",
				"errors":                          "errors",
				"fmt":                             "fmt",
				"hash":                            "hash",
				"internal/byteorder":              "byteorder",
				"internal/cpu":                    "cpu",
				"internal/godebug":                "godebug",
				"io":                              "io",
				"net":                             "net",
				"os":                              "os",
				"runtime":                         "runtime",
				"slices":                          "slices",
				"sort":                            "sort",
				"strconv":                         "strconv",
				"strings":                         "strings",
				"sync":                            "sync",
				"sync/atomic":                     "atomic",
				"time":                            "time",
				"unsafe":                          "unsafe",
				"vendor/golang.org/x/crypto/chacha20poly1305": "chacha20poly1305",
				"vendor/golang.org/x/crypto/cryptobyte":       "cryptobyte",
				"weak":                                        "weak",
			},
			Interfaces: map[string]reflect.Type{
				"ClientSessionCache": reflect.TypeOf((*q.ClientSessionCache)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"AlertError":                   reflect.TypeOf((*q.AlertError)(nil)).Elem(),
				"Certificate":                  reflect.TypeOf((*q.Certificate)(nil)).Elem(),
				"CertificateRequestInfo":       reflect.TypeOf((*q.CertificateRequestInfo)(nil)).Elem(),
				"CertificateVerificationError": reflect.TypeOf((*q.CertificateVerificationError)(nil)).Elem(),
				"CipherSuite":                  reflect.TypeOf((*q.CipherSuite)(nil)).Elem(),
				"ClientAuthType":               reflect.TypeOf((*q.ClientAuthType)(nil)).Elem(),
				"ClientHelloInfo":              reflect.TypeOf((*q.ClientHelloInfo)(nil)).Elem(),
				"ClientSessionState":           reflect.TypeOf((*q.ClientSessionState)(nil)).Elem(),
				"Config":                       reflect.TypeOf((*q.Config)(nil)).Elem(),
				"Conn":                         reflect.TypeOf((*q.Conn)(nil)).Elem(),
				"ConnectionState":              reflect.TypeOf((*q.ConnectionState)(nil)).Elem(),
				"CurveID":                      reflect.TypeOf((*q.CurveID)(nil)).Elem(),
				"Dialer":                       reflect.TypeOf((*q.Dialer)(nil)).Elem(),
				"ECHRejectionError":            reflect.TypeOf((*q.ECHRejectionError)(nil)).Elem(),
				"EncryptedClientHelloKey":      reflect.TypeOf((*q.EncryptedClientHelloKey)(nil)).Elem(),
				"QUICConfig":                   reflect.TypeOf((*q.QUICConfig)(nil)).Elem(),
				"QUICConn":                     reflect.TypeOf((*q.QUICConn)(nil)).Elem(),
				"QUICEncryptionLevel":          reflect.TypeOf((*q.QUICEncryptionLevel)(nil)).Elem(),
				"QUICEvent":                    reflect.TypeOf((*q.QUICEvent)(nil)).Elem(),
				"QUICEventKind":                reflect.TypeOf((*q.QUICEventKind)(nil)).Elem(),
				"QUICSessionTicketOptions":     reflect.TypeOf((*q.QUICSessionTicketOptions)(nil)).Elem(),
				"RecordHeaderError":            reflect.TypeOf((*q.RecordHeaderError)(nil)).Elem(),
				"RenegotiationSupport":         reflect.TypeOf((*q.RenegotiationSupport)(nil)).Elem(),
				"SessionState":                 reflect.TypeOf((*q.SessionState)(nil)).Elem(),
				"SignatureScheme":              reflect.TypeOf((*q.SignatureScheme)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars:       map[string]reflect.Value{},
			Funcs: map[string]reflect.Value{
				"CipherSuiteName":          reflect.ValueOf(q.CipherSuiteName),
				"CipherSuites":             reflect.ValueOf(q.CipherSuites),
				"Client":                   reflect.ValueOf(q.Client),
				"Dial":                     reflect.ValueOf(q.Dial),
				"DialWithDialer":           reflect.ValueOf(q.DialWithDialer),
				"InsecureCipherSuites":     reflect.ValueOf(q.InsecureCipherSuites),
				"Listen":                   reflect.ValueOf(q.Listen),
				"LoadX509KeyPair":          reflect.ValueOf(q.LoadX509KeyPair),
				"NewLRUClientSessionCache": reflect.ValueOf(q.NewLRUClientSessionCache),
				"NewListener":              reflect.ValueOf(q.NewListener),
				"NewResumptionState":       reflect.ValueOf(q.NewResumptionState),
				"ParseSessionState":        reflect.ValueOf(q.ParseSessionState),
				"QUICClient":               reflect.ValueOf(q.QUICClient),
				"QUICServer":               reflect.ValueOf(q.QUICServer),
				"Server":                   reflect.ValueOf(q.Server),
				"VersionName":              reflect.ValueOf(q.VersionName),
				"X509KeyPair":              reflect.ValueOf(q.X509KeyPair),
			},
			TypedConsts: map[string]ixgo.TypedConst{
				"CurveP256":                                     {Typ: reflect.TypeOf(q.CurveP256), Value: constant.MakeInt64(int64(q.CurveP256))},
				"CurveP384":                                     {Typ: reflect.TypeOf(q.CurveP384), Value: constant.MakeInt64(int64(q.CurveP384))},
				"CurveP521":                                     {Typ: reflect.TypeOf(q.CurveP521), Value: constant.MakeInt64(int64(q.CurveP521))},
				"ECDSAWithP256AndSHA256":                        {Typ: reflect.TypeOf(q.ECDSAWithP256AndSHA256), Value: constant.MakeInt64(int64(q.ECDSAWithP256AndSHA256))},
				"ECDSAWithP384AndSHA384":                        {Typ: reflect.TypeOf(q.ECDSAWithP384AndSHA384), Value: constant.MakeInt64(int64(q.ECDSAWithP384AndSHA384))},
				"ECDSAWithP521AndSHA512":                        {Typ: reflect.TypeOf(q.ECDSAWithP521AndSHA512), Value: constant.MakeInt64(int64(q.ECDSAWithP521AndSHA512))},
				"ECDSAWithSHA1":                                 {Typ: reflect.TypeOf(q.ECDSAWithSHA1), Value: constant.MakeInt64(int64(q.ECDSAWithSHA1))},
				"Ed25519":                                       {Typ: reflect.TypeOf(q.Ed25519), Value: constant.MakeInt64(int64(q.Ed25519))},
				"NoClientCert":                                  {Typ: reflect.TypeOf(q.NoClientCert), Value: constant.MakeInt64(int64(q.NoClientCert))},
				"PKCS1WithSHA1":                                 {Typ: reflect.TypeOf(q.PKCS1WithSHA1), Value: constant.MakeInt64(int64(q.PKCS1WithSHA1))},
				"PKCS1WithSHA256":                               {Typ: reflect.TypeOf(q.PKCS1WithSHA256), Value: constant.MakeInt64(int64(q.PKCS1WithSHA256))},
				"PKCS1WithSHA384":                               {Typ: reflect.TypeOf(q.PKCS1WithSHA384), Value: constant.MakeInt64(int64(q.PKCS1WithSHA384))},
				"PKCS1WithSHA512":                               {Typ: reflect.TypeOf(q.PKCS1WithSHA512), Value: constant.MakeInt64(int64(q.PKCS1WithSHA512))},
				"PSSWithSHA256":                                 {Typ: reflect.TypeOf(q.PSSWithSHA256), Value: constant.MakeInt64(int64(q.PSSWithSHA256))},
				"PSSWithSHA384":                                 {Typ: reflect.TypeOf(q.PSSWithSHA384), Value: constant.MakeInt64(int64(q.PSSWithSHA384))},
				"PSSWithSHA512":                                 {Typ: reflect.TypeOf(q.PSSWithSHA512), Value: constant.MakeInt64(int64(q.PSSWithSHA512))},
				"QUICEncryptionLevelApplication":                {Typ: reflect.TypeOf(q.QUICEncryptionLevelApplication), Value: constant.MakeInt64(int64(q.QUICEncryptionLevelApplication))},
				"QUICEncryptionLevelEarly":                      {Typ: reflect.TypeOf(q.QUICEncryptionLevelEarly), Value: constant.MakeInt64(int64(q.QUICEncryptionLevelEarly))},
				"QUICEncryptionLevelHandshake":                  {Typ: reflect.TypeOf(q.QUICEncryptionLevelHandshake), Value: constant.MakeInt64(int64(q.QUICEncryptionLevelHandshake))},
				"QUICEncryptionLevelInitial":                    {Typ: reflect.TypeOf(q.QUICEncryptionLevelInitial), Value: constant.MakeInt64(int64(q.QUICEncryptionLevelInitial))},
				"QUICHandshakeDone":                             {Typ: reflect.TypeOf(q.QUICHandshakeDone), Value: constant.MakeInt64(int64(q.QUICHandshakeDone))},
				"QUICNoEvent":                                   {Typ: reflect.TypeOf(q.QUICNoEvent), Value: constant.MakeInt64(int64(q.QUICNoEvent))},
				"QUICRejectedEarlyData":                         {Typ: reflect.TypeOf(q.QUICRejectedEarlyData), Value: constant.MakeInt64(int64(q.QUICRejectedEarlyData))},
				"QUICResumeSession":                             {Typ: reflect.TypeOf(q.QUICResumeSession), Value: constant.MakeInt64(int64(q.QUICResumeSession))},
				"QUICSetReadSecret":                             {Typ: reflect.TypeOf(q.QUICSetReadSecret), Value: constant.MakeInt64(int64(q.QUICSetReadSecret))},
				"QUICSetWriteSecret":                            {Typ: reflect.TypeOf(q.QUICSetWriteSecret), Value: constant.MakeInt64(int64(q.QUICSetWriteSecret))},
				"QUICStoreSession":                              {Typ: reflect.TypeOf(q.QUICStoreSession), Value: constant.MakeInt64(int64(q.QUICStoreSession))},
				"QUICTransportParameters":                       {Typ: reflect.TypeOf(q.QUICTransportParameters), Value: constant.MakeInt64(int64(q.QUICTransportParameters))},
				"QUICTransportParametersRequired":               {Typ: reflect.TypeOf(q.QUICTransportParametersRequired), Value: constant.MakeInt64(int64(q.QUICTransportParametersRequired))},
				"QUICWriteData":                                 {Typ: reflect.TypeOf(q.QUICWriteData), Value: constant.MakeInt64(int64(q.QUICWriteData))},
				"RenegotiateFreelyAsClient":                     {Typ: reflect.TypeOf(q.RenegotiateFreelyAsClient), Value: constant.MakeInt64(int64(q.RenegotiateFreelyAsClient))},
				"RenegotiateNever":                              {Typ: reflect.TypeOf(q.RenegotiateNever), Value: constant.MakeInt64(int64(q.RenegotiateNever))},
				"RenegotiateOnceAsClient":                       {Typ: reflect.TypeOf(q.RenegotiateOnceAsClient), Value: constant.MakeInt64(int64(q.RenegotiateOnceAsClient))},
				"RequestClientCert":                             {Typ: reflect.TypeOf(q.RequestClientCert), Value: constant.MakeInt64(int64(q.RequestClientCert))},
				"RequireAndVerifyClientCert":                    {Typ: reflect.TypeOf(q.RequireAndVerifyClientCert), Value: constant.MakeInt64(int64(q.RequireAndVerifyClientCert))},
				"RequireAnyClientCert":                          {Typ: reflect.TypeOf(q.RequireAnyClientCert), Value: constant.MakeInt64(int64(q.RequireAnyClientCert))},
				"TLS_AES_128_GCM_SHA256":                        {Typ: reflect.TypeOf(q.TLS_AES_128_GCM_SHA256), Value: constant.MakeInt64(int64(q.TLS_AES_128_GCM_SHA256))},
				"TLS_AES_256_GCM_SHA384":                        {Typ: reflect.TypeOf(q.TLS_AES_256_GCM_SHA384), Value: constant.MakeInt64(int64(q.TLS_AES_256_GCM_SHA384))},
				"TLS_CHACHA20_POLY1305_SHA256":                  {Typ: reflect.TypeOf(q.TLS_CHACHA20_POLY1305_SHA256), Value: constant.MakeInt64(int64(q.TLS_CHACHA20_POLY1305_SHA256))},
				"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA":          {Typ: reflect.TypeOf(q.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA), Value: constant.MakeInt64(int64(q.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA))},
				"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256":       {Typ: reflect.TypeOf(q.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256), Value: constant.MakeInt64(int64(q.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256))},
				"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256":       {Typ: reflect.TypeOf(q.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256), Value: constant.MakeInt64(int64(q.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256))},
				"TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA":          {Typ: reflect.TypeOf(q.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA), Value: constant.MakeInt64(int64(q.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA))},
				"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384":       {Typ: reflect.TypeOf(q.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384), Value: constant.MakeInt64(int64(q.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384))},
				"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305":        {Typ: reflect.TypeOf(q.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305), Value: constant.MakeInt64(int64(q.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305))},
				"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256": {Typ: reflect.TypeOf(q.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256), Value: constant.MakeInt64(int64(q.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256))},
				"TLS_ECDHE_ECDSA_WITH_RC4_128_SHA":              {Typ: reflect.TypeOf(q.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA), Value: constant.MakeInt64(int64(q.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA))},
				"TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA":           {Typ: reflect.TypeOf(q.TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA), Value: constant.MakeInt64(int64(q.TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA))},
				"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA":            {Typ: reflect.TypeOf(q.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA), Value: constant.MakeInt64(int64(q.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA))},
				"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256":         {Typ: reflect.TypeOf(q.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256), Value: constant.MakeInt64(int64(q.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256))},
				"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256":         {Typ: reflect.TypeOf(q.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256), Value: constant.MakeInt64(int64(q.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256))},
				"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA":            {Typ: reflect.TypeOf(q.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA), Value: constant.MakeInt64(int64(q.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA))},
				"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384":         {Typ: reflect.TypeOf(q.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384), Value: constant.MakeInt64(int64(q.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384))},
				"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305":          {Typ: reflect.TypeOf(q.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305), Value: constant.MakeInt64(int64(q.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305))},
				"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256":   {Typ: reflect.TypeOf(q.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256), Value: constant.MakeInt64(int64(q.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256))},
				"TLS_ECDHE_RSA_WITH_RC4_128_SHA":                {Typ: reflect.TypeOf(q.TLS_ECDHE_RSA_WITH_RC4_128_SHA), Value: constant.MakeInt64(int64(q.TLS_ECDHE_RSA_WITH_RC4_128_SHA))},
				"TLS_FALLBACK_SCSV":                             {Typ: reflect.TypeOf(q.TLS_FALLBACK_SCSV), Value: constant.MakeInt64(int64(q.TLS_FALLBACK_SCSV))},
				"TLS_RSA_WITH_3DES_EDE_CBC_SHA":                 {Typ: reflect.TypeOf(q.TLS_RSA_WITH_3DES_EDE_CBC_SHA), Value: constant.MakeInt64(int64(q.TLS_RSA_WITH_3DES_EDE_CBC_SHA))},
				"TLS_RSA_WITH_AES_128_CBC_SHA":                  {Typ: reflect.TypeOf(q.TLS_RSA_WITH_AES_128_CBC_SHA), Value: constant.MakeInt64(int64(q.TLS_RSA_WITH_AES_128_CBC_SHA))},
				"TLS_RSA_WITH_AES_128_CBC_SHA256":               {Typ: reflect.TypeOf(q.TLS_RSA_WITH_AES_128_CBC_SHA256), Value: constant.MakeInt64(int64(q.TLS_RSA_WITH_AES_128_CBC_SHA256))},
				"TLS_RSA_WITH_AES_128_GCM_SHA256":               {Typ: reflect.TypeOf(q.TLS_RSA_WITH_AES_128_GCM_SHA256), Value: constant.MakeInt64(int64(q.TLS_RSA_WITH_AES_128_GCM_SHA256))},
				"TLS_RSA_WITH_AES_256_CBC_SHA":                  {Typ: reflect.TypeOf(q.TLS_RSA_WITH_AES_256_CBC_SHA), Value: constant.MakeInt64(int64(q.TLS_RSA_WITH_AES_256_CBC_SHA))},
				"TLS_RSA_WITH_AES_256_GCM_SHA384":               {Typ: reflect.TypeOf(q.TLS_RSA_WITH_AES_256_GCM_SHA384), Value: constant.MakeInt64(int64(q.TLS_RSA_WITH_AES_256_GCM_SHA384))},
				"TLS_RSA_WITH_RC4_128_SHA":                      {Typ: reflect.TypeOf(q.TLS_RSA_WITH_RC4_128_SHA), Value: constant.MakeInt64(int64(q.TLS_RSA_WITH_RC4_128_SHA))},
				"VerifyClientCertIfGiven":                       {Typ: reflect.TypeOf(q.VerifyClientCertIfGiven), Value: constant.MakeInt64(int64(q.VerifyClientCertIfGiven))},
				"X25519":                                        {Typ: reflect.TypeOf(q.X25519), Value: constant.MakeInt64(int64(q.X25519))},
				"X25519MLKEM768":                                {Typ: reflect.TypeOf(q.X25519MLKEM768), Value: constant.MakeInt64(int64(q.X25519MLKEM768))},
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"VersionSSL30": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.VersionSSL30))},
				"VersionTLS10": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.VersionTLS10))},
				"VersionTLS11": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.VersionTLS11))},
				"VersionTLS12": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.VersionTLS12))},
				"VersionTLS13": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.VersionTLS13))},
			},
		}
	})
}
