// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.26
// +build go1.26

package tls

import (
	q "crypto/tls"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("crypto/tls", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "tls",
			Path: "crypto/tls",
			Deps: map[string]string{
				"bytes":                           "bytes",
				"container/list":                  "list",
				"context":                         "context",
				"crypto":                          "crypto",
				"crypto/aes":                      "aes",
				"crypto/cipher":                   "cipher",
				"crypto/des":                      "des",
				"crypto/ecdh":                     "ecdh",
				"crypto/ecdsa":                    "ecdsa",
				"crypto/ed25519":                  "ed25519",
				"crypto/elliptic":                 "elliptic",
				"crypto/hkdf":                     "hkdf",
				"crypto/hmac":                     "hmac",
				"crypto/hpke":                     "hpke",
				"crypto/internal/boring":          "boring",
				"crypto/internal/fips140/aes":     "aes",
				"crypto/internal/fips140/aes/gcm": "gcm",
				"crypto/internal/fips140/tls12":   "tls12",
				"crypto/internal/fips140/tls13":   "tls13",
				"crypto/md5":                      "md5",
				"crypto/mlkem":                    "mlkem",
				"crypto/rand":                     "rand",
				"crypto/rc4":                      "rc4",
				"crypto/rsa":                      "rsa",
				"crypto/sha1":                     "sha1",
				"crypto/sha256":                   "sha256",
				"crypto/sha512":                   "sha512",
				"crypto/subtle":                   "subtle",
				"crypto/tls/internal/fips140tls":  "fips140tls",
				"crypto/x509":                     "x509",
				"encoding/pem":                    "pem",
				"errors":                          "errors",
				"fmt":                             "fmt",
				"hash":                            "hash",
				"internal/byteorder":              "byteorder",
				"internal/cpu":                    "cpu",
				"internal/godebug":                "godebug",
				"io":                              "io",
				"net":                             "net",
				"os":                              "os",
				"runtime":                         "runtime",
				"slices":                          "slices",
				"sort":                            "sort",
				"strconv":                         "strconv",
				"strings":                         "strings",
				"sync":                            "sync",
				"sync/atomic":                     "atomic",
				"time":                            "time",
				"unsafe":                          "unsafe",
				"vendor/golang.org/x/crypto/chacha20poly1305": "chacha20poly1305",
				"vendor/golang.org/x/crypto/cryptobyte":       "cryptobyte",
				"weak":                                        "weak",
			},
			Interfaces: map[string]reflect.Type{
				"ClientSessionCache": reflect.TypeOf((*q.ClientSessionCache)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"AlertError":                   reflect.TypeOf((*q.AlertError)(nil)).Elem(),
				"Certificate":                  reflect.TypeOf((*q.Certificate)(nil)).Elem(),
				"CertificateRequestInfo":       reflect.TypeOf((*q.CertificateRequestInfo)(nil)).Elem(),
				"CertificateVerificationError": reflect.TypeOf((*q.CertificateVerificationError)(nil)).Elem(),
				"CipherSuite":                  reflect.TypeOf((*q.CipherSuite)(nil)).Elem(),
				"ClientAuthType":               reflect.TypeOf((*q.ClientAuthType)(nil)).Elem(),
				"ClientHelloInfo":              reflect.TypeOf((*q.ClientHelloInfo)(nil)).Elem(),
				"ClientSessionState":           reflect.TypeOf((*q.ClientSessionState)(nil)).Elem(),
				"Config":                       reflect.TypeOf((*q.Config)(nil)).Elem(),
				"Conn":                         reflect.TypeOf((*q.Conn)(nil)).Elem(),
				"ConnectionState":              reflect.TypeOf((*q.ConnectionState)(nil)).Elem(),
				"CurveID":                      reflect.TypeOf((*q.CurveID)(nil)).Elem(),
				"Dialer":                       reflect.TypeOf((*q.Dialer)(nil)).Elem(),
				"ECHRejectionError":            reflect.TypeOf((*q.ECHRejectionError)(nil)).Elem(),
				"EncryptedClientHelloKey":      reflect.TypeOf((*q.EncryptedClientHelloKey)(nil)).Elem(),
				"QUICConfig":                   reflect.TypeOf((*q.QUICConfig)(nil)).Elem(),
				"QUICConn":                     reflect.TypeOf((*q.QUICConn)(nil)).Elem(),
				"QUICEncryptionLevel":          reflect.TypeOf((*q.QUICEncryptionLevel)(nil)).Elem(),
				"QUICEvent":                    reflect.TypeOf((*q.QUICEvent)(nil)).Elem(),
				"QUICEventKind":                reflect.TypeOf((*q.QUICEventKind)(nil)).Elem(),
				"QUICSessionTicketOptions":     reflect.TypeOf((*q.QUICSessionTicketOptions)(nil)).Elem(),
				"RecordHeaderError":            reflect.TypeOf((*q.RecordHeaderError)(nil)).Elem(),
				"RenegotiationSupport":         reflect.TypeOf((*q.RenegotiationSupport)(nil)).Elem(),
				"SessionState":                 reflect.TypeOf((*q.SessionState)(nil)).Elem(),
				"SignatureScheme":              reflect.TypeOf((*q.SignatureScheme)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars:       map[string]interface{}{},
			Funcs: map[string]interface{}{
				"CipherSuiteName":          q.CipherSuiteName,
				"CipherSuites":             q.CipherSuites,
				"Client":                   q.Client,
				"Dial":                     q.Dial,
				"DialWithDialer":           q.DialWithDialer,
				"InsecureCipherSuites":     q.InsecureCipherSuites,
				"Listen":                   q.Listen,
				"LoadX509KeyPair":          q.LoadX509KeyPair,
				"NewLRUClientSessionCache": q.NewLRUClientSessionCache,
				"NewListener":              q.NewListener,
				"NewResumptionState":       q.NewResumptionState,
				"ParseSessionState":        q.ParseSessionState,
				"QUICClient":               q.QUICClient,
				"QUICServer":               q.QUICServer,
				"Server":                   q.Server,
				"VersionName":              q.VersionName,
				"X509KeyPair":              q.X509KeyPair,
			},
			TypedConsts: map[string]interface{}{
				"CurveP256":                                     q.CurveP256,
				"CurveP384":                                     q.CurveP384,
				"CurveP521":                                     q.CurveP521,
				"ECDSAWithP256AndSHA256":                        q.ECDSAWithP256AndSHA256,
				"ECDSAWithP384AndSHA384":                        q.ECDSAWithP384AndSHA384,
				"ECDSAWithP521AndSHA512":                        q.ECDSAWithP521AndSHA512,
				"ECDSAWithSHA1":                                 q.ECDSAWithSHA1,
				"Ed25519":                                       q.Ed25519,
				"NoClientCert":                                  q.NoClientCert,
				"PKCS1WithSHA1":                                 q.PKCS1WithSHA1,
				"PKCS1WithSHA256":                               q.PKCS1WithSHA256,
				"PKCS1WithSHA384":                               q.PKCS1WithSHA384,
				"PKCS1WithSHA512":                               q.PKCS1WithSHA512,
				"PSSWithSHA256":                                 q.PSSWithSHA256,
				"PSSWithSHA384":                                 q.PSSWithSHA384,
				"PSSWithSHA512":                                 q.PSSWithSHA512,
				"QUICEncryptionLevelApplication":                q.QUICEncryptionLevelApplication,
				"QUICEncryptionLevelEarly":                      q.QUICEncryptionLevelEarly,
				"QUICEncryptionLevelHandshake":                  q.QUICEncryptionLevelHandshake,
				"QUICEncryptionLevelInitial":                    q.QUICEncryptionLevelInitial,
				"QUICErrorEvent":                                q.QUICErrorEvent,
				"QUICHandshakeDone":                             q.QUICHandshakeDone,
				"QUICNoEvent":                                   q.QUICNoEvent,
				"QUICRejectedEarlyData":                         q.QUICRejectedEarlyData,
				"QUICResumeSession":                             q.QUICResumeSession,
				"QUICSetReadSecret":                             q.QUICSetReadSecret,
				"QUICSetWriteSecret":                            q.QUICSetWriteSecret,
				"QUICStoreSession":                              q.QUICStoreSession,
				"QUICTransportParameters":                       q.QUICTransportParameters,
				"QUICTransportParametersRequired":               q.QUICTransportParametersRequired,
				"QUICWriteData":                                 q.QUICWriteData,
				"RenegotiateFreelyAsClient":                     q.RenegotiateFreelyAsClient,
				"RenegotiateNever":                              q.RenegotiateNever,
				"RenegotiateOnceAsClient":                       q.RenegotiateOnceAsClient,
				"RequestClientCert":                             q.RequestClientCert,
				"RequireAndVerifyClientCert":                    q.RequireAndVerifyClientCert,
				"RequireAnyClientCert":                          q.RequireAnyClientCert,
				"SecP256r1MLKEM768":                             q.SecP256r1MLKEM768,
				"SecP384r1MLKEM1024":                            q.SecP384r1MLKEM1024,
				"TLS_AES_128_GCM_SHA256":                        q.TLS_AES_128_GCM_SHA256,
				"TLS_AES_256_GCM_SHA384":                        q.TLS_AES_256_GCM_SHA384,
				"TLS_CHACHA20_POLY1305_SHA256":                  q.TLS_CHACHA20_POLY1305_SHA256,
				"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA":          q.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
				"TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256":       q.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,
				"TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256":       q.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
				"TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA":          q.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
				"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384":       q.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
				"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305":        q.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
				"TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256": q.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
				"TLS_ECDHE_ECDSA_WITH_RC4_128_SHA":              q.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,
				"TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA":           q.TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA,
				"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA":            q.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
				"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256":         q.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,
				"TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256":         q.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
				"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA":            q.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
				"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384":         q.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
				"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305":          q.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
				"TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256":   q.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
				"TLS_ECDHE_RSA_WITH_RC4_128_SHA":                q.TLS_ECDHE_RSA_WITH_RC4_128_SHA,
				"TLS_FALLBACK_SCSV":                             q.TLS_FALLBACK_SCSV,
				"TLS_RSA_WITH_3DES_EDE_CBC_SHA":                 q.TLS_RSA_WITH_3DES_EDE_CBC_SHA,
				"TLS_RSA_WITH_AES_128_CBC_SHA":                  q.TLS_RSA_WITH_AES_128_CBC_SHA,
				"TLS_RSA_WITH_AES_128_CBC_SHA256":               q.TLS_RSA_WITH_AES_128_CBC_SHA256,
				"TLS_RSA_WITH_AES_128_GCM_SHA256":               q.TLS_RSA_WITH_AES_128_GCM_SHA256,
				"TLS_RSA_WITH_AES_256_CBC_SHA":                  q.TLS_RSA_WITH_AES_256_CBC_SHA,
				"TLS_RSA_WITH_AES_256_GCM_SHA384":               q.TLS_RSA_WITH_AES_256_GCM_SHA384,
				"TLS_RSA_WITH_RC4_128_SHA":                      q.TLS_RSA_WITH_RC4_128_SHA,
				"VerifyClientCertIfGiven":                       q.VerifyClientCertIfGiven,
				"X25519":                                        q.X25519,
				"X25519MLKEM768":                                q.X25519MLKEM768,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"VersionSSL30": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.VersionSSL30))},
				"VersionTLS10": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.VersionTLS10))},
				"VersionTLS11": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.VersionTLS11))},
				"VersionTLS12": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.VersionTLS12))},
				"VersionTLS13": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.VersionTLS13))},
			},
		}
	})
}
