// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.26
// +build go1.26

package syscall

import (
	q "syscall"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage(&ixgo.Package{
		Name: "syscall",
		Path: "syscall",
		Deps: map[string]string{
			"errors":               "errors",
			"internal/bytealg":     "bytealg",
			"internal/byteorder":   "byteorder",
			"internal/goarch":      "goarch",
			"internal/oserror":     "oserror",
			"internal/strconv":     "strconv",
			"internal/stringslite": "stringslite",
			"runtime":              "runtime",
			"structs":              "structs",
			"sync":                 "sync",
			"unsafe":               "unsafe",
		},
		Interfaces: map[string]reflect.Type{
			"Conn":     reflect.TypeOf((*q.Conn)(nil)).Elem(),
			"RawConn":  reflect.TypeOf((*q.RawConn)(nil)).Elem(),
			"Sockaddr": reflect.TypeOf((*q.Sockaddr)(nil)).Elem(),
		},
		NamedTypes: map[string]reflect.Type{
			"Dirent":        reflect.TypeOf((*q.Dirent)(nil)).Elem(),
			"Errno":         reflect.TypeOf((*q.Errno)(nil)).Elem(),
			"ProcAttr":      reflect.TypeOf((*q.ProcAttr)(nil)).Elem(),
			"Rlimit":        reflect.TypeOf((*q.Rlimit)(nil)).Elem(),
			"Rusage":        reflect.TypeOf((*q.Rusage)(nil)).Elem(),
			"Signal":        reflect.TypeOf((*q.Signal)(nil)).Elem(),
			"SockaddrInet4": reflect.TypeOf((*q.SockaddrInet4)(nil)).Elem(),
			"SockaddrInet6": reflect.TypeOf((*q.SockaddrInet6)(nil)).Elem(),
			"SockaddrUnix":  reflect.TypeOf((*q.SockaddrUnix)(nil)).Elem(),
			"Stat_t":        reflect.TypeOf((*q.Stat_t)(nil)).Elem(),
			"SysProcAttr":   reflect.TypeOf((*q.SysProcAttr)(nil)).Elem(),
			"Timespec":      reflect.TypeOf((*q.Timespec)(nil)).Elem(),
			"Timeval":       reflect.TypeOf((*q.Timeval)(nil)).Elem(),
			"WaitStatus":    reflect.TypeOf((*q.WaitStatus)(nil)).Elem(),
		},
		AliasTypes: map[string]reflect.Type{
			"Dircookie": reflect.TypeOf((*q.Dircookie)(nil)).Elem(),
			"Filetype":  reflect.TypeOf((*q.Filetype)(nil)).Elem(),
		},
		Vars: map[string]reflect.Value{},
		Funcs: map[string]reflect.Value{
			"Accept":              reflect.ValueOf(q.Accept),
			"Bind":                reflect.ValueOf(q.Bind),
			"BytePtrFromString":   reflect.ValueOf(q.BytePtrFromString),
			"ByteSliceFromString": reflect.ValueOf(q.ByteSliceFromString),
			"Chdir":               reflect.ValueOf(q.Chdir),
			"Chmod":               reflect.ValueOf(q.Chmod),
			"Chown":               reflect.ValueOf(q.Chown),
			"Clearenv":            reflect.ValueOf(q.Clearenv),
			"Close":               reflect.ValueOf(q.Close),
			"CloseOnExec":         reflect.ValueOf(q.CloseOnExec),
			"Connect":             reflect.ValueOf(q.Connect),
			"Dup":                 reflect.ValueOf(q.Dup),
			"Dup2":                reflect.ValueOf(q.Dup2),
			"Environ":             reflect.ValueOf(q.Environ),
			"Exit":                reflect.ValueOf(q.Exit),
			"Fchmod":              reflect.ValueOf(q.Fchmod),
			"Fchown":              reflect.ValueOf(q.Fchown),
			"Fstat":               reflect.ValueOf(q.Fstat),
			"Fsync":               reflect.ValueOf(q.Fsync),
			"Ftruncate":           reflect.ValueOf(q.Ftruncate),
			"Getegid":             reflect.ValueOf(q.Getegid),
			"Getenv":              reflect.ValueOf(q.Getenv),
			"Geteuid":             reflect.ValueOf(q.Geteuid),
			"Getgid":              reflect.ValueOf(q.Getgid),
			"Getgroups":           reflect.ValueOf(q.Getgroups),
			"Getpagesize":         reflect.ValueOf(q.Getpagesize),
			"Getpid":              reflect.ValueOf(q.Getpid),
			"Getppid":             reflect.ValueOf(q.Getppid),
			"Getrlimit":           reflect.ValueOf(q.Getrlimit),
			"GetsockoptInt":       reflect.ValueOf(q.GetsockoptInt),
			"Gettimeofday":        reflect.ValueOf(q.Gettimeofday),
			"Getuid":              reflect.ValueOf(q.Getuid),
			"Getwd":               reflect.ValueOf(q.Getwd),
			"Kill":                reflect.ValueOf(q.Kill),
			"Lchown":              reflect.ValueOf(q.Lchown),
			"Link":                reflect.ValueOf(q.Link),
			"Listen":              reflect.ValueOf(q.Listen),
			"Lstat":               reflect.ValueOf(q.Lstat),
			"Mkdir":               reflect.ValueOf(q.Mkdir),
			"NsecToTimespec":      reflect.ValueOf(q.NsecToTimespec),
			"NsecToTimeval":       reflect.ValueOf(q.NsecToTimeval),
			"Open":                reflect.ValueOf(q.Open),
			"Openat":              reflect.ValueOf(q.Openat),
			"ParseDirent":         reflect.ValueOf(q.ParseDirent),
			"Pipe":                reflect.ValueOf(q.Pipe),
			"Pread":               reflect.ValueOf(q.Pread),
			"ProcExit":            reflect.ValueOf(q.ProcExit),
			"Pwrite":              reflect.ValueOf(q.Pwrite),
			"RandomGet":           reflect.ValueOf(q.RandomGet),
			"RawSyscall":          reflect.ValueOf(q.RawSyscall),
			"RawSyscall6":         reflect.ValueOf(q.RawSyscall6),
			"Read":                reflect.ValueOf(q.Read),
			"ReadDir":             reflect.ValueOf(q.ReadDir),
			"Readlink":            reflect.ValueOf(q.Readlink),
			"Recvfrom":            reflect.ValueOf(q.Recvfrom),
			"Recvmsg":             reflect.ValueOf(q.Recvmsg),
			"Rename":              reflect.ValueOf(q.Rename),
			"Rmdir":               reflect.ValueOf(q.Rmdir),
			"Seek":                reflect.ValueOf(q.Seek),
			"Sendfile":            reflect.ValueOf(q.Sendfile),
			"SendmsgN":            reflect.ValueOf(q.SendmsgN),
			"Sendto":              reflect.ValueOf(q.Sendto),
			"SetNonblock":         reflect.ValueOf(q.SetNonblock),
			"SetReadDeadline":     reflect.ValueOf(q.SetReadDeadline),
			"SetWriteDeadline":    reflect.ValueOf(q.SetWriteDeadline),
			"Setenv":              reflect.ValueOf(q.Setenv),
			"SetsockoptInt":       reflect.ValueOf(q.SetsockoptInt),
			"Shutdown":            reflect.ValueOf(q.Shutdown),
			"Socket":              reflect.ValueOf(q.Socket),
			"StartProcess":        reflect.ValueOf(q.StartProcess),
			"Stat":                reflect.ValueOf(q.Stat),
			"StopIO":              reflect.ValueOf(q.StopIO),
			"StringBytePtr":       reflect.ValueOf(q.StringBytePtr),
			"StringByteSlice":     reflect.ValueOf(q.StringByteSlice),
			"Symlink":             reflect.ValueOf(q.Symlink),
			"Syscall":             reflect.ValueOf(q.Syscall),
			"Syscall6":            reflect.ValueOf(q.Syscall6),
			"Sysctl":              reflect.ValueOf(q.Sysctl),
			"TimespecToNsec":      reflect.ValueOf(q.TimespecToNsec),
			"TimevalToNsec":       reflect.ValueOf(q.TimevalToNsec),
			"Truncate":            reflect.ValueOf(q.Truncate),
			"Umask":               reflect.ValueOf(q.Umask),
			"Unlink":              reflect.ValueOf(q.Unlink),
			"Unsetenv":            reflect.ValueOf(q.Unsetenv),
			"UtimesNano":          reflect.ValueOf(q.UtimesNano),
			"Wait4":               reflect.ValueOf(q.Wait4),
			"Write":               reflect.ValueOf(q.Write),
		},
		TypedConsts: map[string]ixgo.TypedConst{
			"E2BIG":                     {Typ: reflect.TypeOf(q.E2BIG), Value: constant.MakeInt64(int64(q.E2BIG))},
			"EACCES":                    {Typ: reflect.TypeOf(q.EACCES), Value: constant.MakeInt64(int64(q.EACCES))},
			"EADDRINUSE":                {Typ: reflect.TypeOf(q.EADDRINUSE), Value: constant.MakeInt64(int64(q.EADDRINUSE))},
			"EADDRNOTAVAIL":             {Typ: reflect.TypeOf(q.EADDRNOTAVAIL), Value: constant.MakeInt64(int64(q.EADDRNOTAVAIL))},
			"EAFNOSUPPORT":              {Typ: reflect.TypeOf(q.EAFNOSUPPORT), Value: constant.MakeInt64(int64(q.EAFNOSUPPORT))},
			"EAGAIN":                    {Typ: reflect.TypeOf(q.EAGAIN), Value: constant.MakeInt64(int64(q.EAGAIN))},
			"EALREADY":                  {Typ: reflect.TypeOf(q.EALREADY), Value: constant.MakeInt64(int64(q.EALREADY))},
			"EBADF":                     {Typ: reflect.TypeOf(q.EBADF), Value: constant.MakeInt64(int64(q.EBADF))},
			"EBADFD":                    {Typ: reflect.TypeOf(q.EBADFD), Value: constant.MakeInt64(int64(q.EBADFD))},
			"EBADMSG":                   {Typ: reflect.TypeOf(q.EBADMSG), Value: constant.MakeInt64(int64(q.EBADMSG))},
			"EBUSY":                     {Typ: reflect.TypeOf(q.EBUSY), Value: constant.MakeInt64(int64(q.EBUSY))},
			"ECANCELED":                 {Typ: reflect.TypeOf(q.ECANCELED), Value: constant.MakeInt64(int64(q.ECANCELED))},
			"ECHILD":                    {Typ: reflect.TypeOf(q.ECHILD), Value: constant.MakeInt64(int64(q.ECHILD))},
			"ECONNABORTED":              {Typ: reflect.TypeOf(q.ECONNABORTED), Value: constant.MakeInt64(int64(q.ECONNABORTED))},
			"ECONNREFUSED":              {Typ: reflect.TypeOf(q.ECONNREFUSED), Value: constant.MakeInt64(int64(q.ECONNREFUSED))},
			"ECONNRESET":                {Typ: reflect.TypeOf(q.ECONNRESET), Value: constant.MakeInt64(int64(q.ECONNRESET))},
			"EDEADLK":                   {Typ: reflect.TypeOf(q.EDEADLK), Value: constant.MakeInt64(int64(q.EDEADLK))},
			"EDESTADDRREQ":              {Typ: reflect.TypeOf(q.EDESTADDRREQ), Value: constant.MakeInt64(int64(q.EDESTADDRREQ))},
			"EDOM":                      {Typ: reflect.TypeOf(q.EDOM), Value: constant.MakeInt64(int64(q.EDOM))},
			"EDQUOT":                    {Typ: reflect.TypeOf(q.EDQUOT), Value: constant.MakeInt64(int64(q.EDQUOT))},
			"EEXIST":                    {Typ: reflect.TypeOf(q.EEXIST), Value: constant.MakeInt64(int64(q.EEXIST))},
			"EFAULT":                    {Typ: reflect.TypeOf(q.EFAULT), Value: constant.MakeInt64(int64(q.EFAULT))},
			"EFBIG":                     {Typ: reflect.TypeOf(q.EFBIG), Value: constant.MakeInt64(int64(q.EFBIG))},
			"EHOSTUNREACH":              {Typ: reflect.TypeOf(q.EHOSTUNREACH), Value: constant.MakeInt64(int64(q.EHOSTUNREACH))},
			"EIDRM":                     {Typ: reflect.TypeOf(q.EIDRM), Value: constant.MakeInt64(int64(q.EIDRM))},
			"EILSEQ":                    {Typ: reflect.TypeOf(q.EILSEQ), Value: constant.MakeInt64(int64(q.EILSEQ))},
			"EINPROGRESS":               {Typ: reflect.TypeOf(q.EINPROGRESS), Value: constant.MakeInt64(int64(q.EINPROGRESS))},
			"EINTR":                     {Typ: reflect.TypeOf(q.EINTR), Value: constant.MakeInt64(int64(q.EINTR))},
			"EINVAL":                    {Typ: reflect.TypeOf(q.EINVAL), Value: constant.MakeInt64(int64(q.EINVAL))},
			"EIO":                       {Typ: reflect.TypeOf(q.EIO), Value: constant.MakeInt64(int64(q.EIO))},
			"EISCONN":                   {Typ: reflect.TypeOf(q.EISCONN), Value: constant.MakeInt64(int64(q.EISCONN))},
			"EISDIR":                    {Typ: reflect.TypeOf(q.EISDIR), Value: constant.MakeInt64(int64(q.EISDIR))},
			"ELOOP":                     {Typ: reflect.TypeOf(q.ELOOP), Value: constant.MakeInt64(int64(q.ELOOP))},
			"EMFILE":                    {Typ: reflect.TypeOf(q.EMFILE), Value: constant.MakeInt64(int64(q.EMFILE))},
			"EMLINK":                    {Typ: reflect.TypeOf(q.EMLINK), Value: constant.MakeInt64(int64(q.EMLINK))},
			"EMSGSIZE":                  {Typ: reflect.TypeOf(q.EMSGSIZE), Value: constant.MakeInt64(int64(q.EMSGSIZE))},
			"EMULTIHOP":                 {Typ: reflect.TypeOf(q.EMULTIHOP), Value: constant.MakeInt64(int64(q.EMULTIHOP))},
			"ENAMETOOLONG":              {Typ: reflect.TypeOf(q.ENAMETOOLONG), Value: constant.MakeInt64(int64(q.ENAMETOOLONG))},
			"ENETDOWN":                  {Typ: reflect.TypeOf(q.ENETDOWN), Value: constant.MakeInt64(int64(q.ENETDOWN))},
			"ENETRESET":                 {Typ: reflect.TypeOf(q.ENETRESET), Value: constant.MakeInt64(int64(q.ENETRESET))},
			"ENETUNREACH":               {Typ: reflect.TypeOf(q.ENETUNREACH), Value: constant.MakeInt64(int64(q.ENETUNREACH))},
			"ENFILE":                    {Typ: reflect.TypeOf(q.ENFILE), Value: constant.MakeInt64(int64(q.ENFILE))},
			"ENOBUFS":                   {Typ: reflect.TypeOf(q.ENOBUFS), Value: constant.MakeInt64(int64(q.ENOBUFS))},
			"ENODEV":                    {Typ: reflect.TypeOf(q.ENODEV), Value: constant.MakeInt64(int64(q.ENODEV))},
			"ENOENT":                    {Typ: reflect.TypeOf(q.ENOENT), Value: constant.MakeInt64(int64(q.ENOENT))},
			"ENOEXEC":                   {Typ: reflect.TypeOf(q.ENOEXEC), Value: constant.MakeInt64(int64(q.ENOEXEC))},
			"ENOLCK":                    {Typ: reflect.TypeOf(q.ENOLCK), Value: constant.MakeInt64(int64(q.ENOLCK))},
			"ENOLINK":                   {Typ: reflect.TypeOf(q.ENOLINK), Value: constant.MakeInt64(int64(q.ENOLINK))},
			"ENOMEM":                    {Typ: reflect.TypeOf(q.ENOMEM), Value: constant.MakeInt64(int64(q.ENOMEM))},
			"ENOMSG":                    {Typ: reflect.TypeOf(q.ENOMSG), Value: constant.MakeInt64(int64(q.ENOMSG))},
			"ENOPROTOOPT":               {Typ: reflect.TypeOf(q.ENOPROTOOPT), Value: constant.MakeInt64(int64(q.ENOPROTOOPT))},
			"ENOSPC":                    {Typ: reflect.TypeOf(q.ENOSPC), Value: constant.MakeInt64(int64(q.ENOSPC))},
			"ENOSYS":                    {Typ: reflect.TypeOf(q.ENOSYS), Value: constant.MakeInt64(int64(q.ENOSYS))},
			"ENOTCAPABLE":               {Typ: reflect.TypeOf(q.ENOTCAPABLE), Value: constant.MakeInt64(int64(q.ENOTCAPABLE))},
			"ENOTCONN":                  {Typ: reflect.TypeOf(q.ENOTCONN), Value: constant.MakeInt64(int64(q.ENOTCONN))},
			"ENOTDIR":                   {Typ: reflect.TypeOf(q.ENOTDIR), Value: constant.MakeInt64(int64(q.ENOTDIR))},
			"ENOTEMPTY":                 {Typ: reflect.TypeOf(q.ENOTEMPTY), Value: constant.MakeInt64(int64(q.ENOTEMPTY))},
			"ENOTRECOVERABLE":           {Typ: reflect.TypeOf(q.ENOTRECOVERABLE), Value: constant.MakeInt64(int64(q.ENOTRECOVERABLE))},
			"ENOTSOCK":                  {Typ: reflect.TypeOf(q.ENOTSOCK), Value: constant.MakeInt64(int64(q.ENOTSOCK))},
			"ENOTSUP":                   {Typ: reflect.TypeOf(q.ENOTSUP), Value: constant.MakeInt64(int64(q.ENOTSUP))},
			"ENOTTY":                    {Typ: reflect.TypeOf(q.ENOTTY), Value: constant.MakeInt64(int64(q.ENOTTY))},
			"ENXIO":                     {Typ: reflect.TypeOf(q.ENXIO), Value: constant.MakeInt64(int64(q.ENXIO))},
			"EOPNOTSUPP":                {Typ: reflect.TypeOf(q.EOPNOTSUPP), Value: constant.MakeInt64(int64(q.EOPNOTSUPP))},
			"EOVERFLOW":                 {Typ: reflect.TypeOf(q.EOVERFLOW), Value: constant.MakeInt64(int64(q.EOVERFLOW))},
			"EOWNERDEAD":                {Typ: reflect.TypeOf(q.EOWNERDEAD), Value: constant.MakeInt64(int64(q.EOWNERDEAD))},
			"EPERM":                     {Typ: reflect.TypeOf(q.EPERM), Value: constant.MakeInt64(int64(q.EPERM))},
			"EPIPE":                     {Typ: reflect.TypeOf(q.EPIPE), Value: constant.MakeInt64(int64(q.EPIPE))},
			"EPROTO":                    {Typ: reflect.TypeOf(q.EPROTO), Value: constant.MakeInt64(int64(q.EPROTO))},
			"EPROTONOSUPPORT":           {Typ: reflect.TypeOf(q.EPROTONOSUPPORT), Value: constant.MakeInt64(int64(q.EPROTONOSUPPORT))},
			"EPROTOTYPE":                {Typ: reflect.TypeOf(q.EPROTOTYPE), Value: constant.MakeInt64(int64(q.EPROTOTYPE))},
			"ERANGE":                    {Typ: reflect.TypeOf(q.ERANGE), Value: constant.MakeInt64(int64(q.ERANGE))},
			"EROFS":                     {Typ: reflect.TypeOf(q.EROFS), Value: constant.MakeInt64(int64(q.EROFS))},
			"ESPIPE":                    {Typ: reflect.TypeOf(q.ESPIPE), Value: constant.MakeInt64(int64(q.ESPIPE))},
			"ESRCH":                     {Typ: reflect.TypeOf(q.ESRCH), Value: constant.MakeInt64(int64(q.ESRCH))},
			"ESTALE":                    {Typ: reflect.TypeOf(q.ESTALE), Value: constant.MakeInt64(int64(q.ESTALE))},
			"ETIMEDOUT":                 {Typ: reflect.TypeOf(q.ETIMEDOUT), Value: constant.MakeInt64(int64(q.ETIMEDOUT))},
			"ETXTBSY":                   {Typ: reflect.TypeOf(q.ETXTBSY), Value: constant.MakeInt64(int64(q.ETXTBSY))},
			"EXDEV":                     {Typ: reflect.TypeOf(q.EXDEV), Value: constant.MakeInt64(int64(q.EXDEV))},
			"FILETYPE_BLOCK_DEVICE":     {Typ: reflect.TypeOf(q.FILETYPE_BLOCK_DEVICE), Value: constant.MakeInt64(int64(q.FILETYPE_BLOCK_DEVICE))},
			"FILETYPE_CHARACTER_DEVICE": {Typ: reflect.TypeOf(q.FILETYPE_CHARACTER_DEVICE), Value: constant.MakeInt64(int64(q.FILETYPE_CHARACTER_DEVICE))},
			"FILETYPE_DIRECTORY":        {Typ: reflect.TypeOf(q.FILETYPE_DIRECTORY), Value: constant.MakeInt64(int64(q.FILETYPE_DIRECTORY))},
			"FILETYPE_REGULAR_FILE":     {Typ: reflect.TypeOf(q.FILETYPE_REGULAR_FILE), Value: constant.MakeInt64(int64(q.FILETYPE_REGULAR_FILE))},
			"FILETYPE_SOCKET_DGRAM":     {Typ: reflect.TypeOf(q.FILETYPE_SOCKET_DGRAM), Value: constant.MakeInt64(int64(q.FILETYPE_SOCKET_DGRAM))},
			"FILETYPE_SOCKET_STREAM":    {Typ: reflect.TypeOf(q.FILETYPE_SOCKET_STREAM), Value: constant.MakeInt64(int64(q.FILETYPE_SOCKET_STREAM))},
			"FILETYPE_SYMBOLIC_LINK":    {Typ: reflect.TypeOf(q.FILETYPE_SYMBOLIC_LINK), Value: constant.MakeInt64(int64(q.FILETYPE_SYMBOLIC_LINK))},
			"FILETYPE_UNKNOWN":          {Typ: reflect.TypeOf(q.FILETYPE_UNKNOWN), Value: constant.MakeInt64(int64(q.FILETYPE_UNKNOWN))},
			"SIGABRT":                   {Typ: reflect.TypeOf(q.SIGABRT), Value: constant.MakeInt64(int64(q.SIGABRT))},
			"SIGALRM":                   {Typ: reflect.TypeOf(q.SIGALRM), Value: constant.MakeInt64(int64(q.SIGALRM))},
			"SIGBUS":                    {Typ: reflect.TypeOf(q.SIGBUS), Value: constant.MakeInt64(int64(q.SIGBUS))},
			"SIGCHLD":                   {Typ: reflect.TypeOf(q.SIGCHLD), Value: constant.MakeInt64(int64(q.SIGCHLD))},
			"SIGCONT":                   {Typ: reflect.TypeOf(q.SIGCONT), Value: constant.MakeInt64(int64(q.SIGCONT))},
			"SIGFPE":                    {Typ: reflect.TypeOf(q.SIGFPE), Value: constant.MakeInt64(int64(q.SIGFPE))},
			"SIGHUP":                    {Typ: reflect.TypeOf(q.SIGHUP), Value: constant.MakeInt64(int64(q.SIGHUP))},
			"SIGILL":                    {Typ: reflect.TypeOf(q.SIGILL), Value: constant.MakeInt64(int64(q.SIGILL))},
			"SIGINT":                    {Typ: reflect.TypeOf(q.SIGINT), Value: constant.MakeInt64(int64(q.SIGINT))},
			"SIGKILL":                   {Typ: reflect.TypeOf(q.SIGKILL), Value: constant.MakeInt64(int64(q.SIGKILL))},
			"SIGNONE":                   {Typ: reflect.TypeOf(q.SIGNONE), Value: constant.MakeInt64(int64(q.SIGNONE))},
			"SIGPIPE":                   {Typ: reflect.TypeOf(q.SIGPIPE), Value: constant.MakeInt64(int64(q.SIGPIPE))},
			"SIGPOLL":                   {Typ: reflect.TypeOf(q.SIGPOLL), Value: constant.MakeInt64(int64(q.SIGPOLL))},
			"SIGPROF":                   {Typ: reflect.TypeOf(q.SIGPROF), Value: constant.MakeInt64(int64(q.SIGPROF))},
			"SIGPWR":                    {Typ: reflect.TypeOf(q.SIGPWR), Value: constant.MakeInt64(int64(q.SIGPWR))},
			"SIGQUIT":                   {Typ: reflect.TypeOf(q.SIGQUIT), Value: constant.MakeInt64(int64(q.SIGQUIT))},
			"SIGSEGV":                   {Typ: reflect.TypeOf(q.SIGSEGV), Value: constant.MakeInt64(int64(q.SIGSEGV))},
			"SIGSTOP":                   {Typ: reflect.TypeOf(q.SIGSTOP), Value: constant.MakeInt64(int64(q.SIGSTOP))},
			"SIGSYS":                    {Typ: reflect.TypeOf(q.SIGSYS), Value: constant.MakeInt64(int64(q.SIGSYS))},
			"SIGTERM":                   {Typ: reflect.TypeOf(q.SIGTERM), Value: constant.MakeInt64(int64(q.SIGTERM))},
			"SIGTRAP":                   {Typ: reflect.TypeOf(q.SIGTRAP), Value: constant.MakeInt64(int64(q.SIGTRAP))},
			"SIGTSTP":                   {Typ: reflect.TypeOf(q.SIGTSTP), Value: constant.MakeInt64(int64(q.SIGTSTP))},
			"SIGTTIN":                   {Typ: reflect.TypeOf(q.SIGTTIN), Value: constant.MakeInt64(int64(q.SIGTTIN))},
			"SIGTTOU":                   {Typ: reflect.TypeOf(q.SIGTTOU), Value: constant.MakeInt64(int64(q.SIGTTOU))},
			"SIGURG":                    {Typ: reflect.TypeOf(q.SIGURG), Value: constant.MakeInt64(int64(q.SIGURG))},
			"SIGUSR1":                   {Typ: reflect.TypeOf(q.SIGUSR1), Value: constant.MakeInt64(int64(q.SIGUSR1))},
			"SIGUSR2":                   {Typ: reflect.TypeOf(q.SIGUSR2), Value: constant.MakeInt64(int64(q.SIGUSR2))},
			"SIGVTARLM":                 {Typ: reflect.TypeOf(q.SIGVTARLM), Value: constant.MakeInt64(int64(q.SIGVTARLM))},
			"SIGWINCH":                  {Typ: reflect.TypeOf(q.SIGWINCH), Value: constant.MakeInt64(int64(q.SIGWINCH))},
			"SIGXCPU":                   {Typ: reflect.TypeOf(q.SIGXCPU), Value: constant.MakeInt64(int64(q.SIGXCPU))},
			"SIGXFSZ":                   {Typ: reflect.TypeOf(q.SIGXFSZ), Value: constant.MakeInt64(int64(q.SIGXFSZ))},
		},
		UntypedConsts: map[string]ixgo.UntypedConst{
			"AF_INET":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_INET))},
			"AF_INET6":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_INET6))},
			"AF_UNIX":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_UNIX))},
			"AF_UNSPEC":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_UNSPEC))},
			"FDFLAG_APPEND":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FDFLAG_APPEND))},
			"FDFLAG_DSYNC":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FDFLAG_DSYNC))},
			"FDFLAG_NONBLOCK":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FDFLAG_NONBLOCK))},
			"FDFLAG_RSYNC":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FDFLAG_RSYNC))},
			"FDFLAG_SYNC":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FDFLAG_SYNC))},
			"FILESTAT_SET_ATIM":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FILESTAT_SET_ATIM))},
			"FILESTAT_SET_ATIM_NOW":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FILESTAT_SET_ATIM_NOW))},
			"FILESTAT_SET_MTIM":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FILESTAT_SET_MTIM))},
			"FILESTAT_SET_MTIM_NOW":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FILESTAT_SET_MTIM_NOW))},
			"F_CNVT":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_CNVT))},
			"F_DUPFD":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_DUPFD))},
			"F_DUPFD_CLOEXEC":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_DUPFD_CLOEXEC))},
			"F_GETFD":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETFD))},
			"F_GETFL":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETFL))},
			"F_GETLK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETLK))},
			"F_GETOWN":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETOWN))},
			"F_RDLCK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RDLCK))},
			"F_RGETLK":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RGETLK))},
			"F_RSETLK":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RSETLK))},
			"F_RSETLKW":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RSETLKW))},
			"F_SETFD":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETFD))},
			"F_SETFL":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETFL))},
			"F_SETLK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETLK))},
			"F_SETLKW":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETLKW))},
			"F_SETOWN":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETOWN))},
			"F_UNLCK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_UNLCK))},
			"F_UNLKSYS":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_UNLKSYS))},
			"F_WRLCK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_WRLCK))},
			"IPPROTO_IP":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IP))},
			"IPPROTO_IPV4":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IPV4))},
			"IPPROTO_IPV6":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IPV6))},
			"IPPROTO_TCP":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_TCP))},
			"IPPROTO_UDP":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_UDP))},
			"IPV6_V6ONLY":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPV6_V6ONLY))},
			"ImplementsGetwd":               {Typ: "untyped bool", Value: constant.MakeBool(bool(q.ImplementsGetwd))},
			"LOOKUP_SYMLINK_FOLLOW":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.LOOKUP_SYMLINK_FOLLOW))},
			"OFLAG_CREATE":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.OFLAG_CREATE))},
			"OFLAG_DIRECTORY":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.OFLAG_DIRECTORY))},
			"OFLAG_EXCL":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.OFLAG_EXCL))},
			"OFLAG_TRUNC":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.OFLAG_TRUNC))},
			"O_APPEND":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_APPEND))},
			"O_CLOEXEC":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CLOEXEC))},
			"O_CREAT":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CREAT))},
			"O_CREATE":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CREATE))},
			"O_DIRECTORY":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_DIRECTORY))},
			"O_EXCL":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_EXCL))},
			"O_NOFOLLOW":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_NOFOLLOW))},
			"O_RDONLY":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDONLY))},
			"O_RDWR":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDWR))},
			"O_SYNC":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_SYNC))},
			"O_TRUNC":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_TRUNC))},
			"O_WRONLY":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_WRONLY))},
			"RIGHT_FDSTAT_SET_FLAGS":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FDSTAT_SET_FLAGS))},
			"RIGHT_FD_ADVISE":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_ADVISE))},
			"RIGHT_FD_ALLOCATE":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_ALLOCATE))},
			"RIGHT_FD_DATASYNC":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_DATASYNC))},
			"RIGHT_FD_FILESTAT_GET":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_FILESTAT_GET))},
			"RIGHT_FD_FILESTAT_SET_SIZE":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_FILESTAT_SET_SIZE))},
			"RIGHT_FD_FILESTAT_SET_TIMES":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_FILESTAT_SET_TIMES))},
			"RIGHT_FD_READ":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_READ))},
			"RIGHT_FD_READDIR":              {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_READDIR))},
			"RIGHT_FD_SEEK":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_SEEK))},
			"RIGHT_FD_SYNC":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_SYNC))},
			"RIGHT_FD_TELL":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_TELL))},
			"RIGHT_FD_WRITE":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_WRITE))},
			"RIGHT_PATH_CREATE_DIRECTORY":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_CREATE_DIRECTORY))},
			"RIGHT_PATH_CREATE_FILE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_CREATE_FILE))},
			"RIGHT_PATH_FILESTAT_GET":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_FILESTAT_GET))},
			"RIGHT_PATH_FILESTAT_SET_SIZE":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_FILESTAT_SET_SIZE))},
			"RIGHT_PATH_FILESTAT_SET_TIMES": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_FILESTAT_SET_TIMES))},
			"RIGHT_PATH_LINK_SOURCE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_LINK_SOURCE))},
			"RIGHT_PATH_LINK_TARGET":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_LINK_TARGET))},
			"RIGHT_PATH_OPEN":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_OPEN))},
			"RIGHT_PATH_READLINK":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_READLINK))},
			"RIGHT_PATH_REMOVE_DIRECTORY":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_REMOVE_DIRECTORY))},
			"RIGHT_PATH_RENAME_SOURCE":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_RENAME_SOURCE))},
			"RIGHT_PATH_RENAME_TARGET":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_RENAME_TARGET))},
			"RIGHT_PATH_SYMLINK":            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_SYMLINK))},
			"RIGHT_PATH_UNLINK_FILE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_UNLINK_FILE))},
			"RIGHT_POLL_FD_READWRITE":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_POLL_FD_READWRITE))},
			"RIGHT_SOCK_ACCEPT":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_SOCK_ACCEPT))},
			"RIGHT_SOCK_SHUTDOWN":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_SOCK_SHUTDOWN))},
			"RLIMIT_NOFILE":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RLIMIT_NOFILE))},
			"SHUT_RD":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SHUT_RD))},
			"SHUT_RDWR":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SHUT_RDWR))},
			"SHUT_WR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SHUT_WR))},
			"SOCK_DGRAM":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_DGRAM))},
			"SOCK_RAW":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_RAW))},
			"SOCK_SEQPACKET":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_SEQPACKET))},
			"SOCK_STREAM":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_STREAM))},
			"SOMAXCONN":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOMAXCONN))},
			"SO_ERROR":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SO_ERROR))},
			"SYS_FCNTL":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FCNTL))},
			"S_IEXEC":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IEXEC))},
			"S_IFBLK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFBLK))},
			"S_IFBOUNDSOCK":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFBOUNDSOCK))},
			"S_IFCHR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFCHR))},
			"S_IFCOND":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFCOND))},
			"S_IFDIR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFDIR))},
			"S_IFDSOCK":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFDSOCK))},
			"S_IFIFO":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFIFO))},
			"S_IFLNK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFLNK))},
			"S_IFMT":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFMT))},
			"S_IFMUTEX":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFMUTEX))},
			"S_IFREG":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFREG))},
			"S_IFSEMA":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSEMA))},
			"S_IFSHM":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSHM))},
			"S_IFSHM_SYSV":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSHM_SYSV))},
			"S_IFSOCK":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSOCK))},
			"S_IFSOCKADDR":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSOCKADDR))},
			"S_IREAD":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IREAD))},
			"S_IRGRP":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRGRP))},
			"S_IROTH":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IROTH))},
			"S_IRUSR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRUSR))},
			"S_IRWXG":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXG))},
			"S_IRWXO":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXO))},
			"S_IRWXU":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXU))},
			"S_ISGID":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISGID))},
			"S_ISUID":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISUID))},
			"S_ISVTX":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISVTX))},
			"S_IWGRP":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWGRP))},
			"S_IWOTH":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWOTH))},
			"S_IWRITE":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWRITE))},
			"S_IWUSR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWUSR))},
			"S_IXGRP":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXGRP))},
			"S_IXOTH":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXOTH))},
			"S_IXUSR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXUSR))},
			"S_UNSUP":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_UNSUP))},
			"Stderr":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stderr))},
			"Stdin":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stdin))},
			"Stdout":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stdout))},
			"WHENCE_CUR":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.WHENCE_CUR))},
			"WHENCE_END":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.WHENCE_END))},
			"WHENCE_SET":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.WHENCE_SET))},
		},
	})
}
