// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.26
// +build go1.26

package syscall

import (
	q "syscall"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackageLazy("syscall", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "syscall",
			Path: "syscall",
			Deps: map[string]string{
				"errors":             "errors",
				"internal/bytealg":   "bytealg",
				"internal/byteorder": "byteorder",
				"internal/goarch":    "goarch",
				"internal/oserror":   "oserror",
				"internal/strconv":   "strconv",
				"runtime":            "runtime",
				"sync":               "sync",
				"syscall/js":         "js",
				"unsafe":             "unsafe",
			},
			Interfaces: map[string]reflect.Type{
				"Conn":     reflect.TypeOf((*q.Conn)(nil)).Elem(),
				"RawConn":  reflect.TypeOf((*q.RawConn)(nil)).Elem(),
				"Sockaddr": reflect.TypeOf((*q.Sockaddr)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Dirent":        reflect.TypeOf((*q.Dirent)(nil)).Elem(),
				"Errno":         reflect.TypeOf((*q.Errno)(nil)).Elem(),
				"Iovec":         reflect.TypeOf((*q.Iovec)(nil)).Elem(),
				"ProcAttr":      reflect.TypeOf((*q.ProcAttr)(nil)).Elem(),
				"Rusage":        reflect.TypeOf((*q.Rusage)(nil)).Elem(),
				"Signal":        reflect.TypeOf((*q.Signal)(nil)).Elem(),
				"SockaddrInet4": reflect.TypeOf((*q.SockaddrInet4)(nil)).Elem(),
				"SockaddrInet6": reflect.TypeOf((*q.SockaddrInet6)(nil)).Elem(),
				"SockaddrUnix":  reflect.TypeOf((*q.SockaddrUnix)(nil)).Elem(),
				"Stat_t":        reflect.TypeOf((*q.Stat_t)(nil)).Elem(),
				"SysProcAttr":   reflect.TypeOf((*q.SysProcAttr)(nil)).Elem(),
				"Timespec":      reflect.TypeOf((*q.Timespec)(nil)).Elem(),
				"Timeval":       reflect.TypeOf((*q.Timeval)(nil)).Elem(),
				"WaitStatus":    reflect.TypeOf((*q.WaitStatus)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]reflect.Value{
				"ForkLock": reflect.ValueOf(&q.ForkLock),
			},
			Funcs: map[string]reflect.Value{
				"Accept":              reflect.ValueOf(q.Accept),
				"Bind":                reflect.ValueOf(q.Bind),
				"BytePtrFromString":   reflect.ValueOf(q.BytePtrFromString),
				"ByteSliceFromString": reflect.ValueOf(q.ByteSliceFromString),
				"Chdir":               reflect.ValueOf(q.Chdir),
				"Chmod":               reflect.ValueOf(q.Chmod),
				"Chown":               reflect.ValueOf(q.Chown),
				"Clearenv":            reflect.ValueOf(q.Clearenv),
				"Close":               reflect.ValueOf(q.Close),
				"CloseOnExec":         reflect.ValueOf(q.CloseOnExec),
				"Connect":             reflect.ValueOf(q.Connect),
				"Dup":                 reflect.ValueOf(q.Dup),
				"Dup2":                reflect.ValueOf(q.Dup2),
				"Environ":             reflect.ValueOf(q.Environ),
				"Exit":                reflect.ValueOf(q.Exit),
				"Fchdir":              reflect.ValueOf(q.Fchdir),
				"Fchmod":              reflect.ValueOf(q.Fchmod),
				"Fchown":              reflect.ValueOf(q.Fchown),
				"Fstat":               reflect.ValueOf(q.Fstat),
				"Fsync":               reflect.ValueOf(q.Fsync),
				"Ftruncate":           reflect.ValueOf(q.Ftruncate),
				"Getcwd":              reflect.ValueOf(q.Getcwd),
				"Getegid":             reflect.ValueOf(q.Getegid),
				"Getenv":              reflect.ValueOf(q.Getenv),
				"Geteuid":             reflect.ValueOf(q.Geteuid),
				"Getgid":              reflect.ValueOf(q.Getgid),
				"Getgroups":           reflect.ValueOf(q.Getgroups),
				"Getpagesize":         reflect.ValueOf(q.Getpagesize),
				"Getpid":              reflect.ValueOf(q.Getpid),
				"Getppid":             reflect.ValueOf(q.Getppid),
				"GetsockoptInt":       reflect.ValueOf(q.GetsockoptInt),
				"Gettimeofday":        reflect.ValueOf(q.Gettimeofday),
				"Getuid":              reflect.ValueOf(q.Getuid),
				"Getwd":               reflect.ValueOf(q.Getwd),
				"Kill":                reflect.ValueOf(q.Kill),
				"Lchown":              reflect.ValueOf(q.Lchown),
				"Link":                reflect.ValueOf(q.Link),
				"Listen":              reflect.ValueOf(q.Listen),
				"Lstat":               reflect.ValueOf(q.Lstat),
				"Mkdir":               reflect.ValueOf(q.Mkdir),
				"NsecToTimespec":      reflect.ValueOf(q.NsecToTimespec),
				"NsecToTimeval":       reflect.ValueOf(q.NsecToTimeval),
				"Open":                reflect.ValueOf(q.Open),
				"ParseDirent":         reflect.ValueOf(q.ParseDirent),
				"Pipe":                reflect.ValueOf(q.Pipe),
				"Pread":               reflect.ValueOf(q.Pread),
				"Pwrite":              reflect.ValueOf(q.Pwrite),
				"RawSyscall":          reflect.ValueOf(q.RawSyscall),
				"RawSyscall6":         reflect.ValueOf(q.RawSyscall6),
				"Read":                reflect.ValueOf(q.Read),
				"ReadDirent":          reflect.ValueOf(q.ReadDirent),
				"Readlink":            reflect.ValueOf(q.Readlink),
				"Recvfrom":            reflect.ValueOf(q.Recvfrom),
				"Recvmsg":             reflect.ValueOf(q.Recvmsg),
				"Rename":              reflect.ValueOf(q.Rename),
				"Rmdir":               reflect.ValueOf(q.Rmdir),
				"Seek":                reflect.ValueOf(q.Seek),
				"Sendfile":            reflect.ValueOf(q.Sendfile),
				"SendmsgN":            reflect.ValueOf(q.SendmsgN),
				"Sendto":              reflect.ValueOf(q.Sendto),
				"SetNonblock":         reflect.ValueOf(q.SetNonblock),
				"SetReadDeadline":     reflect.ValueOf(q.SetReadDeadline),
				"SetWriteDeadline":    reflect.ValueOf(q.SetWriteDeadline),
				"Setenv":              reflect.ValueOf(q.Setenv),
				"SetsockoptInt":       reflect.ValueOf(q.SetsockoptInt),
				"Shutdown":            reflect.ValueOf(q.Shutdown),
				"Socket":              reflect.ValueOf(q.Socket),
				"StartProcess":        reflect.ValueOf(q.StartProcess),
				"Stat":                reflect.ValueOf(q.Stat),
				"StopIO":              reflect.ValueOf(q.StopIO),
				"StringBytePtr":       reflect.ValueOf(q.StringBytePtr),
				"StringByteSlice":     reflect.ValueOf(q.StringByteSlice),
				"Symlink":             reflect.ValueOf(q.Symlink),
				"Syscall":             reflect.ValueOf(q.Syscall),
				"Syscall6":            reflect.ValueOf(q.Syscall6),
				"Sysctl":              reflect.ValueOf(q.Sysctl),
				"TimespecToNsec":      reflect.ValueOf(q.TimespecToNsec),
				"TimevalToNsec":       reflect.ValueOf(q.TimevalToNsec),
				"Truncate":            reflect.ValueOf(q.Truncate),
				"Umask":               reflect.ValueOf(q.Umask),
				"Unlink":              reflect.ValueOf(q.Unlink),
				"Unsetenv":            reflect.ValueOf(q.Unsetenv),
				"UtimesNano":          reflect.ValueOf(q.UtimesNano),
				"Wait4":               reflect.ValueOf(q.Wait4),
				"Write":               reflect.ValueOf(q.Write),
			},
			TypedConsts: map[string]ixgo.TypedConst{
				"E2BIG":           {Typ: reflect.TypeOf(q.E2BIG), Value: constant.MakeInt64(int64(q.E2BIG))},
				"EACCES":          {Typ: reflect.TypeOf(q.EACCES), Value: constant.MakeInt64(int64(q.EACCES))},
				"EADDRINUSE":      {Typ: reflect.TypeOf(q.EADDRINUSE), Value: constant.MakeInt64(int64(q.EADDRINUSE))},
				"EADDRNOTAVAIL":   {Typ: reflect.TypeOf(q.EADDRNOTAVAIL), Value: constant.MakeInt64(int64(q.EADDRNOTAVAIL))},
				"EADV":            {Typ: reflect.TypeOf(q.EADV), Value: constant.MakeInt64(int64(q.EADV))},
				"EAFNOSUPPORT":    {Typ: reflect.TypeOf(q.EAFNOSUPPORT), Value: constant.MakeInt64(int64(q.EAFNOSUPPORT))},
				"EAGAIN":          {Typ: reflect.TypeOf(q.EAGAIN), Value: constant.MakeInt64(int64(q.EAGAIN))},
				"EALREADY":        {Typ: reflect.TypeOf(q.EALREADY), Value: constant.MakeInt64(int64(q.EALREADY))},
				"EBADE":           {Typ: reflect.TypeOf(q.EBADE), Value: constant.MakeInt64(int64(q.EBADE))},
				"EBADF":           {Typ: reflect.TypeOf(q.EBADF), Value: constant.MakeInt64(int64(q.EBADF))},
				"EBADFD":          {Typ: reflect.TypeOf(q.EBADFD), Value: constant.MakeInt64(int64(q.EBADFD))},
				"EBADMSG":         {Typ: reflect.TypeOf(q.EBADMSG), Value: constant.MakeInt64(int64(q.EBADMSG))},
				"EBADR":           {Typ: reflect.TypeOf(q.EBADR), Value: constant.MakeInt64(int64(q.EBADR))},
				"EBADRQC":         {Typ: reflect.TypeOf(q.EBADRQC), Value: constant.MakeInt64(int64(q.EBADRQC))},
				"EBADSLT":         {Typ: reflect.TypeOf(q.EBADSLT), Value: constant.MakeInt64(int64(q.EBADSLT))},
				"EBFONT":          {Typ: reflect.TypeOf(q.EBFONT), Value: constant.MakeInt64(int64(q.EBFONT))},
				"EBUSY":           {Typ: reflect.TypeOf(q.EBUSY), Value: constant.MakeInt64(int64(q.EBUSY))},
				"ECANCELED":       {Typ: reflect.TypeOf(q.ECANCELED), Value: constant.MakeInt64(int64(q.ECANCELED))},
				"ECASECLASH":      {Typ: reflect.TypeOf(q.ECASECLASH), Value: constant.MakeInt64(int64(q.ECASECLASH))},
				"ECHILD":          {Typ: reflect.TypeOf(q.ECHILD), Value: constant.MakeInt64(int64(q.ECHILD))},
				"ECHRNG":          {Typ: reflect.TypeOf(q.ECHRNG), Value: constant.MakeInt64(int64(q.ECHRNG))},
				"ECOMM":           {Typ: reflect.TypeOf(q.ECOMM), Value: constant.MakeInt64(int64(q.ECOMM))},
				"ECONNABORTED":    {Typ: reflect.TypeOf(q.ECONNABORTED), Value: constant.MakeInt64(int64(q.ECONNABORTED))},
				"ECONNREFUSED":    {Typ: reflect.TypeOf(q.ECONNREFUSED), Value: constant.MakeInt64(int64(q.ECONNREFUSED))},
				"ECONNRESET":      {Typ: reflect.TypeOf(q.ECONNRESET), Value: constant.MakeInt64(int64(q.ECONNRESET))},
				"EDEADLK":         {Typ: reflect.TypeOf(q.EDEADLK), Value: constant.MakeInt64(int64(q.EDEADLK))},
				"EDEADLOCK":       {Typ: reflect.TypeOf(q.EDEADLOCK), Value: constant.MakeInt64(int64(q.EDEADLOCK))},
				"EDESTADDRREQ":    {Typ: reflect.TypeOf(q.EDESTADDRREQ), Value: constant.MakeInt64(int64(q.EDESTADDRREQ))},
				"EDOM":            {Typ: reflect.TypeOf(q.EDOM), Value: constant.MakeInt64(int64(q.EDOM))},
				"EDOTDOT":         {Typ: reflect.TypeOf(q.EDOTDOT), Value: constant.MakeInt64(int64(q.EDOTDOT))},
				"EDQUOT":          {Typ: reflect.TypeOf(q.EDQUOT), Value: constant.MakeInt64(int64(q.EDQUOT))},
				"EEXIST":          {Typ: reflect.TypeOf(q.EEXIST), Value: constant.MakeInt64(int64(q.EEXIST))},
				"EFAULT":          {Typ: reflect.TypeOf(q.EFAULT), Value: constant.MakeInt64(int64(q.EFAULT))},
				"EFBIG":           {Typ: reflect.TypeOf(q.EFBIG), Value: constant.MakeInt64(int64(q.EFBIG))},
				"EFTYPE":          {Typ: reflect.TypeOf(q.EFTYPE), Value: constant.MakeInt64(int64(q.EFTYPE))},
				"EHOSTDOWN":       {Typ: reflect.TypeOf(q.EHOSTDOWN), Value: constant.MakeInt64(int64(q.EHOSTDOWN))},
				"EHOSTUNREACH":    {Typ: reflect.TypeOf(q.EHOSTUNREACH), Value: constant.MakeInt64(int64(q.EHOSTUNREACH))},
				"EIDRM":           {Typ: reflect.TypeOf(q.EIDRM), Value: constant.MakeInt64(int64(q.EIDRM))},
				"EILSEQ":          {Typ: reflect.TypeOf(q.EILSEQ), Value: constant.MakeInt64(int64(q.EILSEQ))},
				"EINPROGRESS":     {Typ: reflect.TypeOf(q.EINPROGRESS), Value: constant.MakeInt64(int64(q.EINPROGRESS))},
				"EINTR":           {Typ: reflect.TypeOf(q.EINTR), Value: constant.MakeInt64(int64(q.EINTR))},
				"EINVAL":          {Typ: reflect.TypeOf(q.EINVAL), Value: constant.MakeInt64(int64(q.EINVAL))},
				"EIO":             {Typ: reflect.TypeOf(q.EIO), Value: constant.MakeInt64(int64(q.EIO))},
				"EISCONN":         {Typ: reflect.TypeOf(q.EISCONN), Value: constant.MakeInt64(int64(q.EISCONN))},
				"EISDIR":          {Typ: reflect.TypeOf(q.EISDIR), Value: constant.MakeInt64(int64(q.EISDIR))},
				"EL2HLT":          {Typ: reflect.TypeOf(q.EL2HLT), Value: constant.MakeInt64(int64(q.EL2HLT))},
				"EL2NSYNC":        {Typ: reflect.TypeOf(q.EL2NSYNC), Value: constant.MakeInt64(int64(q.EL2NSYNC))},
				"EL3HLT":          {Typ: reflect.TypeOf(q.EL3HLT), Value: constant.MakeInt64(int64(q.EL3HLT))},
				"EL3RST":          {Typ: reflect.TypeOf(q.EL3RST), Value: constant.MakeInt64(int64(q.EL3RST))},
				"ELBIN":           {Typ: reflect.TypeOf(q.ELBIN), Value: constant.MakeInt64(int64(q.ELBIN))},
				"ELIBACC":         {Typ: reflect.TypeOf(q.ELIBACC), Value: constant.MakeInt64(int64(q.ELIBACC))},
				"ELIBBAD":         {Typ: reflect.TypeOf(q.ELIBBAD), Value: constant.MakeInt64(int64(q.ELIBBAD))},
				"ELIBEXEC":        {Typ: reflect.TypeOf(q.ELIBEXEC), Value: constant.MakeInt64(int64(q.ELIBEXEC))},
				"ELIBMAX":         {Typ: reflect.TypeOf(q.ELIBMAX), Value: constant.MakeInt64(int64(q.ELIBMAX))},
				"ELIBSCN":         {Typ: reflect.TypeOf(q.ELIBSCN), Value: constant.MakeInt64(int64(q.ELIBSCN))},
				"ELNRNG":          {Typ: reflect.TypeOf(q.ELNRNG), Value: constant.MakeInt64(int64(q.ELNRNG))},
				"ELOOP":           {Typ: reflect.TypeOf(q.ELOOP), Value: constant.MakeInt64(int64(q.ELOOP))},
				"EMFILE":          {Typ: reflect.TypeOf(q.EMFILE), Value: constant.MakeInt64(int64(q.EMFILE))},
				"EMLINK":          {Typ: reflect.TypeOf(q.EMLINK), Value: constant.MakeInt64(int64(q.EMLINK))},
				"EMSGSIZE":        {Typ: reflect.TypeOf(q.EMSGSIZE), Value: constant.MakeInt64(int64(q.EMSGSIZE))},
				"EMULTIHOP":       {Typ: reflect.TypeOf(q.EMULTIHOP), Value: constant.MakeInt64(int64(q.EMULTIHOP))},
				"ENAMETOOLONG":    {Typ: reflect.TypeOf(q.ENAMETOOLONG), Value: constant.MakeInt64(int64(q.ENAMETOOLONG))},
				"ENETDOWN":        {Typ: reflect.TypeOf(q.ENETDOWN), Value: constant.MakeInt64(int64(q.ENETDOWN))},
				"ENETRESET":       {Typ: reflect.TypeOf(q.ENETRESET), Value: constant.MakeInt64(int64(q.ENETRESET))},
				"ENETUNREACH":     {Typ: reflect.TypeOf(q.ENETUNREACH), Value: constant.MakeInt64(int64(q.ENETUNREACH))},
				"ENFILE":          {Typ: reflect.TypeOf(q.ENFILE), Value: constant.MakeInt64(int64(q.ENFILE))},
				"ENMFILE":         {Typ: reflect.TypeOf(q.ENMFILE), Value: constant.MakeInt64(int64(q.ENMFILE))},
				"ENOANO":          {Typ: reflect.TypeOf(q.ENOANO), Value: constant.MakeInt64(int64(q.ENOANO))},
				"ENOBUFS":         {Typ: reflect.TypeOf(q.ENOBUFS), Value: constant.MakeInt64(int64(q.ENOBUFS))},
				"ENOCSI":          {Typ: reflect.TypeOf(q.ENOCSI), Value: constant.MakeInt64(int64(q.ENOCSI))},
				"ENODATA":         {Typ: reflect.TypeOf(q.ENODATA), Value: constant.MakeInt64(int64(q.ENODATA))},
				"ENODEV":          {Typ: reflect.TypeOf(q.ENODEV), Value: constant.MakeInt64(int64(q.ENODEV))},
				"ENOENT":          {Typ: reflect.TypeOf(q.ENOENT), Value: constant.MakeInt64(int64(q.ENOENT))},
				"ENOEXEC":         {Typ: reflect.TypeOf(q.ENOEXEC), Value: constant.MakeInt64(int64(q.ENOEXEC))},
				"ENOLCK":          {Typ: reflect.TypeOf(q.ENOLCK), Value: constant.MakeInt64(int64(q.ENOLCK))},
				"ENOLINK":         {Typ: reflect.TypeOf(q.ENOLINK), Value: constant.MakeInt64(int64(q.ENOLINK))},
				"ENOMEDIUM":       {Typ: reflect.TypeOf(q.ENOMEDIUM), Value: constant.MakeInt64(int64(q.ENOMEDIUM))},
				"ENOMEM":          {Typ: reflect.TypeOf(q.ENOMEM), Value: constant.MakeInt64(int64(q.ENOMEM))},
				"ENOMSG":          {Typ: reflect.TypeOf(q.ENOMSG), Value: constant.MakeInt64(int64(q.ENOMSG))},
				"ENONET":          {Typ: reflect.TypeOf(q.ENONET), Value: constant.MakeInt64(int64(q.ENONET))},
				"ENOPKG":          {Typ: reflect.TypeOf(q.ENOPKG), Value: constant.MakeInt64(int64(q.ENOPKG))},
				"ENOPROTOOPT":     {Typ: reflect.TypeOf(q.ENOPROTOOPT), Value: constant.MakeInt64(int64(q.ENOPROTOOPT))},
				"ENOSHARE":        {Typ: reflect.TypeOf(q.ENOSHARE), Value: constant.MakeInt64(int64(q.ENOSHARE))},
				"ENOSPC":          {Typ: reflect.TypeOf(q.ENOSPC), Value: constant.MakeInt64(int64(q.ENOSPC))},
				"ENOSR":           {Typ: reflect.TypeOf(q.ENOSR), Value: constant.MakeInt64(int64(q.ENOSR))},
				"ENOSTR":          {Typ: reflect.TypeOf(q.ENOSTR), Value: constant.MakeInt64(int64(q.ENOSTR))},
				"ENOSYS":          {Typ: reflect.TypeOf(q.ENOSYS), Value: constant.MakeInt64(int64(q.ENOSYS))},
				"ENOTCONN":        {Typ: reflect.TypeOf(q.ENOTCONN), Value: constant.MakeInt64(int64(q.ENOTCONN))},
				"ENOTDIR":         {Typ: reflect.TypeOf(q.ENOTDIR), Value: constant.MakeInt64(int64(q.ENOTDIR))},
				"ENOTEMPTY":       {Typ: reflect.TypeOf(q.ENOTEMPTY), Value: constant.MakeInt64(int64(q.ENOTEMPTY))},
				"ENOTSOCK":        {Typ: reflect.TypeOf(q.ENOTSOCK), Value: constant.MakeInt64(int64(q.ENOTSOCK))},
				"ENOTSUP":         {Typ: reflect.TypeOf(q.ENOTSUP), Value: constant.MakeInt64(int64(q.ENOTSUP))},
				"ENOTTY":          {Typ: reflect.TypeOf(q.ENOTTY), Value: constant.MakeInt64(int64(q.ENOTTY))},
				"ENOTUNIQ":        {Typ: reflect.TypeOf(q.ENOTUNIQ), Value: constant.MakeInt64(int64(q.ENOTUNIQ))},
				"ENXIO":           {Typ: reflect.TypeOf(q.ENXIO), Value: constant.MakeInt64(int64(q.ENXIO))},
				"EOPNOTSUPP":      {Typ: reflect.TypeOf(q.EOPNOTSUPP), Value: constant.MakeInt64(int64(q.EOPNOTSUPP))},
				"EOVERFLOW":       {Typ: reflect.TypeOf(q.EOVERFLOW), Value: constant.MakeInt64(int64(q.EOVERFLOW))},
				"EPERM":           {Typ: reflect.TypeOf(q.EPERM), Value: constant.MakeInt64(int64(q.EPERM))},
				"EPFNOSUPPORT":    {Typ: reflect.TypeOf(q.EPFNOSUPPORT), Value: constant.MakeInt64(int64(q.EPFNOSUPPORT))},
				"EPIPE":           {Typ: reflect.TypeOf(q.EPIPE), Value: constant.MakeInt64(int64(q.EPIPE))},
				"EPROCLIM":        {Typ: reflect.TypeOf(q.EPROCLIM), Value: constant.MakeInt64(int64(q.EPROCLIM))},
				"EPROTO":          {Typ: reflect.TypeOf(q.EPROTO), Value: constant.MakeInt64(int64(q.EPROTO))},
				"EPROTONOSUPPORT": {Typ: reflect.TypeOf(q.EPROTONOSUPPORT), Value: constant.MakeInt64(int64(q.EPROTONOSUPPORT))},
				"EPROTOTYPE":      {Typ: reflect.TypeOf(q.EPROTOTYPE), Value: constant.MakeInt64(int64(q.EPROTOTYPE))},
				"ERANGE":          {Typ: reflect.TypeOf(q.ERANGE), Value: constant.MakeInt64(int64(q.ERANGE))},
				"EREMCHG":         {Typ: reflect.TypeOf(q.EREMCHG), Value: constant.MakeInt64(int64(q.EREMCHG))},
				"EREMOTE":         {Typ: reflect.TypeOf(q.EREMOTE), Value: constant.MakeInt64(int64(q.EREMOTE))},
				"EROFS":           {Typ: reflect.TypeOf(q.EROFS), Value: constant.MakeInt64(int64(q.EROFS))},
				"ESHUTDOWN":       {Typ: reflect.TypeOf(q.ESHUTDOWN), Value: constant.MakeInt64(int64(q.ESHUTDOWN))},
				"ESOCKTNOSUPPORT": {Typ: reflect.TypeOf(q.ESOCKTNOSUPPORT), Value: constant.MakeInt64(int64(q.ESOCKTNOSUPPORT))},
				"ESPIPE":          {Typ: reflect.TypeOf(q.ESPIPE), Value: constant.MakeInt64(int64(q.ESPIPE))},
				"ESRCH":           {Typ: reflect.TypeOf(q.ESRCH), Value: constant.MakeInt64(int64(q.ESRCH))},
				"ESRMNT":          {Typ: reflect.TypeOf(q.ESRMNT), Value: constant.MakeInt64(int64(q.ESRMNT))},
				"ESTALE":          {Typ: reflect.TypeOf(q.ESTALE), Value: constant.MakeInt64(int64(q.ESTALE))},
				"ETIME":           {Typ: reflect.TypeOf(q.ETIME), Value: constant.MakeInt64(int64(q.ETIME))},
				"ETIMEDOUT":       {Typ: reflect.TypeOf(q.ETIMEDOUT), Value: constant.MakeInt64(int64(q.ETIMEDOUT))},
				"ETOOMANYREFS":    {Typ: reflect.TypeOf(q.ETOOMANYREFS), Value: constant.MakeInt64(int64(q.ETOOMANYREFS))},
				"EUNATCH":         {Typ: reflect.TypeOf(q.EUNATCH), Value: constant.MakeInt64(int64(q.EUNATCH))},
				"EUSERS":          {Typ: reflect.TypeOf(q.EUSERS), Value: constant.MakeInt64(int64(q.EUSERS))},
				"EWOULDBLOCK":     {Typ: reflect.TypeOf(q.EWOULDBLOCK), Value: constant.MakeInt64(int64(q.EWOULDBLOCK))},
				"EXDEV":           {Typ: reflect.TypeOf(q.EXDEV), Value: constant.MakeInt64(int64(q.EXDEV))},
				"EXFULL":          {Typ: reflect.TypeOf(q.EXFULL), Value: constant.MakeInt64(int64(q.EXFULL))},
				"SIGCHLD":         {Typ: reflect.TypeOf(q.SIGCHLD), Value: constant.MakeInt64(int64(q.SIGCHLD))},
				"SIGINT":          {Typ: reflect.TypeOf(q.SIGINT), Value: constant.MakeInt64(int64(q.SIGINT))},
				"SIGKILL":         {Typ: reflect.TypeOf(q.SIGKILL), Value: constant.MakeInt64(int64(q.SIGKILL))},
				"SIGQUIT":         {Typ: reflect.TypeOf(q.SIGQUIT), Value: constant.MakeInt64(int64(q.SIGQUIT))},
				"SIGTERM":         {Typ: reflect.TypeOf(q.SIGTERM), Value: constant.MakeInt64(int64(q.SIGTERM))},
				"SIGTRAP":         {Typ: reflect.TypeOf(q.SIGTRAP), Value: constant.MakeInt64(int64(q.SIGTRAP))},
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"AF_INET":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_INET))},
				"AF_INET6":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_INET6))},
				"AF_UNIX":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_UNIX))},
				"AF_UNSPEC":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_UNSPEC))},
				"F_CNVT":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_CNVT))},
				"F_DUPFD":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_DUPFD))},
				"F_DUPFD_CLOEXEC": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_DUPFD_CLOEXEC))},
				"F_GETFD":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETFD))},
				"F_GETFL":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETFL))},
				"F_GETLK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETLK))},
				"F_GETOWN":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETOWN))},
				"F_RDLCK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RDLCK))},
				"F_RGETLK":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RGETLK))},
				"F_RSETLK":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RSETLK))},
				"F_RSETLKW":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RSETLKW))},
				"F_SETFD":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETFD))},
				"F_SETFL":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETFL))},
				"F_SETLK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETLK))},
				"F_SETLKW":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETLKW))},
				"F_SETOWN":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETOWN))},
				"F_UNLCK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_UNLCK))},
				"F_UNLKSYS":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_UNLKSYS))},
				"F_WRLCK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_WRLCK))},
				"IPPROTO_IP":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IP))},
				"IPPROTO_IPV4":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IPV4))},
				"IPPROTO_IPV6":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IPV6))},
				"IPPROTO_TCP":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_TCP))},
				"IPPROTO_UDP":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_UDP))},
				"IPV6_V6ONLY":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPV6_V6ONLY))},
				"ImplementsGetwd": {Typ: "untyped bool", Value: constant.MakeBool(bool(q.ImplementsGetwd))},
				"O_APPEND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_APPEND))},
				"O_CLOEXEC":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CLOEXEC))},
				"O_CREAT":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CREAT))},
				"O_CREATE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CREATE))},
				"O_DIRECTORY":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_DIRECTORY))},
				"O_EXCL":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_EXCL))},
				"O_RDONLY":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDONLY))},
				"O_RDWR":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDWR))},
				"O_SYNC":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_SYNC))},
				"O_TRUNC":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_TRUNC))},
				"O_WRONLY":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_WRONLY))},
				"PathMax":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.PathMax))},
				"SOCK_DGRAM":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_DGRAM))},
				"SOCK_RAW":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_RAW))},
				"SOCK_SEQPACKET":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_SEQPACKET))},
				"SOCK_STREAM":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_STREAM))},
				"SOMAXCONN":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOMAXCONN))},
				"SO_ERROR":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SO_ERROR))},
				"SYS_FCNTL":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FCNTL))},
				"S_IEXEC":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IEXEC))},
				"S_IFBLK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFBLK))},
				"S_IFBOUNDSOCK":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFBOUNDSOCK))},
				"S_IFCHR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFCHR))},
				"S_IFCOND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFCOND))},
				"S_IFDIR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFDIR))},
				"S_IFDSOCK":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFDSOCK))},
				"S_IFIFO":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFIFO))},
				"S_IFLNK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFLNK))},
				"S_IFMT":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFMT))},
				"S_IFMUTEX":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFMUTEX))},
				"S_IFREG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFREG))},
				"S_IFSEMA":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSEMA))},
				"S_IFSHM":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSHM))},
				"S_IFSHM_SYSV":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSHM_SYSV))},
				"S_IFSOCK":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSOCK))},
				"S_IFSOCKADDR":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSOCKADDR))},
				"S_IREAD":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IREAD))},
				"S_IRGRP":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRGRP))},
				"S_IROTH":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IROTH))},
				"S_IRUSR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRUSR))},
				"S_IRWXG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXG))},
				"S_IRWXO":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXO))},
				"S_IRWXU":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXU))},
				"S_ISGID":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISGID))},
				"S_ISUID":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISUID))},
				"S_ISVTX":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISVTX))},
				"S_IWGRP":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWGRP))},
				"S_IWOTH":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWOTH))},
				"S_IWRITE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWRITE))},
				"S_IWUSR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWUSR))},
				"S_IXGRP":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXGRP))},
				"S_IXOTH":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXOTH))},
				"S_IXUSR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXUSR))},
				"S_UNSUP":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_UNSUP))},
				"Stderr":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stderr))},
				"Stdin":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stdin))},
				"Stdout":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stdout))},
			},
		}
	})
}
