// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.24 && !go1.25
// +build go1.24,!go1.25

package syscall

import (
	q "syscall"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("syscall", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "syscall",
			Path: "syscall",
			Deps: map[string]string{
				"errors":               "errors",
				"internal/bytealg":     "bytealg",
				"internal/byteorder":   "byteorder",
				"internal/goarch":      "goarch",
				"internal/itoa":        "itoa",
				"internal/oserror":     "oserror",
				"internal/stringslite": "stringslite",
				"runtime":              "runtime",
				"structs":              "structs",
				"sync":                 "sync",
				"unsafe":               "unsafe",
			},
			Interfaces: map[string]reflect.Type{
				"Conn":     reflect.TypeOf((*q.Conn)(nil)).Elem(),
				"RawConn":  reflect.TypeOf((*q.RawConn)(nil)).Elem(),
				"Sockaddr": reflect.TypeOf((*q.Sockaddr)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Dirent":        reflect.TypeOf((*q.Dirent)(nil)).Elem(),
				"Errno":         reflect.TypeOf((*q.Errno)(nil)).Elem(),
				"ProcAttr":      reflect.TypeOf((*q.ProcAttr)(nil)).Elem(),
				"Rlimit":        reflect.TypeOf((*q.Rlimit)(nil)).Elem(),
				"Rusage":        reflect.TypeOf((*q.Rusage)(nil)).Elem(),
				"Signal":        reflect.TypeOf((*q.Signal)(nil)).Elem(),
				"SockaddrInet4": reflect.TypeOf((*q.SockaddrInet4)(nil)).Elem(),
				"SockaddrInet6": reflect.TypeOf((*q.SockaddrInet6)(nil)).Elem(),
				"SockaddrUnix":  reflect.TypeOf((*q.SockaddrUnix)(nil)).Elem(),
				"Stat_t":        reflect.TypeOf((*q.Stat_t)(nil)).Elem(),
				"SysProcAttr":   reflect.TypeOf((*q.SysProcAttr)(nil)).Elem(),
				"Timespec":      reflect.TypeOf((*q.Timespec)(nil)).Elem(),
				"Timeval":       reflect.TypeOf((*q.Timeval)(nil)).Elem(),
				"WaitStatus":    reflect.TypeOf((*q.WaitStatus)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{
				"Dircookie": reflect.TypeOf((*q.Dircookie)(nil)).Elem(),
				"Filetype":  reflect.TypeOf((*q.Filetype)(nil)).Elem(),
			},
			Vars: map[string]interface{}{},
			Funcs: map[string]interface{}{
				"Accept":              q.Accept,
				"Bind":                q.Bind,
				"BytePtrFromString":   q.BytePtrFromString,
				"ByteSliceFromString": q.ByteSliceFromString,
				"Chdir":               q.Chdir,
				"Chmod":               q.Chmod,
				"Chown":               q.Chown,
				"Clearenv":            q.Clearenv,
				"Close":               q.Close,
				"CloseOnExec":         q.CloseOnExec,
				"Connect":             q.Connect,
				"Dup":                 q.Dup,
				"Dup2":                q.Dup2,
				"Environ":             q.Environ,
				"Exit":                q.Exit,
				"Fchmod":              q.Fchmod,
				"Fchown":              q.Fchown,
				"Fstat":               q.Fstat,
				"Fsync":               q.Fsync,
				"Ftruncate":           q.Ftruncate,
				"Getegid":             q.Getegid,
				"Getenv":              q.Getenv,
				"Geteuid":             q.Geteuid,
				"Getgid":              q.Getgid,
				"Getgroups":           q.Getgroups,
				"Getpagesize":         q.Getpagesize,
				"Getpid":              q.Getpid,
				"Getppid":             q.Getppid,
				"Getrlimit":           q.Getrlimit,
				"GetsockoptInt":       q.GetsockoptInt,
				"Gettimeofday":        q.Gettimeofday,
				"Getuid":              q.Getuid,
				"Getwd":               q.Getwd,
				"Kill":                q.Kill,
				"Lchown":              q.Lchown,
				"Link":                q.Link,
				"Listen":              q.Listen,
				"Lstat":               q.Lstat,
				"Mkdir":               q.Mkdir,
				"NsecToTimespec":      q.NsecToTimespec,
				"NsecToTimeval":       q.NsecToTimeval,
				"Open":                q.Open,
				"Openat":              q.Openat,
				"ParseDirent":         q.ParseDirent,
				"Pipe":                q.Pipe,
				"Pread":               q.Pread,
				"ProcExit":            q.ProcExit,
				"Pwrite":              q.Pwrite,
				"RandomGet":           q.RandomGet,
				"RawSyscall":          q.RawSyscall,
				"RawSyscall6":         q.RawSyscall6,
				"Read":                q.Read,
				"ReadDir":             q.ReadDir,
				"Readlink":            q.Readlink,
				"Recvfrom":            q.Recvfrom,
				"Recvmsg":             q.Recvmsg,
				"Rename":              q.Rename,
				"Rmdir":               q.Rmdir,
				"Seek":                q.Seek,
				"Sendfile":            q.Sendfile,
				"SendmsgN":            q.SendmsgN,
				"Sendto":              q.Sendto,
				"SetNonblock":         q.SetNonblock,
				"SetReadDeadline":     q.SetReadDeadline,
				"SetWriteDeadline":    q.SetWriteDeadline,
				"Setenv":              q.Setenv,
				"SetsockoptInt":       q.SetsockoptInt,
				"Shutdown":            q.Shutdown,
				"Socket":              q.Socket,
				"StartProcess":        q.StartProcess,
				"Stat":                q.Stat,
				"StopIO":              q.StopIO,
				"StringBytePtr":       q.StringBytePtr,
				"StringByteSlice":     q.StringByteSlice,
				"Symlink":             q.Symlink,
				"Syscall":             q.Syscall,
				"Syscall6":            q.Syscall6,
				"Sysctl":              q.Sysctl,
				"TimespecToNsec":      q.TimespecToNsec,
				"TimevalToNsec":       q.TimevalToNsec,
				"Truncate":            q.Truncate,
				"Umask":               q.Umask,
				"Unlink":              q.Unlink,
				"Unsetenv":            q.Unsetenv,
				"UtimesNano":          q.UtimesNano,
				"Wait4":               q.Wait4,
				"Write":               q.Write,
			},
			TypedConsts: map[string]interface{}{
				"E2BIG":                     q.E2BIG,
				"EACCES":                    q.EACCES,
				"EADDRINUSE":                q.EADDRINUSE,
				"EADDRNOTAVAIL":             q.EADDRNOTAVAIL,
				"EAFNOSUPPORT":              q.EAFNOSUPPORT,
				"EAGAIN":                    q.EAGAIN,
				"EALREADY":                  q.EALREADY,
				"EBADF":                     q.EBADF,
				"EBADFD":                    q.EBADFD,
				"EBADMSG":                   q.EBADMSG,
				"EBUSY":                     q.EBUSY,
				"ECANCELED":                 q.ECANCELED,
				"ECHILD":                    q.ECHILD,
				"ECONNABORTED":              q.ECONNABORTED,
				"ECONNREFUSED":              q.ECONNREFUSED,
				"ECONNRESET":                q.ECONNRESET,
				"EDEADLK":                   q.EDEADLK,
				"EDESTADDRREQ":              q.EDESTADDRREQ,
				"EDOM":                      q.EDOM,
				"EDQUOT":                    q.EDQUOT,
				"EEXIST":                    q.EEXIST,
				"EFAULT":                    q.EFAULT,
				"EFBIG":                     q.EFBIG,
				"EHOSTUNREACH":              q.EHOSTUNREACH,
				"EIDRM":                     q.EIDRM,
				"EILSEQ":                    q.EILSEQ,
				"EINPROGRESS":               q.EINPROGRESS,
				"EINTR":                     q.EINTR,
				"EINVAL":                    q.EINVAL,
				"EIO":                       q.EIO,
				"EISCONN":                   q.EISCONN,
				"EISDIR":                    q.EISDIR,
				"ELOOP":                     q.ELOOP,
				"EMFILE":                    q.EMFILE,
				"EMLINK":                    q.EMLINK,
				"EMSGSIZE":                  q.EMSGSIZE,
				"EMULTIHOP":                 q.EMULTIHOP,
				"ENAMETOOLONG":              q.ENAMETOOLONG,
				"ENETDOWN":                  q.ENETDOWN,
				"ENETRESET":                 q.ENETRESET,
				"ENETUNREACH":               q.ENETUNREACH,
				"ENFILE":                    q.ENFILE,
				"ENOBUFS":                   q.ENOBUFS,
				"ENODEV":                    q.ENODEV,
				"ENOENT":                    q.ENOENT,
				"ENOEXEC":                   q.ENOEXEC,
				"ENOLCK":                    q.ENOLCK,
				"ENOLINK":                   q.ENOLINK,
				"ENOMEM":                    q.ENOMEM,
				"ENOMSG":                    q.ENOMSG,
				"ENOPROTOOPT":               q.ENOPROTOOPT,
				"ENOSPC":                    q.ENOSPC,
				"ENOSYS":                    q.ENOSYS,
				"ENOTCAPABLE":               q.ENOTCAPABLE,
				"ENOTCONN":                  q.ENOTCONN,
				"ENOTDIR":                   q.ENOTDIR,
				"ENOTEMPTY":                 q.ENOTEMPTY,
				"ENOTRECOVERABLE":           q.ENOTRECOVERABLE,
				"ENOTSOCK":                  q.ENOTSOCK,
				"ENOTSUP":                   q.ENOTSUP,
				"ENOTTY":                    q.ENOTTY,
				"ENXIO":                     q.ENXIO,
				"EOPNOTSUPP":                q.EOPNOTSUPP,
				"EOVERFLOW":                 q.EOVERFLOW,
				"EOWNERDEAD":                q.EOWNERDEAD,
				"EPERM":                     q.EPERM,
				"EPIPE":                     q.EPIPE,
				"EPROTO":                    q.EPROTO,
				"EPROTONOSUPPORT":           q.EPROTONOSUPPORT,
				"EPROTOTYPE":                q.EPROTOTYPE,
				"ERANGE":                    q.ERANGE,
				"EROFS":                     q.EROFS,
				"ESPIPE":                    q.ESPIPE,
				"ESRCH":                     q.ESRCH,
				"ESTALE":                    q.ESTALE,
				"ETIMEDOUT":                 q.ETIMEDOUT,
				"ETXTBSY":                   q.ETXTBSY,
				"EXDEV":                     q.EXDEV,
				"FILETYPE_BLOCK_DEVICE":     q.FILETYPE_BLOCK_DEVICE,
				"FILETYPE_CHARACTER_DEVICE": q.FILETYPE_CHARACTER_DEVICE,
				"FILETYPE_DIRECTORY":        q.FILETYPE_DIRECTORY,
				"FILETYPE_REGULAR_FILE":     q.FILETYPE_REGULAR_FILE,
				"FILETYPE_SOCKET_DGRAM":     q.FILETYPE_SOCKET_DGRAM,
				"FILETYPE_SOCKET_STREAM":    q.FILETYPE_SOCKET_STREAM,
				"FILETYPE_SYMBOLIC_LINK":    q.FILETYPE_SYMBOLIC_LINK,
				"FILETYPE_UNKNOWN":          q.FILETYPE_UNKNOWN,
				"SIGABRT":                   q.SIGABRT,
				"SIGALRM":                   q.SIGALRM,
				"SIGBUS":                    q.SIGBUS,
				"SIGCHLD":                   q.SIGCHLD,
				"SIGCONT":                   q.SIGCONT,
				"SIGFPE":                    q.SIGFPE,
				"SIGHUP":                    q.SIGHUP,
				"SIGILL":                    q.SIGILL,
				"SIGINT":                    q.SIGINT,
				"SIGKILL":                   q.SIGKILL,
				"SIGNONE":                   q.SIGNONE,
				"SIGPIPE":                   q.SIGPIPE,
				"SIGPOLL":                   q.SIGPOLL,
				"SIGPROF":                   q.SIGPROF,
				"SIGPWR":                    q.SIGPWR,
				"SIGQUIT":                   q.SIGQUIT,
				"SIGSEGV":                   q.SIGSEGV,
				"SIGSTOP":                   q.SIGSTOP,
				"SIGSYS":                    q.SIGSYS,
				"SIGTERM":                   q.SIGTERM,
				"SIGTRAP":                   q.SIGTRAP,
				"SIGTSTP":                   q.SIGTSTP,
				"SIGTTIN":                   q.SIGTTIN,
				"SIGTTOU":                   q.SIGTTOU,
				"SIGURG":                    q.SIGURG,
				"SIGUSR1":                   q.SIGUSR1,
				"SIGUSR2":                   q.SIGUSR2,
				"SIGVTARLM":                 q.SIGVTARLM,
				"SIGWINCH":                  q.SIGWINCH,
				"SIGXCPU":                   q.SIGXCPU,
				"SIGXFSZ":                   q.SIGXFSZ,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"AF_INET":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_INET))},
				"AF_INET6":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_INET6))},
				"AF_UNIX":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_UNIX))},
				"AF_UNSPEC":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_UNSPEC))},
				"FDFLAG_APPEND":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FDFLAG_APPEND))},
				"FDFLAG_DSYNC":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FDFLAG_DSYNC))},
				"FDFLAG_NONBLOCK":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FDFLAG_NONBLOCK))},
				"FDFLAG_RSYNC":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FDFLAG_RSYNC))},
				"FDFLAG_SYNC":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FDFLAG_SYNC))},
				"FILESTAT_SET_ATIM":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FILESTAT_SET_ATIM))},
				"FILESTAT_SET_ATIM_NOW":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FILESTAT_SET_ATIM_NOW))},
				"FILESTAT_SET_MTIM":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FILESTAT_SET_MTIM))},
				"FILESTAT_SET_MTIM_NOW":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.FILESTAT_SET_MTIM_NOW))},
				"F_CNVT":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_CNVT))},
				"F_DUPFD":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_DUPFD))},
				"F_DUPFD_CLOEXEC":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_DUPFD_CLOEXEC))},
				"F_GETFD":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETFD))},
				"F_GETFL":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETFL))},
				"F_GETLK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETLK))},
				"F_GETOWN":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETOWN))},
				"F_RDLCK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RDLCK))},
				"F_RGETLK":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RGETLK))},
				"F_RSETLK":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RSETLK))},
				"F_RSETLKW":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RSETLKW))},
				"F_SETFD":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETFD))},
				"F_SETFL":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETFL))},
				"F_SETLK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETLK))},
				"F_SETLKW":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETLKW))},
				"F_SETOWN":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETOWN))},
				"F_UNLCK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_UNLCK))},
				"F_UNLKSYS":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_UNLKSYS))},
				"F_WRLCK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_WRLCK))},
				"IPPROTO_IP":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IP))},
				"IPPROTO_IPV4":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IPV4))},
				"IPPROTO_IPV6":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IPV6))},
				"IPPROTO_TCP":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_TCP))},
				"IPPROTO_UDP":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_UDP))},
				"IPV6_V6ONLY":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPV6_V6ONLY))},
				"ImplementsGetwd":               {Typ: "untyped bool", Value: constant.MakeBool(bool(q.ImplementsGetwd))},
				"LOOKUP_SYMLINK_FOLLOW":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.LOOKUP_SYMLINK_FOLLOW))},
				"OFLAG_CREATE":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.OFLAG_CREATE))},
				"OFLAG_DIRECTORY":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.OFLAG_DIRECTORY))},
				"OFLAG_EXCL":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.OFLAG_EXCL))},
				"OFLAG_TRUNC":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.OFLAG_TRUNC))},
				"O_APPEND":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_APPEND))},
				"O_CLOEXEC":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CLOEXEC))},
				"O_CREAT":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CREAT))},
				"O_CREATE":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CREATE))},
				"O_DIRECTORY":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_DIRECTORY))},
				"O_EXCL":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_EXCL))},
				"O_NOFOLLOW":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_NOFOLLOW))},
				"O_RDONLY":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDONLY))},
				"O_RDWR":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDWR))},
				"O_SYNC":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_SYNC))},
				"O_TRUNC":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_TRUNC))},
				"O_WRONLY":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_WRONLY))},
				"RIGHT_FDSTAT_SET_FLAGS":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FDSTAT_SET_FLAGS))},
				"RIGHT_FD_ADVISE":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_ADVISE))},
				"RIGHT_FD_ALLOCATE":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_ALLOCATE))},
				"RIGHT_FD_DATASYNC":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_DATASYNC))},
				"RIGHT_FD_FILESTAT_GET":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_FILESTAT_GET))},
				"RIGHT_FD_FILESTAT_SET_SIZE":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_FILESTAT_SET_SIZE))},
				"RIGHT_FD_FILESTAT_SET_TIMES":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_FILESTAT_SET_TIMES))},
				"RIGHT_FD_READ":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_READ))},
				"RIGHT_FD_READDIR":              {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_READDIR))},
				"RIGHT_FD_SEEK":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_SEEK))},
				"RIGHT_FD_SYNC":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_SYNC))},
				"RIGHT_FD_TELL":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_TELL))},
				"RIGHT_FD_WRITE":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_FD_WRITE))},
				"RIGHT_PATH_CREATE_DIRECTORY":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_CREATE_DIRECTORY))},
				"RIGHT_PATH_CREATE_FILE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_CREATE_FILE))},
				"RIGHT_PATH_FILESTAT_GET":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_FILESTAT_GET))},
				"RIGHT_PATH_FILESTAT_SET_SIZE":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_FILESTAT_SET_SIZE))},
				"RIGHT_PATH_FILESTAT_SET_TIMES": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_FILESTAT_SET_TIMES))},
				"RIGHT_PATH_LINK_SOURCE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_LINK_SOURCE))},
				"RIGHT_PATH_LINK_TARGET":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_LINK_TARGET))},
				"RIGHT_PATH_OPEN":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_OPEN))},
				"RIGHT_PATH_READLINK":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_READLINK))},
				"RIGHT_PATH_REMOVE_DIRECTORY":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_REMOVE_DIRECTORY))},
				"RIGHT_PATH_RENAME_SOURCE":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_RENAME_SOURCE))},
				"RIGHT_PATH_RENAME_TARGET":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_RENAME_TARGET))},
				"RIGHT_PATH_SYMLINK":            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_SYMLINK))},
				"RIGHT_PATH_UNLINK_FILE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_PATH_UNLINK_FILE))},
				"RIGHT_POLL_FD_READWRITE":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_POLL_FD_READWRITE))},
				"RIGHT_SOCK_ACCEPT":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_SOCK_ACCEPT))},
				"RIGHT_SOCK_SHUTDOWN":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RIGHT_SOCK_SHUTDOWN))},
				"RLIMIT_NOFILE":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RLIMIT_NOFILE))},
				"SHUT_RD":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SHUT_RD))},
				"SHUT_RDWR":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SHUT_RDWR))},
				"SHUT_WR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SHUT_WR))},
				"SOCK_DGRAM":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_DGRAM))},
				"SOCK_RAW":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_RAW))},
				"SOCK_SEQPACKET":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_SEQPACKET))},
				"SOCK_STREAM":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_STREAM))},
				"SOMAXCONN":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOMAXCONN))},
				"SO_ERROR":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SO_ERROR))},
				"SYS_FCNTL":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FCNTL))},
				"S_IEXEC":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IEXEC))},
				"S_IFBLK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFBLK))},
				"S_IFBOUNDSOCK":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFBOUNDSOCK))},
				"S_IFCHR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFCHR))},
				"S_IFCOND":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFCOND))},
				"S_IFDIR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFDIR))},
				"S_IFDSOCK":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFDSOCK))},
				"S_IFIFO":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFIFO))},
				"S_IFLNK":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFLNK))},
				"S_IFMT":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFMT))},
				"S_IFMUTEX":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFMUTEX))},
				"S_IFREG":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFREG))},
				"S_IFSEMA":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSEMA))},
				"S_IFSHM":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSHM))},
				"S_IFSHM_SYSV":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSHM_SYSV))},
				"S_IFSOCK":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSOCK))},
				"S_IFSOCKADDR":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSOCKADDR))},
				"S_IREAD":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IREAD))},
				"S_IRGRP":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRGRP))},
				"S_IROTH":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IROTH))},
				"S_IRUSR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRUSR))},
				"S_IRWXG":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXG))},
				"S_IRWXO":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXO))},
				"S_IRWXU":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXU))},
				"S_ISGID":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISGID))},
				"S_ISUID":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISUID))},
				"S_ISVTX":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISVTX))},
				"S_IWGRP":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWGRP))},
				"S_IWOTH":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWOTH))},
				"S_IWRITE":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWRITE))},
				"S_IWUSR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWUSR))},
				"S_IXGRP":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXGRP))},
				"S_IXOTH":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXOTH))},
				"S_IXUSR":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXUSR))},
				"S_UNSUP":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_UNSUP))},
				"Stderr":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stderr))},
				"Stdin":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stdin))},
				"Stdout":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stdout))},
				"WHENCE_CUR":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.WHENCE_CUR))},
				"WHENCE_END":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.WHENCE_END))},
				"WHENCE_SET":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.WHENCE_SET))},
			},
		}
	})
}
