// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.26
// +build go1.26

package syscall

import (
	q "syscall"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("syscall", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "syscall",
			Path: "syscall",
			Deps: map[string]string{
				"errors":             "errors",
				"internal/bytealg":   "bytealg",
				"internal/byteorder": "byteorder",
				"internal/oserror":   "oserror",
				"internal/strconv":   "strconv",
				"runtime":            "runtime",
				"sync":               "sync",
				"unsafe":             "unsafe",
			},
			Interfaces: map[string]reflect.Type{
				"Conn":    reflect.TypeOf((*q.Conn)(nil)).Elem(),
				"RawConn": reflect.TypeOf((*q.RawConn)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Dir":         reflect.TypeOf((*q.Dir)(nil)).Elem(),
				"ErrorString": reflect.TypeOf((*q.ErrorString)(nil)).Elem(),
				"Note":        reflect.TypeOf((*q.Note)(nil)).Elem(),
				"ProcAttr":    reflect.TypeOf((*q.ProcAttr)(nil)).Elem(),
				"Qid":         reflect.TypeOf((*q.Qid)(nil)).Elem(),
				"SysProcAttr": reflect.TypeOf((*q.SysProcAttr)(nil)).Elem(),
				"Timespec":    reflect.TypeOf((*q.Timespec)(nil)).Elem(),
				"Timeval":     reflect.TypeOf((*q.Timeval)(nil)).Elem(),
				"Waitmsg":     reflect.TypeOf((*q.Waitmsg)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]interface{}{
				"EACCES":            &q.EACCES,
				"EAFNOSUPPORT":      &q.EAFNOSUPPORT,
				"EBUSY":             &q.EBUSY,
				"EEXIST":            &q.EEXIST,
				"EINTR":             &q.EINTR,
				"EINVAL":            &q.EINVAL,
				"EIO":               &q.EIO,
				"EISDIR":            &q.EISDIR,
				"EMFILE":            &q.EMFILE,
				"ENAMETOOLONG":      &q.ENAMETOOLONG,
				"ENOENT":            &q.ENOENT,
				"ENOTDIR":           &q.ENOTDIR,
				"EPERM":             &q.EPERM,
				"EPLAN9":            &q.EPLAN9,
				"ESPIPE":            &q.ESPIPE,
				"ETIMEDOUT":         &q.ETIMEDOUT,
				"ErrBadName":        &q.ErrBadName,
				"ErrBadStat":        &q.ErrBadStat,
				"ErrShortStat":      &q.ErrShortStat,
				"ForkLock":          &q.ForkLock,
				"SocketDisableIPv6": &q.SocketDisableIPv6,
				"Stderr":            &q.Stderr,
				"Stdin":             &q.Stdin,
				"Stdout":            &q.Stdout,
			},
			Funcs: map[string]interface{}{
				"Await":               q.Await,
				"Bind":                q.Bind,
				"BytePtrFromString":   q.BytePtrFromString,
				"ByteSliceFromString": q.ByteSliceFromString,
				"Chdir":               q.Chdir,
				"Clearenv":            q.Clearenv,
				"Close":               q.Close,
				"Create":              q.Create,
				"Dup":                 q.Dup,
				"Environ":             q.Environ,
				"Exec":                q.Exec,
				"Exit":                q.Exit,
				"Fchdir":              q.Fchdir,
				"Fd2path":             q.Fd2path,
				"Fixwd":               q.Fixwd,
				"ForkExec":            q.ForkExec,
				"Fstat":               q.Fstat,
				"Fwstat":              q.Fwstat,
				"Getegid":             q.Getegid,
				"Getenv":              q.Getenv,
				"Geteuid":             q.Geteuid,
				"Getgid":              q.Getgid,
				"Getgroups":           q.Getgroups,
				"Getpagesize":         q.Getpagesize,
				"Getpid":              q.Getpid,
				"Getppid":             q.Getppid,
				"Gettimeofday":        q.Gettimeofday,
				"Getuid":              q.Getuid,
				"Getwd":               q.Getwd,
				"Mkdir":               q.Mkdir,
				"Mount":               q.Mount,
				"NewError":            q.NewError,
				"NsecToTimeval":       q.NsecToTimeval,
				"Open":                q.Open,
				"Pipe":                q.Pipe,
				"Pread":               q.Pread,
				"Pwrite":              q.Pwrite,
				"RawSyscall":          q.RawSyscall,
				"RawSyscall6":         q.RawSyscall6,
				"Read":                q.Read,
				"Remove":              q.Remove,
				"Seek":                q.Seek,
				"Setenv":              q.Setenv,
				"SlicePtrFromStrings": q.SlicePtrFromStrings,
				"StartProcess":        q.StartProcess,
				"Stat":                q.Stat,
				"StringBytePtr":       q.StringBytePtr,
				"StringByteSlice":     q.StringByteSlice,
				"StringSlicePtr":      q.StringSlicePtr,
				"Syscall":             q.Syscall,
				"Syscall6":            q.Syscall6,
				"UnmarshalDir":        q.UnmarshalDir,
				"Unmount":             q.Unmount,
				"Unsetenv":            q.Unsetenv,
				"WaitProcess":         q.WaitProcess,
				"Write":               q.Write,
				"Wstat":               q.Wstat,
			},
			TypedConsts: map[string]interface{}{
				"SIGABRT": q.SIGABRT,
				"SIGALRM": q.SIGALRM,
				"SIGHUP":  q.SIGHUP,
				"SIGINT":  q.SIGINT,
				"SIGKILL": q.SIGKILL,
				"SIGTERM": q.SIGTERM,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"DMAPPEND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMAPPEND))},
				"DMAUTH":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMAUTH))},
				"DMDIR":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMDIR))},
				"DMEXCL":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMEXCL))},
				"DMEXEC":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMEXEC))},
				"DMMOUNT":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMMOUNT))},
				"DMREAD":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMREAD))},
				"DMTMP":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMTMP))},
				"DMWRITE":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMWRITE))},
				"ERRMAX":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.ERRMAX))},
				"ImplementsGetwd": {Typ: "untyped bool", Value: constant.MakeBool(bool(q.ImplementsGetwd))},
				"MAFTER":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MAFTER))},
				"MBEFORE":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MBEFORE))},
				"MCACHE":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MCACHE))},
				"MCREATE":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MCREATE))},
				"MMASK":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MMASK))},
				"MORDER":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MORDER))},
				"MREPL":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MREPL))},
				"O_APPEND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_APPEND))},
				"O_ASYNC":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_ASYNC))},
				"O_CLOEXEC":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CLOEXEC))},
				"O_CREAT":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CREAT))},
				"O_EXCL":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_EXCL))},
				"O_NOCTTY":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_NOCTTY))},
				"O_NONBLOCK":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_NONBLOCK))},
				"O_RDONLY":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDONLY))},
				"O_RDWR":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDWR))},
				"O_SYNC":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_SYNC))},
				"O_TRUNC":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_TRUNC))},
				"O_WRONLY":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_WRONLY))},
				"QTAPPEND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTAPPEND))},
				"QTAUTH":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTAUTH))},
				"QTDIR":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTDIR))},
				"QTEXCL":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTEXCL))},
				"QTFILE":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTFILE))},
				"QTMOUNT":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTMOUNT))},
				"QTTMP":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTTMP))},
				"RFCENVG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFCENVG))},
				"RFCFDG":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFCFDG))},
				"RFCNAMEG":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFCNAMEG))},
				"RFENVG":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFENVG))},
				"RFFDG":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFFDG))},
				"RFMEM":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFMEM))},
				"RFNAMEG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFNAMEG))},
				"RFNOMNT":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFNOMNT))},
				"RFNOTEG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFNOTEG))},
				"RFNOWAIT":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFNOWAIT))},
				"RFPROC":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFPROC))},
				"RFREND":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFREND))},
				"STATFIXLEN":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.STATFIXLEN))},
				"STATMAX":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.STATMAX))},
				"SYS_ALARM":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_ALARM))},
				"SYS_AWAIT":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_AWAIT))},
				"SYS_BIND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_BIND))},
				"SYS_BRK_":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_BRK_))},
				"SYS_CHDIR":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_CHDIR))},
				"SYS_CLOSE":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_CLOSE))},
				"SYS_CREATE":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_CREATE))},
				"SYS_DUP":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_DUP))},
				"SYS_ERRSTR":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_ERRSTR))},
				"SYS_EXEC":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_EXEC))},
				"SYS_EXITS":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_EXITS))},
				"SYS_FAUTH":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FAUTH))},
				"SYS_FD2PATH":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FD2PATH))},
				"SYS_FSTAT":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FSTAT))},
				"SYS_FVERSION":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FVERSION))},
				"SYS_FWSTAT":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FWSTAT))},
				"SYS_MOUNT":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_MOUNT))},
				"SYS_NOTED":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_NOTED))},
				"SYS_NOTIFY":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_NOTIFY))},
				"SYS_NSEC":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_NSEC))},
				"SYS_OPEN":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_OPEN))},
				"SYS_OSEEK":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_OSEEK))},
				"SYS_PIPE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_PIPE))},
				"SYS_PREAD":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_PREAD))},
				"SYS_PWRITE":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_PWRITE))},
				"SYS_REMOVE":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_REMOVE))},
				"SYS_RENDEZVOUS":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_RENDEZVOUS))},
				"SYS_RFORK":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_RFORK))},
				"SYS_SEEK":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEEK))},
				"SYS_SEGATTACH":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEGATTACH))},
				"SYS_SEGBRK":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEGBRK))},
				"SYS_SEGDETACH":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEGDETACH))},
				"SYS_SEGFLUSH":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEGFLUSH))},
				"SYS_SEGFREE":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEGFREE))},
				"SYS_SEMACQUIRE":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEMACQUIRE))},
				"SYS_SEMRELEASE":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEMRELEASE))},
				"SYS_SLEEP":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SLEEP))},
				"SYS_STAT":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_STAT))},
				"SYS_SYSR1":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SYSR1))},
				"SYS_TSEMACQUIRE": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_TSEMACQUIRE))},
				"SYS_UNMOUNT":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_UNMOUNT))},
				"SYS_WSTAT":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_WSTAT))},
				"S_IFBLK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFBLK))},
				"S_IFCHR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFCHR))},
				"S_IFDIR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFDIR))},
				"S_IFIFO":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFIFO))},
				"S_IFLNK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFLNK))},
				"S_IFMT":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFMT))},
				"S_IFREG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFREG))},
				"S_IFSOCK":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSOCK))},
			},
		}
	})
}
