// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.24 && !go1.25
// +build go1.24,!go1.25

package syscall

import (
	q "syscall"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("syscall", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "syscall",
			Path: "syscall",
			Deps: map[string]string{
				"errors":             "errors",
				"internal/bytealg":   "bytealg",
				"internal/byteorder": "byteorder",
				"internal/goarch":    "goarch",
				"internal/itoa":      "itoa",
				"internal/oserror":   "oserror",
				"runtime":            "runtime",
				"sync":               "sync",
				"syscall/js":         "js",
				"unsafe":             "unsafe",
			},
			Interfaces: map[string]reflect.Type{
				"Conn":     reflect.TypeOf((*q.Conn)(nil)).Elem(),
				"RawConn":  reflect.TypeOf((*q.RawConn)(nil)).Elem(),
				"Sockaddr": reflect.TypeOf((*q.Sockaddr)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Dirent":        reflect.TypeOf((*q.Dirent)(nil)).Elem(),
				"Errno":         reflect.TypeOf((*q.Errno)(nil)).Elem(),
				"Iovec":         reflect.TypeOf((*q.Iovec)(nil)).Elem(),
				"ProcAttr":      reflect.TypeOf((*q.ProcAttr)(nil)).Elem(),
				"Rusage":        reflect.TypeOf((*q.Rusage)(nil)).Elem(),
				"Signal":        reflect.TypeOf((*q.Signal)(nil)).Elem(),
				"SockaddrInet4": reflect.TypeOf((*q.SockaddrInet4)(nil)).Elem(),
				"SockaddrInet6": reflect.TypeOf((*q.SockaddrInet6)(nil)).Elem(),
				"SockaddrUnix":  reflect.TypeOf((*q.SockaddrUnix)(nil)).Elem(),
				"Stat_t":        reflect.TypeOf((*q.Stat_t)(nil)).Elem(),
				"SysProcAttr":   reflect.TypeOf((*q.SysProcAttr)(nil)).Elem(),
				"Timespec":      reflect.TypeOf((*q.Timespec)(nil)).Elem(),
				"Timeval":       reflect.TypeOf((*q.Timeval)(nil)).Elem(),
				"WaitStatus":    reflect.TypeOf((*q.WaitStatus)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]interface{}{
				"ForkLock": &q.ForkLock,
			},
			Funcs: map[string]interface{}{
				"Accept":              q.Accept,
				"Bind":                q.Bind,
				"BytePtrFromString":   q.BytePtrFromString,
				"ByteSliceFromString": q.ByteSliceFromString,
				"Chdir":               q.Chdir,
				"Chmod":               q.Chmod,
				"Chown":               q.Chown,
				"Clearenv":            q.Clearenv,
				"Close":               q.Close,
				"CloseOnExec":         q.CloseOnExec,
				"Connect":             q.Connect,
				"Dup":                 q.Dup,
				"Dup2":                q.Dup2,
				"Environ":             q.Environ,
				"Exit":                q.Exit,
				"Fchdir":              q.Fchdir,
				"Fchmod":              q.Fchmod,
				"Fchown":              q.Fchown,
				"Fstat":               q.Fstat,
				"Fsync":               q.Fsync,
				"Ftruncate":           q.Ftruncate,
				"Getcwd":              q.Getcwd,
				"Getegid":             q.Getegid,
				"Getenv":              q.Getenv,
				"Geteuid":             q.Geteuid,
				"Getgid":              q.Getgid,
				"Getgroups":           q.Getgroups,
				"Getpagesize":         q.Getpagesize,
				"Getpid":              q.Getpid,
				"Getppid":             q.Getppid,
				"GetsockoptInt":       q.GetsockoptInt,
				"Gettimeofday":        q.Gettimeofday,
				"Getuid":              q.Getuid,
				"Getwd":               q.Getwd,
				"Kill":                q.Kill,
				"Lchown":              q.Lchown,
				"Link":                q.Link,
				"Listen":              q.Listen,
				"Lstat":               q.Lstat,
				"Mkdir":               q.Mkdir,
				"NsecToTimespec":      q.NsecToTimespec,
				"NsecToTimeval":       q.NsecToTimeval,
				"Open":                q.Open,
				"ParseDirent":         q.ParseDirent,
				"Pipe":                q.Pipe,
				"Pread":               q.Pread,
				"Pwrite":              q.Pwrite,
				"RawSyscall":          q.RawSyscall,
				"RawSyscall6":         q.RawSyscall6,
				"Read":                q.Read,
				"ReadDirent":          q.ReadDirent,
				"Readlink":            q.Readlink,
				"Recvfrom":            q.Recvfrom,
				"Recvmsg":             q.Recvmsg,
				"Rename":              q.Rename,
				"Rmdir":               q.Rmdir,
				"Seek":                q.Seek,
				"Sendfile":            q.Sendfile,
				"SendmsgN":            q.SendmsgN,
				"Sendto":              q.Sendto,
				"SetNonblock":         q.SetNonblock,
				"SetReadDeadline":     q.SetReadDeadline,
				"SetWriteDeadline":    q.SetWriteDeadline,
				"Setenv":              q.Setenv,
				"SetsockoptInt":       q.SetsockoptInt,
				"Shutdown":            q.Shutdown,
				"Socket":              q.Socket,
				"StartProcess":        q.StartProcess,
				"Stat":                q.Stat,
				"StopIO":              q.StopIO,
				"StringBytePtr":       q.StringBytePtr,
				"StringByteSlice":     q.StringByteSlice,
				"Symlink":             q.Symlink,
				"Syscall":             q.Syscall,
				"Syscall6":            q.Syscall6,
				"Sysctl":              q.Sysctl,
				"TimespecToNsec":      q.TimespecToNsec,
				"TimevalToNsec":       q.TimevalToNsec,
				"Truncate":            q.Truncate,
				"Umask":               q.Umask,
				"Unlink":              q.Unlink,
				"Unsetenv":            q.Unsetenv,
				"UtimesNano":          q.UtimesNano,
				"Wait4":               q.Wait4,
				"Write":               q.Write,
			},
			TypedConsts: map[string]interface{}{
				"E2BIG":           q.E2BIG,
				"EACCES":          q.EACCES,
				"EADDRINUSE":      q.EADDRINUSE,
				"EADDRNOTAVAIL":   q.EADDRNOTAVAIL,
				"EADV":            q.EADV,
				"EAFNOSUPPORT":    q.EAFNOSUPPORT,
				"EAGAIN":          q.EAGAIN,
				"EALREADY":        q.EALREADY,
				"EBADE":           q.EBADE,
				"EBADF":           q.EBADF,
				"EBADFD":          q.EBADFD,
				"EBADMSG":         q.EBADMSG,
				"EBADR":           q.EBADR,
				"EBADRQC":         q.EBADRQC,
				"EBADSLT":         q.EBADSLT,
				"EBFONT":          q.EBFONT,
				"EBUSY":           q.EBUSY,
				"ECANCELED":       q.ECANCELED,
				"ECASECLASH":      q.ECASECLASH,
				"ECHILD":          q.ECHILD,
				"ECHRNG":          q.ECHRNG,
				"ECOMM":           q.ECOMM,
				"ECONNABORTED":    q.ECONNABORTED,
				"ECONNREFUSED":    q.ECONNREFUSED,
				"ECONNRESET":      q.ECONNRESET,
				"EDEADLK":         q.EDEADLK,
				"EDEADLOCK":       q.EDEADLOCK,
				"EDESTADDRREQ":    q.EDESTADDRREQ,
				"EDOM":            q.EDOM,
				"EDOTDOT":         q.EDOTDOT,
				"EDQUOT":          q.EDQUOT,
				"EEXIST":          q.EEXIST,
				"EFAULT":          q.EFAULT,
				"EFBIG":           q.EFBIG,
				"EFTYPE":          q.EFTYPE,
				"EHOSTDOWN":       q.EHOSTDOWN,
				"EHOSTUNREACH":    q.EHOSTUNREACH,
				"EIDRM":           q.EIDRM,
				"EILSEQ":          q.EILSEQ,
				"EINPROGRESS":     q.EINPROGRESS,
				"EINTR":           q.EINTR,
				"EINVAL":          q.EINVAL,
				"EIO":             q.EIO,
				"EISCONN":         q.EISCONN,
				"EISDIR":          q.EISDIR,
				"EL2HLT":          q.EL2HLT,
				"EL2NSYNC":        q.EL2NSYNC,
				"EL3HLT":          q.EL3HLT,
				"EL3RST":          q.EL3RST,
				"ELBIN":           q.ELBIN,
				"ELIBACC":         q.ELIBACC,
				"ELIBBAD":         q.ELIBBAD,
				"ELIBEXEC":        q.ELIBEXEC,
				"ELIBMAX":         q.ELIBMAX,
				"ELIBSCN":         q.ELIBSCN,
				"ELNRNG":          q.ELNRNG,
				"ELOOP":           q.ELOOP,
				"EMFILE":          q.EMFILE,
				"EMLINK":          q.EMLINK,
				"EMSGSIZE":        q.EMSGSIZE,
				"EMULTIHOP":       q.EMULTIHOP,
				"ENAMETOOLONG":    q.ENAMETOOLONG,
				"ENETDOWN":        q.ENETDOWN,
				"ENETRESET":       q.ENETRESET,
				"ENETUNREACH":     q.ENETUNREACH,
				"ENFILE":          q.ENFILE,
				"ENMFILE":         q.ENMFILE,
				"ENOANO":          q.ENOANO,
				"ENOBUFS":         q.ENOBUFS,
				"ENOCSI":          q.ENOCSI,
				"ENODATA":         q.ENODATA,
				"ENODEV":          q.ENODEV,
				"ENOENT":          q.ENOENT,
				"ENOEXEC":         q.ENOEXEC,
				"ENOLCK":          q.ENOLCK,
				"ENOLINK":         q.ENOLINK,
				"ENOMEDIUM":       q.ENOMEDIUM,
				"ENOMEM":          q.ENOMEM,
				"ENOMSG":          q.ENOMSG,
				"ENONET":          q.ENONET,
				"ENOPKG":          q.ENOPKG,
				"ENOPROTOOPT":     q.ENOPROTOOPT,
				"ENOSHARE":        q.ENOSHARE,
				"ENOSPC":          q.ENOSPC,
				"ENOSR":           q.ENOSR,
				"ENOSTR":          q.ENOSTR,
				"ENOSYS":          q.ENOSYS,
				"ENOTCONN":        q.ENOTCONN,
				"ENOTDIR":         q.ENOTDIR,
				"ENOTEMPTY":       q.ENOTEMPTY,
				"ENOTSOCK":        q.ENOTSOCK,
				"ENOTSUP":         q.ENOTSUP,
				"ENOTTY":          q.ENOTTY,
				"ENOTUNIQ":        q.ENOTUNIQ,
				"ENXIO":           q.ENXIO,
				"EOPNOTSUPP":      q.EOPNOTSUPP,
				"EOVERFLOW":       q.EOVERFLOW,
				"EPERM":           q.EPERM,
				"EPFNOSUPPORT":    q.EPFNOSUPPORT,
				"EPIPE":           q.EPIPE,
				"EPROCLIM":        q.EPROCLIM,
				"EPROTO":          q.EPROTO,
				"EPROTONOSUPPORT": q.EPROTONOSUPPORT,
				"EPROTOTYPE":      q.EPROTOTYPE,
				"ERANGE":          q.ERANGE,
				"EREMCHG":         q.EREMCHG,
				"EREMOTE":         q.EREMOTE,
				"EROFS":           q.EROFS,
				"ESHUTDOWN":       q.ESHUTDOWN,
				"ESOCKTNOSUPPORT": q.ESOCKTNOSUPPORT,
				"ESPIPE":          q.ESPIPE,
				"ESRCH":           q.ESRCH,
				"ESRMNT":          q.ESRMNT,
				"ESTALE":          q.ESTALE,
				"ETIME":           q.ETIME,
				"ETIMEDOUT":       q.ETIMEDOUT,
				"ETOOMANYREFS":    q.ETOOMANYREFS,
				"EUNATCH":         q.EUNATCH,
				"EUSERS":          q.EUSERS,
				"EWOULDBLOCK":     q.EWOULDBLOCK,
				"EXDEV":           q.EXDEV,
				"EXFULL":          q.EXFULL,
				"SIGCHLD":         q.SIGCHLD,
				"SIGINT":          q.SIGINT,
				"SIGKILL":         q.SIGKILL,
				"SIGQUIT":         q.SIGQUIT,
				"SIGTERM":         q.SIGTERM,
				"SIGTRAP":         q.SIGTRAP,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"AF_INET":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_INET))},
				"AF_INET6":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_INET6))},
				"AF_UNIX":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_UNIX))},
				"AF_UNSPEC":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.AF_UNSPEC))},
				"F_CNVT":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_CNVT))},
				"F_DUPFD":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_DUPFD))},
				"F_DUPFD_CLOEXEC": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_DUPFD_CLOEXEC))},
				"F_GETFD":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETFD))},
				"F_GETFL":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETFL))},
				"F_GETLK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETLK))},
				"F_GETOWN":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_GETOWN))},
				"F_RDLCK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RDLCK))},
				"F_RGETLK":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RGETLK))},
				"F_RSETLK":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RSETLK))},
				"F_RSETLKW":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_RSETLKW))},
				"F_SETFD":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETFD))},
				"F_SETFL":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETFL))},
				"F_SETLK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETLK))},
				"F_SETLKW":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETLKW))},
				"F_SETOWN":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_SETOWN))},
				"F_UNLCK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_UNLCK))},
				"F_UNLKSYS":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_UNLKSYS))},
				"F_WRLCK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.F_WRLCK))},
				"IPPROTO_IP":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IP))},
				"IPPROTO_IPV4":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IPV4))},
				"IPPROTO_IPV6":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_IPV6))},
				"IPPROTO_TCP":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_TCP))},
				"IPPROTO_UDP":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPPROTO_UDP))},
				"IPV6_V6ONLY":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPV6_V6ONLY))},
				"ImplementsGetwd": {Typ: "untyped bool", Value: constant.MakeBool(bool(q.ImplementsGetwd))},
				"O_APPEND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_APPEND))},
				"O_CLOEXEC":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CLOEXEC))},
				"O_CREAT":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CREAT))},
				"O_CREATE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CREATE))},
				"O_DIRECTORY":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_DIRECTORY))},
				"O_EXCL":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_EXCL))},
				"O_RDONLY":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDONLY))},
				"O_RDWR":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDWR))},
				"O_SYNC":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_SYNC))},
				"O_TRUNC":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_TRUNC))},
				"O_WRONLY":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_WRONLY))},
				"PathMax":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.PathMax))},
				"SOCK_DGRAM":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_DGRAM))},
				"SOCK_RAW":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_RAW))},
				"SOCK_SEQPACKET":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_SEQPACKET))},
				"SOCK_STREAM":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOCK_STREAM))},
				"SOMAXCONN":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SOMAXCONN))},
				"SO_ERROR":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SO_ERROR))},
				"SYS_FCNTL":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FCNTL))},
				"S_IEXEC":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IEXEC))},
				"S_IFBLK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFBLK))},
				"S_IFBOUNDSOCK":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFBOUNDSOCK))},
				"S_IFCHR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFCHR))},
				"S_IFCOND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFCOND))},
				"S_IFDIR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFDIR))},
				"S_IFDSOCK":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFDSOCK))},
				"S_IFIFO":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFIFO))},
				"S_IFLNK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFLNK))},
				"S_IFMT":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFMT))},
				"S_IFMUTEX":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFMUTEX))},
				"S_IFREG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFREG))},
				"S_IFSEMA":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSEMA))},
				"S_IFSHM":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSHM))},
				"S_IFSHM_SYSV":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSHM_SYSV))},
				"S_IFSOCK":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSOCK))},
				"S_IFSOCKADDR":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSOCKADDR))},
				"S_IREAD":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IREAD))},
				"S_IRGRP":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRGRP))},
				"S_IROTH":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IROTH))},
				"S_IRUSR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRUSR))},
				"S_IRWXG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXG))},
				"S_IRWXO":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXO))},
				"S_IRWXU":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IRWXU))},
				"S_ISGID":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISGID))},
				"S_ISUID":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISUID))},
				"S_ISVTX":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_ISVTX))},
				"S_IWGRP":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWGRP))},
				"S_IWOTH":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWOTH))},
				"S_IWRITE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWRITE))},
				"S_IWUSR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IWUSR))},
				"S_IXGRP":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXGRP))},
				"S_IXOTH":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXOTH))},
				"S_IXUSR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IXUSR))},
				"S_UNSUP":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_UNSUP))},
				"Stderr":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stderr))},
				"Stdin":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stdin))},
				"Stdout":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.Stdout))},
			},
		}
	})
}
