// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.24 && !go1.25
// +build go1.24,!go1.25

package syscall

import (
	q "syscall"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackageLazy("syscall", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "syscall",
			Path: "syscall",
			Deps: map[string]string{
				"errors":             "errors",
				"internal/bytealg":   "bytealg",
				"internal/byteorder": "byteorder",
				"internal/itoa":      "itoa",
				"internal/oserror":   "oserror",
				"runtime":            "runtime",
				"sync":               "sync",
				"unsafe":             "unsafe",
			},
			Interfaces: map[string]reflect.Type{
				"Conn":    reflect.TypeOf((*q.Conn)(nil)).Elem(),
				"RawConn": reflect.TypeOf((*q.RawConn)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Dir":         reflect.TypeOf((*q.Dir)(nil)).Elem(),
				"ErrorString": reflect.TypeOf((*q.ErrorString)(nil)).Elem(),
				"Note":        reflect.TypeOf((*q.Note)(nil)).Elem(),
				"ProcAttr":    reflect.TypeOf((*q.ProcAttr)(nil)).Elem(),
				"Qid":         reflect.TypeOf((*q.Qid)(nil)).Elem(),
				"SysProcAttr": reflect.TypeOf((*q.SysProcAttr)(nil)).Elem(),
				"Timespec":    reflect.TypeOf((*q.Timespec)(nil)).Elem(),
				"Timeval":     reflect.TypeOf((*q.Timeval)(nil)).Elem(),
				"Waitmsg":     reflect.TypeOf((*q.Waitmsg)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]reflect.Value{
				"EACCES":            reflect.ValueOf(&q.EACCES),
				"EAFNOSUPPORT":      reflect.ValueOf(&q.EAFNOSUPPORT),
				"EBUSY":             reflect.ValueOf(&q.EBUSY),
				"EEXIST":            reflect.ValueOf(&q.EEXIST),
				"EINTR":             reflect.ValueOf(&q.EINTR),
				"EINVAL":            reflect.ValueOf(&q.EINVAL),
				"EIO":               reflect.ValueOf(&q.EIO),
				"EISDIR":            reflect.ValueOf(&q.EISDIR),
				"EMFILE":            reflect.ValueOf(&q.EMFILE),
				"ENAMETOOLONG":      reflect.ValueOf(&q.ENAMETOOLONG),
				"ENOENT":            reflect.ValueOf(&q.ENOENT),
				"ENOTDIR":           reflect.ValueOf(&q.ENOTDIR),
				"EPERM":             reflect.ValueOf(&q.EPERM),
				"EPLAN9":            reflect.ValueOf(&q.EPLAN9),
				"ESPIPE":            reflect.ValueOf(&q.ESPIPE),
				"ETIMEDOUT":         reflect.ValueOf(&q.ETIMEDOUT),
				"ErrBadName":        reflect.ValueOf(&q.ErrBadName),
				"ErrBadStat":        reflect.ValueOf(&q.ErrBadStat),
				"ErrShortStat":      reflect.ValueOf(&q.ErrShortStat),
				"ForkLock":          reflect.ValueOf(&q.ForkLock),
				"SocketDisableIPv6": reflect.ValueOf(&q.SocketDisableIPv6),
				"Stderr":            reflect.ValueOf(&q.Stderr),
				"Stdin":             reflect.ValueOf(&q.Stdin),
				"Stdout":            reflect.ValueOf(&q.Stdout),
			},
			Funcs: map[string]reflect.Value{
				"Await":               reflect.ValueOf(q.Await),
				"Bind":                reflect.ValueOf(q.Bind),
				"BytePtrFromString":   reflect.ValueOf(q.BytePtrFromString),
				"ByteSliceFromString": reflect.ValueOf(q.ByteSliceFromString),
				"Chdir":               reflect.ValueOf(q.Chdir),
				"Clearenv":            reflect.ValueOf(q.Clearenv),
				"Close":               reflect.ValueOf(q.Close),
				"Create":              reflect.ValueOf(q.Create),
				"Dup":                 reflect.ValueOf(q.Dup),
				"Environ":             reflect.ValueOf(q.Environ),
				"Exec":                reflect.ValueOf(q.Exec),
				"Exit":                reflect.ValueOf(q.Exit),
				"Fchdir":              reflect.ValueOf(q.Fchdir),
				"Fd2path":             reflect.ValueOf(q.Fd2path),
				"Fixwd":               reflect.ValueOf(q.Fixwd),
				"ForkExec":            reflect.ValueOf(q.ForkExec),
				"Fstat":               reflect.ValueOf(q.Fstat),
				"Fwstat":              reflect.ValueOf(q.Fwstat),
				"Getegid":             reflect.ValueOf(q.Getegid),
				"Getenv":              reflect.ValueOf(q.Getenv),
				"Geteuid":             reflect.ValueOf(q.Geteuid),
				"Getgid":              reflect.ValueOf(q.Getgid),
				"Getgroups":           reflect.ValueOf(q.Getgroups),
				"Getpagesize":         reflect.ValueOf(q.Getpagesize),
				"Getpid":              reflect.ValueOf(q.Getpid),
				"Getppid":             reflect.ValueOf(q.Getppid),
				"Gettimeofday":        reflect.ValueOf(q.Gettimeofday),
				"Getuid":              reflect.ValueOf(q.Getuid),
				"Getwd":               reflect.ValueOf(q.Getwd),
				"Mkdir":               reflect.ValueOf(q.Mkdir),
				"Mount":               reflect.ValueOf(q.Mount),
				"NewError":            reflect.ValueOf(q.NewError),
				"NsecToTimeval":       reflect.ValueOf(q.NsecToTimeval),
				"Open":                reflect.ValueOf(q.Open),
				"Pipe":                reflect.ValueOf(q.Pipe),
				"Pread":               reflect.ValueOf(q.Pread),
				"Pwrite":              reflect.ValueOf(q.Pwrite),
				"RawSyscall":          reflect.ValueOf(q.RawSyscall),
				"RawSyscall6":         reflect.ValueOf(q.RawSyscall6),
				"Read":                reflect.ValueOf(q.Read),
				"Remove":              reflect.ValueOf(q.Remove),
				"Seek":                reflect.ValueOf(q.Seek),
				"Setenv":              reflect.ValueOf(q.Setenv),
				"SlicePtrFromStrings": reflect.ValueOf(q.SlicePtrFromStrings),
				"StartProcess":        reflect.ValueOf(q.StartProcess),
				"Stat":                reflect.ValueOf(q.Stat),
				"StringBytePtr":       reflect.ValueOf(q.StringBytePtr),
				"StringByteSlice":     reflect.ValueOf(q.StringByteSlice),
				"StringSlicePtr":      reflect.ValueOf(q.StringSlicePtr),
				"Syscall":             reflect.ValueOf(q.Syscall),
				"Syscall6":            reflect.ValueOf(q.Syscall6),
				"UnmarshalDir":        reflect.ValueOf(q.UnmarshalDir),
				"Unmount":             reflect.ValueOf(q.Unmount),
				"Unsetenv":            reflect.ValueOf(q.Unsetenv),
				"WaitProcess":         reflect.ValueOf(q.WaitProcess),
				"Write":               reflect.ValueOf(q.Write),
				"Wstat":               reflect.ValueOf(q.Wstat),
			},
			TypedConsts: map[string]ixgo.TypedConst{
				"SIGABRT": {Typ: reflect.TypeOf(q.SIGABRT), Value: constant.MakeString(string(q.SIGABRT))},
				"SIGALRM": {Typ: reflect.TypeOf(q.SIGALRM), Value: constant.MakeString(string(q.SIGALRM))},
				"SIGHUP":  {Typ: reflect.TypeOf(q.SIGHUP), Value: constant.MakeString(string(q.SIGHUP))},
				"SIGINT":  {Typ: reflect.TypeOf(q.SIGINT), Value: constant.MakeString(string(q.SIGINT))},
				"SIGKILL": {Typ: reflect.TypeOf(q.SIGKILL), Value: constant.MakeString(string(q.SIGKILL))},
				"SIGTERM": {Typ: reflect.TypeOf(q.SIGTERM), Value: constant.MakeString(string(q.SIGTERM))},
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"DMAPPEND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMAPPEND))},
				"DMAUTH":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMAUTH))},
				"DMDIR":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMDIR))},
				"DMEXCL":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMEXCL))},
				"DMEXEC":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMEXEC))},
				"DMMOUNT":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMMOUNT))},
				"DMREAD":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMREAD))},
				"DMTMP":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMTMP))},
				"DMWRITE":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DMWRITE))},
				"ERRMAX":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.ERRMAX))},
				"ImplementsGetwd": {Typ: "untyped bool", Value: constant.MakeBool(bool(q.ImplementsGetwd))},
				"MAFTER":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MAFTER))},
				"MBEFORE":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MBEFORE))},
				"MCACHE":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MCACHE))},
				"MCREATE":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MCREATE))},
				"MMASK":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MMASK))},
				"MORDER":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MORDER))},
				"MREPL":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.MREPL))},
				"O_APPEND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_APPEND))},
				"O_ASYNC":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_ASYNC))},
				"O_CLOEXEC":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CLOEXEC))},
				"O_CREAT":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_CREAT))},
				"O_EXCL":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_EXCL))},
				"O_NOCTTY":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_NOCTTY))},
				"O_NONBLOCK":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_NONBLOCK))},
				"O_RDONLY":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDONLY))},
				"O_RDWR":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_RDWR))},
				"O_SYNC":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_SYNC))},
				"O_TRUNC":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_TRUNC))},
				"O_WRONLY":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.O_WRONLY))},
				"QTAPPEND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTAPPEND))},
				"QTAUTH":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTAUTH))},
				"QTDIR":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTDIR))},
				"QTEXCL":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTEXCL))},
				"QTFILE":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTFILE))},
				"QTMOUNT":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTMOUNT))},
				"QTTMP":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.QTTMP))},
				"RFCENVG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFCENVG))},
				"RFCFDG":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFCFDG))},
				"RFCNAMEG":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFCNAMEG))},
				"RFENVG":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFENVG))},
				"RFFDG":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFFDG))},
				"RFMEM":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFMEM))},
				"RFNAMEG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFNAMEG))},
				"RFNOMNT":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFNOMNT))},
				"RFNOTEG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFNOTEG))},
				"RFNOWAIT":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFNOWAIT))},
				"RFPROC":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFPROC))},
				"RFREND":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.RFREND))},
				"STATFIXLEN":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.STATFIXLEN))},
				"STATMAX":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.STATMAX))},
				"SYS_ALARM":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_ALARM))},
				"SYS_AWAIT":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_AWAIT))},
				"SYS_BIND":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_BIND))},
				"SYS_BRK_":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_BRK_))},
				"SYS_CHDIR":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_CHDIR))},
				"SYS_CLOSE":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_CLOSE))},
				"SYS_CREATE":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_CREATE))},
				"SYS_DUP":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_DUP))},
				"SYS_ERRSTR":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_ERRSTR))},
				"SYS_EXEC":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_EXEC))},
				"SYS_EXITS":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_EXITS))},
				"SYS_FAUTH":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FAUTH))},
				"SYS_FD2PATH":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FD2PATH))},
				"SYS_FSTAT":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FSTAT))},
				"SYS_FVERSION":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FVERSION))},
				"SYS_FWSTAT":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_FWSTAT))},
				"SYS_MOUNT":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_MOUNT))},
				"SYS_NOTED":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_NOTED))},
				"SYS_NOTIFY":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_NOTIFY))},
				"SYS_NSEC":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_NSEC))},
				"SYS_OPEN":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_OPEN))},
				"SYS_OSEEK":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_OSEEK))},
				"SYS_PIPE":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_PIPE))},
				"SYS_PREAD":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_PREAD))},
				"SYS_PWRITE":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_PWRITE))},
				"SYS_REMOVE":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_REMOVE))},
				"SYS_RENDEZVOUS":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_RENDEZVOUS))},
				"SYS_RFORK":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_RFORK))},
				"SYS_SEEK":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEEK))},
				"SYS_SEGATTACH":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEGATTACH))},
				"SYS_SEGBRK":      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEGBRK))},
				"SYS_SEGDETACH":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEGDETACH))},
				"SYS_SEGFLUSH":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEGFLUSH))},
				"SYS_SEGFREE":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEGFREE))},
				"SYS_SEMACQUIRE":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEMACQUIRE))},
				"SYS_SEMRELEASE":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SEMRELEASE))},
				"SYS_SLEEP":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SLEEP))},
				"SYS_STAT":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_STAT))},
				"SYS_SYSR1":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_SYSR1))},
				"SYS_TSEMACQUIRE": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_TSEMACQUIRE))},
				"SYS_UNMOUNT":     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_UNMOUNT))},
				"SYS_WSTAT":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.SYS_WSTAT))},
				"S_IFBLK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFBLK))},
				"S_IFCHR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFCHR))},
				"S_IFDIR":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFDIR))},
				"S_IFIFO":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFIFO))},
				"S_IFLNK":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFLNK))},
				"S_IFMT":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFMT))},
				"S_IFREG":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFREG))},
				"S_IFSOCK":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.S_IFSOCK))},
			},
		}
	})
}
