// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.25 && !go1.26
// +build go1.25,!go1.26

package token

import (
	q "go/token"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("go/token", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "token",
			Path: "go/token",
			Deps: map[string]string{
				"cmp":          "cmp",
				"fmt":          "fmt",
				"iter":         "iter",
				"slices":       "slices",
				"strconv":      "strconv",
				"sync":         "sync",
				"sync/atomic":  "atomic",
				"unicode":      "unicode",
				"unicode/utf8": "utf8",
			},
			Interfaces: map[string]reflect.Type{},
			NamedTypes: map[string]reflect.Type{
				"File":     reflect.TypeOf((*q.File)(nil)).Elem(),
				"FileSet":  reflect.TypeOf((*q.FileSet)(nil)).Elem(),
				"Pos":      reflect.TypeOf((*q.Pos)(nil)).Elem(),
				"Position": reflect.TypeOf((*q.Position)(nil)).Elem(),
				"Token":    reflect.TypeOf((*q.Token)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars:       map[string]interface{}{},
			Funcs: map[string]interface{}{
				"IsExported":   q.IsExported,
				"IsIdentifier": q.IsIdentifier,
				"IsKeyword":    q.IsKeyword,
				"Lookup":       q.Lookup,
				"NewFileSet":   q.NewFileSet,
			},
			TypedConsts: map[string]interface{}{
				"ADD":            q.ADD,
				"ADD_ASSIGN":     q.ADD_ASSIGN,
				"AND":            q.AND,
				"AND_ASSIGN":     q.AND_ASSIGN,
				"AND_NOT":        q.AND_NOT,
				"AND_NOT_ASSIGN": q.AND_NOT_ASSIGN,
				"ARROW":          q.ARROW,
				"ASSIGN":         q.ASSIGN,
				"BREAK":          q.BREAK,
				"CASE":           q.CASE,
				"CHAN":           q.CHAN,
				"CHAR":           q.CHAR,
				"COLON":          q.COLON,
				"COMMA":          q.COMMA,
				"COMMENT":        q.COMMENT,
				"CONST":          q.CONST,
				"CONTINUE":       q.CONTINUE,
				"DEC":            q.DEC,
				"DEFAULT":        q.DEFAULT,
				"DEFER":          q.DEFER,
				"DEFINE":         q.DEFINE,
				"ELLIPSIS":       q.ELLIPSIS,
				"ELSE":           q.ELSE,
				"EOF":            q.EOF,
				"EQL":            q.EQL,
				"FALLTHROUGH":    q.FALLTHROUGH,
				"FLOAT":          q.FLOAT,
				"FOR":            q.FOR,
				"FUNC":           q.FUNC,
				"GEQ":            q.GEQ,
				"GO":             q.GO,
				"GOTO":           q.GOTO,
				"GTR":            q.GTR,
				"IDENT":          q.IDENT,
				"IF":             q.IF,
				"ILLEGAL":        q.ILLEGAL,
				"IMAG":           q.IMAG,
				"IMPORT":         q.IMPORT,
				"INC":            q.INC,
				"INT":            q.INT,
				"INTERFACE":      q.INTERFACE,
				"LAND":           q.LAND,
				"LBRACE":         q.LBRACE,
				"LBRACK":         q.LBRACK,
				"LEQ":            q.LEQ,
				"LOR":            q.LOR,
				"LPAREN":         q.LPAREN,
				"LSS":            q.LSS,
				"MAP":            q.MAP,
				"MUL":            q.MUL,
				"MUL_ASSIGN":     q.MUL_ASSIGN,
				"NEQ":            q.NEQ,
				"NOT":            q.NOT,
				"NoPos":          q.NoPos,
				"OR":             q.OR,
				"OR_ASSIGN":      q.OR_ASSIGN,
				"PACKAGE":        q.PACKAGE,
				"PERIOD":         q.PERIOD,
				"QUO":            q.QUO,
				"QUO_ASSIGN":     q.QUO_ASSIGN,
				"RANGE":          q.RANGE,
				"RBRACE":         q.RBRACE,
				"RBRACK":         q.RBRACK,
				"REM":            q.REM,
				"REM_ASSIGN":     q.REM_ASSIGN,
				"RETURN":         q.RETURN,
				"RPAREN":         q.RPAREN,
				"SELECT":         q.SELECT,
				"SEMICOLON":      q.SEMICOLON,
				"SHL":            q.SHL,
				"SHL_ASSIGN":     q.SHL_ASSIGN,
				"SHR":            q.SHR,
				"SHR_ASSIGN":     q.SHR_ASSIGN,
				"STRING":         q.STRING,
				"STRUCT":         q.STRUCT,
				"SUB":            q.SUB,
				"SUB_ASSIGN":     q.SUB_ASSIGN,
				"SWITCH":         q.SWITCH,
				"TILDE":          q.TILDE,
				"TYPE":           q.TYPE,
				"VAR":            q.VAR,
				"XOR":            q.XOR,
				"XOR_ASSIGN":     q.XOR_ASSIGN,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"HighestPrec": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.HighestPrec))},
				"LowestPrec":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.LowestPrec))},
				"UnaryPrec":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.UnaryPrec))},
			},
		}
	})
}
