// export by github.com/goplus/ixgo/cmd/qexp

package token

import (
	q "github.com/goplus/xgo/token"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage(&ixgo.Package{
		Name: "token",
		Path: "github.com/goplus/xgo/token",
		Deps: map[string]string{
			"github.com/goplus/gogen/token":                  "token",
			"github.com/goplus/xgo/token/internal/tokenutil": "tokenutil",
			"go/token": "token",
			"strconv":  "strconv",
		},
		Interfaces: map[string]reflect.Type{},
		NamedTypes: map[string]reflect.Type{
			"Token": reflect.TypeOf((*q.Token)(nil)).Elem(),
		},
		AliasTypes: map[string]reflect.Type{
			"File":     reflect.TypeOf((*q.File)(nil)).Elem(),
			"FileSet":  reflect.TypeOf((*q.FileSet)(nil)).Elem(),
			"Pos":      reflect.TypeOf((*q.Pos)(nil)).Elem(),
			"Position": reflect.TypeOf((*q.Position)(nil)).Elem(),
		},
		Vars: map[string]reflect.Value{},
		Funcs: map[string]reflect.Value{
			"IsExported":   reflect.ValueOf(q.IsExported),
			"IsIdentifier": reflect.ValueOf(q.IsIdentifier),
			"IsKeyword":    reflect.ValueOf(q.IsKeyword),
			"Lines":        reflect.ValueOf(q.Lines),
			"Lookup":       reflect.ValueOf(q.Lookup),
			"NewFileSet":   reflect.ValueOf(q.NewFileSet),
		},
		TypedConsts: map[string]ixgo.TypedConst{
			"ADD":            {Typ: reflect.TypeOf(q.ADD), Value: constant.MakeInt64(int64(q.ADD))},
			"ADD_ASSIGN":     {Typ: reflect.TypeOf(q.ADD_ASSIGN), Value: constant.MakeInt64(int64(q.ADD_ASSIGN))},
			"AND":            {Typ: reflect.TypeOf(q.AND), Value: constant.MakeInt64(int64(q.AND))},
			"AND_ASSIGN":     {Typ: reflect.TypeOf(q.AND_ASSIGN), Value: constant.MakeInt64(int64(q.AND_ASSIGN))},
			"AND_NOT":        {Typ: reflect.TypeOf(q.AND_NOT), Value: constant.MakeInt64(int64(q.AND_NOT))},
			"AND_NOT_ASSIGN": {Typ: reflect.TypeOf(q.AND_NOT_ASSIGN), Value: constant.MakeInt64(int64(q.AND_NOT_ASSIGN))},
			"ARROW":          {Typ: reflect.TypeOf(q.ARROW), Value: constant.MakeInt64(int64(q.ARROW))},
			"ASSIGN":         {Typ: reflect.TypeOf(q.ASSIGN), Value: constant.MakeInt64(int64(q.ASSIGN))},
			"AT":             {Typ: reflect.TypeOf(q.AT), Value: constant.MakeInt64(int64(q.AT))},
			"BIDIARROW":      {Typ: reflect.TypeOf(q.BIDIARROW), Value: constant.MakeInt64(int64(q.BIDIARROW))},
			"BREAK":          {Typ: reflect.TypeOf(q.BREAK), Value: constant.MakeInt64(int64(q.BREAK))},
			"CASE":           {Typ: reflect.TypeOf(q.CASE), Value: constant.MakeInt64(int64(q.CASE))},
			"CHAN":           {Typ: reflect.TypeOf(q.CHAN), Value: constant.MakeInt64(int64(q.CHAN))},
			"CHAR":           {Typ: reflect.TypeOf(q.CHAR), Value: constant.MakeInt64(int64(q.CHAR))},
			"COLON":          {Typ: reflect.TypeOf(q.COLON), Value: constant.MakeInt64(int64(q.COLON))},
			"COMMA":          {Typ: reflect.TypeOf(q.COMMA), Value: constant.MakeInt64(int64(q.COMMA))},
			"COMMENT":        {Typ: reflect.TypeOf(q.COMMENT), Value: constant.MakeInt64(int64(q.COMMENT))},
			"CONST":          {Typ: reflect.TypeOf(q.CONST), Value: constant.MakeInt64(int64(q.CONST))},
			"CONTINUE":       {Typ: reflect.TypeOf(q.CONTINUE), Value: constant.MakeInt64(int64(q.CONTINUE))},
			"CSTRING":        {Typ: reflect.TypeOf(q.CSTRING), Value: constant.MakeInt64(int64(q.CSTRING))},
			"DEC":            {Typ: reflect.TypeOf(q.DEC), Value: constant.MakeInt64(int64(q.DEC))},
			"DEFAULT":        {Typ: reflect.TypeOf(q.DEFAULT), Value: constant.MakeInt64(int64(q.DEFAULT))},
			"DEFER":          {Typ: reflect.TypeOf(q.DEFER), Value: constant.MakeInt64(int64(q.DEFER))},
			"DEFINE":         {Typ: reflect.TypeOf(q.DEFINE), Value: constant.MakeInt64(int64(q.DEFINE))},
			"DRARROW":        {Typ: reflect.TypeOf(q.DRARROW), Value: constant.MakeInt64(int64(q.DRARROW))},
			"ELLIPSIS":       {Typ: reflect.TypeOf(q.ELLIPSIS), Value: constant.MakeInt64(int64(q.ELLIPSIS))},
			"ELSE":           {Typ: reflect.TypeOf(q.ELSE), Value: constant.MakeInt64(int64(q.ELSE))},
			"ENV":            {Typ: reflect.TypeOf(q.ENV), Value: constant.MakeInt64(int64(q.ENV))},
			"EOF":            {Typ: reflect.TypeOf(q.EOF), Value: constant.MakeInt64(int64(q.EOF))},
			"EQL":            {Typ: reflect.TypeOf(q.EQL), Value: constant.MakeInt64(int64(q.EQL))},
			"FALLTHROUGH":    {Typ: reflect.TypeOf(q.FALLTHROUGH), Value: constant.MakeInt64(int64(q.FALLTHROUGH))},
			"FLOAT":          {Typ: reflect.TypeOf(q.FLOAT), Value: constant.MakeInt64(int64(q.FLOAT))},
			"FOR":            {Typ: reflect.TypeOf(q.FOR), Value: constant.MakeInt64(int64(q.FOR))},
			"FUNC":           {Typ: reflect.TypeOf(q.FUNC), Value: constant.MakeInt64(int64(q.FUNC))},
			"GEQ":            {Typ: reflect.TypeOf(q.GEQ), Value: constant.MakeInt64(int64(q.GEQ))},
			"GO":             {Typ: reflect.TypeOf(q.GO), Value: constant.MakeInt64(int64(q.GO))},
			"GOTO":           {Typ: reflect.TypeOf(q.GOTO), Value: constant.MakeInt64(int64(q.GOTO))},
			"GTR":            {Typ: reflect.TypeOf(q.GTR), Value: constant.MakeInt64(int64(q.GTR))},
			"IDENT":          {Typ: reflect.TypeOf(q.IDENT), Value: constant.MakeInt64(int64(q.IDENT))},
			"IF":             {Typ: reflect.TypeOf(q.IF), Value: constant.MakeInt64(int64(q.IF))},
			"ILLEGAL":        {Typ: reflect.TypeOf(q.ILLEGAL), Value: constant.MakeInt64(int64(q.ILLEGAL))},
			"IMAG":           {Typ: reflect.TypeOf(q.IMAG), Value: constant.MakeInt64(int64(q.IMAG))},
			"IMPORT":         {Typ: reflect.TypeOf(q.IMPORT), Value: constant.MakeInt64(int64(q.IMPORT))},
			"INC":            {Typ: reflect.TypeOf(q.INC), Value: constant.MakeInt64(int64(q.INC))},
			"INT":            {Typ: reflect.TypeOf(q.INT), Value: constant.MakeInt64(int64(q.INT))},
			"INTERFACE":      {Typ: reflect.TypeOf(q.INTERFACE), Value: constant.MakeInt64(int64(q.INTERFACE))},
			"LAND":           {Typ: reflect.TypeOf(q.LAND), Value: constant.MakeInt64(int64(q.LAND))},
			"LBRACE":         {Typ: reflect.TypeOf(q.LBRACE), Value: constant.MakeInt64(int64(q.LBRACE))},
			"LBRACK":         {Typ: reflect.TypeOf(q.LBRACK), Value: constant.MakeInt64(int64(q.LBRACK))},
			"LEQ":            {Typ: reflect.TypeOf(q.LEQ), Value: constant.MakeInt64(int64(q.LEQ))},
			"LOR":            {Typ: reflect.TypeOf(q.LOR), Value: constant.MakeInt64(int64(q.LOR))},
			"LPAREN":         {Typ: reflect.TypeOf(q.LPAREN), Value: constant.MakeInt64(int64(q.LPAREN))},
			"LSS":            {Typ: reflect.TypeOf(q.LSS), Value: constant.MakeInt64(int64(q.LSS))},
			"MAP":            {Typ: reflect.TypeOf(q.MAP), Value: constant.MakeInt64(int64(q.MAP))},
			"MUL":            {Typ: reflect.TypeOf(q.MUL), Value: constant.MakeInt64(int64(q.MUL))},
			"MUL_ASSIGN":     {Typ: reflect.TypeOf(q.MUL_ASSIGN), Value: constant.MakeInt64(int64(q.MUL_ASSIGN))},
			"NEQ":            {Typ: reflect.TypeOf(q.NEQ), Value: constant.MakeInt64(int64(q.NEQ))},
			"NOT":            {Typ: reflect.TypeOf(q.NOT), Value: constant.MakeInt64(int64(q.NOT))},
			"NoPos":          {Typ: reflect.TypeOf(q.NoPos), Value: constant.MakeInt64(int64(q.NoPos))},
			"OR":             {Typ: reflect.TypeOf(q.OR), Value: constant.MakeInt64(int64(q.OR))},
			"OR_ASSIGN":      {Typ: reflect.TypeOf(q.OR_ASSIGN), Value: constant.MakeInt64(int64(q.OR_ASSIGN))},
			"PACKAGE":        {Typ: reflect.TypeOf(q.PACKAGE), Value: constant.MakeInt64(int64(q.PACKAGE))},
			"PERIOD":         {Typ: reflect.TypeOf(q.PERIOD), Value: constant.MakeInt64(int64(q.PERIOD))},
			"QUESTION":       {Typ: reflect.TypeOf(q.QUESTION), Value: constant.MakeInt64(int64(q.QUESTION))},
			"QUO":            {Typ: reflect.TypeOf(q.QUO), Value: constant.MakeInt64(int64(q.QUO))},
			"QUO_ASSIGN":     {Typ: reflect.TypeOf(q.QUO_ASSIGN), Value: constant.MakeInt64(int64(q.QUO_ASSIGN))},
			"RANGE":          {Typ: reflect.TypeOf(q.RANGE), Value: constant.MakeInt64(int64(q.RANGE))},
			"RARROW":         {Typ: reflect.TypeOf(q.RARROW), Value: constant.MakeInt64(int64(q.RARROW))},
			"RAT":            {Typ: reflect.TypeOf(q.RAT), Value: constant.MakeInt64(int64(q.RAT))},
			"RBRACE":         {Typ: reflect.TypeOf(q.RBRACE), Value: constant.MakeInt64(int64(q.RBRACE))},
			"RBRACK":         {Typ: reflect.TypeOf(q.RBRACK), Value: constant.MakeInt64(int64(q.RBRACK))},
			"REM":            {Typ: reflect.TypeOf(q.REM), Value: constant.MakeInt64(int64(q.REM))},
			"REM_ASSIGN":     {Typ: reflect.TypeOf(q.REM_ASSIGN), Value: constant.MakeInt64(int64(q.REM_ASSIGN))},
			"RETURN":         {Typ: reflect.TypeOf(q.RETURN), Value: constant.MakeInt64(int64(q.RETURN))},
			"RPAREN":         {Typ: reflect.TypeOf(q.RPAREN), Value: constant.MakeInt64(int64(q.RPAREN))},
			"SELECT":         {Typ: reflect.TypeOf(q.SELECT), Value: constant.MakeInt64(int64(q.SELECT))},
			"SEMICOLON":      {Typ: reflect.TypeOf(q.SEMICOLON), Value: constant.MakeInt64(int64(q.SEMICOLON))},
			"SHL":            {Typ: reflect.TypeOf(q.SHL), Value: constant.MakeInt64(int64(q.SHL))},
			"SHL_ASSIGN":     {Typ: reflect.TypeOf(q.SHL_ASSIGN), Value: constant.MakeInt64(int64(q.SHL_ASSIGN))},
			"SHR":            {Typ: reflect.TypeOf(q.SHR), Value: constant.MakeInt64(int64(q.SHR))},
			"SHR_ASSIGN":     {Typ: reflect.TypeOf(q.SHR_ASSIGN), Value: constant.MakeInt64(int64(q.SHR_ASSIGN))},
			"SRARROW":        {Typ: reflect.TypeOf(q.SRARROW), Value: constant.MakeInt64(int64(q.SRARROW))},
			"STRING":         {Typ: reflect.TypeOf(q.STRING), Value: constant.MakeInt64(int64(q.STRING))},
			"STRUCT":         {Typ: reflect.TypeOf(q.STRUCT), Value: constant.MakeInt64(int64(q.STRUCT))},
			"SUB":            {Typ: reflect.TypeOf(q.SUB), Value: constant.MakeInt64(int64(q.SUB))},
			"SUB_ASSIGN":     {Typ: reflect.TypeOf(q.SUB_ASSIGN), Value: constant.MakeInt64(int64(q.SUB_ASSIGN))},
			"SWITCH":         {Typ: reflect.TypeOf(q.SWITCH), Value: constant.MakeInt64(int64(q.SWITCH))},
			"TILDE":          {Typ: reflect.TypeOf(q.TILDE), Value: constant.MakeInt64(int64(q.TILDE))},
			"TYPE":           {Typ: reflect.TypeOf(q.TYPE), Value: constant.MakeInt64(int64(q.TYPE))},
			"VAR":            {Typ: reflect.TypeOf(q.VAR), Value: constant.MakeInt64(int64(q.VAR))},
			"XOR":            {Typ: reflect.TypeOf(q.XOR), Value: constant.MakeInt64(int64(q.XOR))},
			"XOR_ASSIGN":     {Typ: reflect.TypeOf(q.XOR_ASSIGN), Value: constant.MakeInt64(int64(q.XOR_ASSIGN))},
		},
		UntypedConsts: map[string]ixgo.UntypedConst{
			"HighestPrec": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.HighestPrec))},
			"LowestPrec":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.LowestPrec))},
			"PYSTRING":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.PYSTRING))},
			"UNIT":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.UNIT))},
			"UnaryPrec":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.UnaryPrec))},
		},
	})
}
