package ixgo

import (
	"go/token"
	"go/types"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"unsafe"

	"golang.org/x/tools/go/ssa"
)

func findFuncByPC(interp *Interp, pc int) *function {
	if pc == 0 {
		return nil
	}
	for _, pfn := range interp.funcs {
		if pc >= pfn.base && pc <= pfn.base+len(pfn.ssaInstrs) {
			return pfn
		}
	}
	return nil
}

func findFuncByEntry(interp *Interp, entry int) *function {
	for _, pfn := range interp.funcs {
		if entry == pfn.base {
			return pfn
		}
	}
	return nil
}

func isWrapperFuncName(name string) bool {
	return strings.HasSuffix(name, "$bound") || strings.HasSuffix(name, "$thunk")
}

func runtimeFunc(pfn *function) *runtime.Func {
	fn := pfn.Fn
	f := inlineFunc(uintptr(pfn.base))
	var autogen bool
	f.name, autogen = fixedFuncName(pfn.Fn)
	if autogen {
		f.file = "<autogenerated>"
		f.line = 1
	} else {
		if pos := fn.Pos(); pos != token.NoPos {
			fpos := pfn.Interp.ctx.FileSet.Position(pos)
			f.file = filepath.ToSlash(fpos.Filename)
			f.line = fpos.Line
		}
	}
	return (*runtime.Func)(unsafe.Pointer(f))
}

var (
	reFuncName = regexp.MustCompile("\\$(\\d+)")
)

func fixedFuncName(fn *ssa.Function) (name string, autogen bool) {
	name = fn.String()
	name = reFuncName.ReplaceAllString(name, ".func$1")
	if strings.HasPrefix(name, "(") {
		if pos := strings.LastIndex(name, ")"); pos != -1 {
			line := name[1:pos]
			if strings.HasPrefix(line, "*") {
				if dot := strings.LastIndex(line, "."); dot != -1 {
					line = line[1:dot+1] + "(*" + line[dot+1:] + ")"
				}
			}
			name = line + name[pos+1:]
		}
	}
	if strings.HasSuffix(name, "$bound") {
		return name[:len(name)-6] + "-fm", true
	} else if strings.HasSuffix(name, "$thunk") {
		name = name[:len(name)-6]
		if strings.HasPrefix(name, "struct{") {
			return name, true
		}
		if sig, ok := fn.Type().(*types.Signature); ok {
			if types.IsInterface(sig.Params().At(0).Type()) {
				return name, true
			}
		}
	}
	return name, false
}
