// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.25 && !go1.26
// +build go1.25,!go1.26

package http

import (
	q "net/http"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackageLazy("net/http", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "http",
			Path: "net/http",
			Deps: map[string]string{
				"bufio":                                  "bufio",
				"bytes":                                  "bytes",
				"compress/gzip":                          "gzip",
				"container/list":                         "list",
				"context":                                "context",
				"crypto/rand":                            "rand",
				"crypto/tls":                             "tls",
				"encoding/base64":                        "base64",
				"encoding/binary":                        "binary",
				"errors":                                 "errors",
				"fmt":                                    "fmt",
				"internal/godebug":                       "godebug",
				"io":                                     "io",
				"io/fs":                                  "fs",
				"log":                                    "log",
				"maps":                                   "maps",
				"math":                                   "math",
				"math/bits":                              "bits",
				"math/rand":                              "rand",
				"mime":                                   "mime",
				"mime/multipart":                         "multipart",
				"net":                                    "net",
				"net/http/httptrace":                     "httptrace",
				"net/http/internal":                      "internal",
				"net/http/internal/ascii":                "ascii",
				"net/http/internal/httpcommon":           "httpcommon",
				"net/textproto":                          "textproto",
				"net/url":                                "url",
				"os":                                     "os",
				"path":                                   "path",
				"path/filepath":                          "filepath",
				"reflect":                                "reflect",
				"runtime":                                "runtime",
				"slices":                                 "slices",
				"sort":                                   "sort",
				"strconv":                                "strconv",
				"strings":                                "strings",
				"sync":                                   "sync",
				"sync/atomic":                            "atomic",
				"time":                                   "time",
				"unicode":                                "unicode",
				"unicode/utf8":                           "utf8",
				"unsafe":                                 "unsafe",
				"vendor/golang.org/x/net/http/httpguts":  "httpguts",
				"vendor/golang.org/x/net/http/httpproxy": "httpproxy",
				"vendor/golang.org/x/net/http2/hpack":    "hpack",
				"vendor/golang.org/x/net/idna":           "idna",
			},
			Interfaces: map[string]reflect.Type{
				"CloseNotifier":  reflect.TypeOf((*q.CloseNotifier)(nil)).Elem(),
				"CookieJar":      reflect.TypeOf((*q.CookieJar)(nil)).Elem(),
				"File":           reflect.TypeOf((*q.File)(nil)).Elem(),
				"FileSystem":     reflect.TypeOf((*q.FileSystem)(nil)).Elem(),
				"Flusher":        reflect.TypeOf((*q.Flusher)(nil)).Elem(),
				"Handler":        reflect.TypeOf((*q.Handler)(nil)).Elem(),
				"Hijacker":       reflect.TypeOf((*q.Hijacker)(nil)).Elem(),
				"Pusher":         reflect.TypeOf((*q.Pusher)(nil)).Elem(),
				"ResponseWriter": reflect.TypeOf((*q.ResponseWriter)(nil)).Elem(),
				"RoundTripper":   reflect.TypeOf((*q.RoundTripper)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Client":                reflect.TypeOf((*q.Client)(nil)).Elem(),
				"ConnState":             reflect.TypeOf((*q.ConnState)(nil)).Elem(),
				"Cookie":                reflect.TypeOf((*q.Cookie)(nil)).Elem(),
				"CrossOriginProtection": reflect.TypeOf((*q.CrossOriginProtection)(nil)).Elem(),
				"Dir":                   reflect.TypeOf((*q.Dir)(nil)).Elem(),
				"HTTP2Config":           reflect.TypeOf((*q.HTTP2Config)(nil)).Elem(),
				"HandlerFunc":           reflect.TypeOf((*q.HandlerFunc)(nil)).Elem(),
				"Header":                reflect.TypeOf((*q.Header)(nil)).Elem(),
				"MaxBytesError":         reflect.TypeOf((*q.MaxBytesError)(nil)).Elem(),
				"ProtocolError":         reflect.TypeOf((*q.ProtocolError)(nil)).Elem(),
				"Protocols":             reflect.TypeOf((*q.Protocols)(nil)).Elem(),
				"PushOptions":           reflect.TypeOf((*q.PushOptions)(nil)).Elem(),
				"Request":               reflect.TypeOf((*q.Request)(nil)).Elem(),
				"Response":              reflect.TypeOf((*q.Response)(nil)).Elem(),
				"ResponseController":    reflect.TypeOf((*q.ResponseController)(nil)).Elem(),
				"SameSite":              reflect.TypeOf((*q.SameSite)(nil)).Elem(),
				"ServeMux":              reflect.TypeOf((*q.ServeMux)(nil)).Elem(),
				"Server":                reflect.TypeOf((*q.Server)(nil)).Elem(),
				"Transport":             reflect.TypeOf((*q.Transport)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]reflect.Value{
				"DefaultClient":           reflect.ValueOf(&q.DefaultClient),
				"DefaultServeMux":         reflect.ValueOf(&q.DefaultServeMux),
				"DefaultTransport":        reflect.ValueOf(&q.DefaultTransport),
				"ErrAbortHandler":         reflect.ValueOf(&q.ErrAbortHandler),
				"ErrBodyNotAllowed":       reflect.ValueOf(&q.ErrBodyNotAllowed),
				"ErrBodyReadAfterClose":   reflect.ValueOf(&q.ErrBodyReadAfterClose),
				"ErrContentLength":        reflect.ValueOf(&q.ErrContentLength),
				"ErrHandlerTimeout":       reflect.ValueOf(&q.ErrHandlerTimeout),
				"ErrHeaderTooLong":        reflect.ValueOf(&q.ErrHeaderTooLong),
				"ErrHijacked":             reflect.ValueOf(&q.ErrHijacked),
				"ErrLineTooLong":          reflect.ValueOf(&q.ErrLineTooLong),
				"ErrMissingBoundary":      reflect.ValueOf(&q.ErrMissingBoundary),
				"ErrMissingContentLength": reflect.ValueOf(&q.ErrMissingContentLength),
				"ErrMissingFile":          reflect.ValueOf(&q.ErrMissingFile),
				"ErrNoCookie":             reflect.ValueOf(&q.ErrNoCookie),
				"ErrNoLocation":           reflect.ValueOf(&q.ErrNoLocation),
				"ErrNotMultipart":         reflect.ValueOf(&q.ErrNotMultipart),
				"ErrNotSupported":         reflect.ValueOf(&q.ErrNotSupported),
				"ErrSchemeMismatch":       reflect.ValueOf(&q.ErrSchemeMismatch),
				"ErrServerClosed":         reflect.ValueOf(&q.ErrServerClosed),
				"ErrShortBody":            reflect.ValueOf(&q.ErrShortBody),
				"ErrSkipAltProtocol":      reflect.ValueOf(&q.ErrSkipAltProtocol),
				"ErrUnexpectedTrailer":    reflect.ValueOf(&q.ErrUnexpectedTrailer),
				"ErrUseLastResponse":      reflect.ValueOf(&q.ErrUseLastResponse),
				"ErrWriteAfterFlush":      reflect.ValueOf(&q.ErrWriteAfterFlush),
				"LocalAddrContextKey":     reflect.ValueOf(&q.LocalAddrContextKey),
				"NoBody":                  reflect.ValueOf(&q.NoBody),
				"ServerContextKey":        reflect.ValueOf(&q.ServerContextKey),
			},
			Funcs: map[string]reflect.Value{
				"AllowQuerySemicolons":     reflect.ValueOf(q.AllowQuerySemicolons),
				"CanonicalHeaderKey":       reflect.ValueOf(q.CanonicalHeaderKey),
				"DetectContentType":        reflect.ValueOf(q.DetectContentType),
				"Error":                    reflect.ValueOf(q.Error),
				"FS":                       reflect.ValueOf(q.FS),
				"FileServer":               reflect.ValueOf(q.FileServer),
				"FileServerFS":             reflect.ValueOf(q.FileServerFS),
				"Get":                      reflect.ValueOf(q.Get),
				"Handle":                   reflect.ValueOf(q.Handle),
				"HandleFunc":               reflect.ValueOf(q.HandleFunc),
				"Head":                     reflect.ValueOf(q.Head),
				"ListenAndServe":           reflect.ValueOf(q.ListenAndServe),
				"ListenAndServeTLS":        reflect.ValueOf(q.ListenAndServeTLS),
				"MaxBytesHandler":          reflect.ValueOf(q.MaxBytesHandler),
				"MaxBytesReader":           reflect.ValueOf(q.MaxBytesReader),
				"NewCrossOriginProtection": reflect.ValueOf(q.NewCrossOriginProtection),
				"NewFileTransport":         reflect.ValueOf(q.NewFileTransport),
				"NewFileTransportFS":       reflect.ValueOf(q.NewFileTransportFS),
				"NewRequest":               reflect.ValueOf(q.NewRequest),
				"NewRequestWithContext":    reflect.ValueOf(q.NewRequestWithContext),
				"NewResponseController":    reflect.ValueOf(q.NewResponseController),
				"NewServeMux":              reflect.ValueOf(q.NewServeMux),
				"NotFound":                 reflect.ValueOf(q.NotFound),
				"NotFoundHandler":          reflect.ValueOf(q.NotFoundHandler),
				"ParseCookie":              reflect.ValueOf(q.ParseCookie),
				"ParseHTTPVersion":         reflect.ValueOf(q.ParseHTTPVersion),
				"ParseSetCookie":           reflect.ValueOf(q.ParseSetCookie),
				"ParseTime":                reflect.ValueOf(q.ParseTime),
				"Post":                     reflect.ValueOf(q.Post),
				"PostForm":                 reflect.ValueOf(q.PostForm),
				"ProxyFromEnvironment":     reflect.ValueOf(q.ProxyFromEnvironment),
				"ProxyURL":                 reflect.ValueOf(q.ProxyURL),
				"ReadRequest":              reflect.ValueOf(q.ReadRequest),
				"ReadResponse":             reflect.ValueOf(q.ReadResponse),
				"Redirect":                 reflect.ValueOf(q.Redirect),
				"RedirectHandler":          reflect.ValueOf(q.RedirectHandler),
				"Serve":                    reflect.ValueOf(q.Serve),
				"ServeContent":             reflect.ValueOf(q.ServeContent),
				"ServeFile":                reflect.ValueOf(q.ServeFile),
				"ServeFileFS":              reflect.ValueOf(q.ServeFileFS),
				"ServeTLS":                 reflect.ValueOf(q.ServeTLS),
				"SetCookie":                reflect.ValueOf(q.SetCookie),
				"StatusText":               reflect.ValueOf(q.StatusText),
				"StripPrefix":              reflect.ValueOf(q.StripPrefix),
				"TimeoutHandler":           reflect.ValueOf(q.TimeoutHandler),
			},
			TypedConsts: map[string]ixgo.TypedConst{
				"SameSiteDefaultMode": {Typ: reflect.TypeOf(q.SameSiteDefaultMode), Value: constant.MakeInt64(int64(q.SameSiteDefaultMode))},
				"SameSiteLaxMode":     {Typ: reflect.TypeOf(q.SameSiteLaxMode), Value: constant.MakeInt64(int64(q.SameSiteLaxMode))},
				"SameSiteNoneMode":    {Typ: reflect.TypeOf(q.SameSiteNoneMode), Value: constant.MakeInt64(int64(q.SameSiteNoneMode))},
				"SameSiteStrictMode":  {Typ: reflect.TypeOf(q.SameSiteStrictMode), Value: constant.MakeInt64(int64(q.SameSiteStrictMode))},
				"StateActive":         {Typ: reflect.TypeOf(q.StateActive), Value: constant.MakeInt64(int64(q.StateActive))},
				"StateClosed":         {Typ: reflect.TypeOf(q.StateClosed), Value: constant.MakeInt64(int64(q.StateClosed))},
				"StateHijacked":       {Typ: reflect.TypeOf(q.StateHijacked), Value: constant.MakeInt64(int64(q.StateHijacked))},
				"StateIdle":           {Typ: reflect.TypeOf(q.StateIdle), Value: constant.MakeInt64(int64(q.StateIdle))},
				"StateNew":            {Typ: reflect.TypeOf(q.StateNew), Value: constant.MakeInt64(int64(q.StateNew))},
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"DefaultMaxHeaderBytes":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DefaultMaxHeaderBytes))},
				"DefaultMaxIdleConnsPerHost":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DefaultMaxIdleConnsPerHost))},
				"MethodConnect":                       {Typ: "untyped string", Value: constant.MakeString(string(q.MethodConnect))},
				"MethodDelete":                        {Typ: "untyped string", Value: constant.MakeString(string(q.MethodDelete))},
				"MethodGet":                           {Typ: "untyped string", Value: constant.MakeString(string(q.MethodGet))},
				"MethodHead":                          {Typ: "untyped string", Value: constant.MakeString(string(q.MethodHead))},
				"MethodOptions":                       {Typ: "untyped string", Value: constant.MakeString(string(q.MethodOptions))},
				"MethodPatch":                         {Typ: "untyped string", Value: constant.MakeString(string(q.MethodPatch))},
				"MethodPost":                          {Typ: "untyped string", Value: constant.MakeString(string(q.MethodPost))},
				"MethodPut":                           {Typ: "untyped string", Value: constant.MakeString(string(q.MethodPut))},
				"MethodTrace":                         {Typ: "untyped string", Value: constant.MakeString(string(q.MethodTrace))},
				"StatusAccepted":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusAccepted))},
				"StatusAlreadyReported":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusAlreadyReported))},
				"StatusBadGateway":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusBadGateway))},
				"StatusBadRequest":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusBadRequest))},
				"StatusConflict":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusConflict))},
				"StatusContinue":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusContinue))},
				"StatusCreated":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusCreated))},
				"StatusEarlyHints":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusEarlyHints))},
				"StatusExpectationFailed":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusExpectationFailed))},
				"StatusFailedDependency":              {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusFailedDependency))},
				"StatusForbidden":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusForbidden))},
				"StatusFound":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusFound))},
				"StatusGatewayTimeout":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusGatewayTimeout))},
				"StatusGone":                          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusGone))},
				"StatusHTTPVersionNotSupported":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusHTTPVersionNotSupported))},
				"StatusIMUsed":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusIMUsed))},
				"StatusInsufficientStorage":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusInsufficientStorage))},
				"StatusInternalServerError":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusInternalServerError))},
				"StatusLengthRequired":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusLengthRequired))},
				"StatusLocked":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusLocked))},
				"StatusLoopDetected":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusLoopDetected))},
				"StatusMethodNotAllowed":              {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusMethodNotAllowed))},
				"StatusMisdirectedRequest":            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusMisdirectedRequest))},
				"StatusMovedPermanently":              {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusMovedPermanently))},
				"StatusMultiStatus":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusMultiStatus))},
				"StatusMultipleChoices":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusMultipleChoices))},
				"StatusNetworkAuthenticationRequired": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNetworkAuthenticationRequired))},
				"StatusNoContent":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNoContent))},
				"StatusNonAuthoritativeInfo":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNonAuthoritativeInfo))},
				"StatusNotAcceptable":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNotAcceptable))},
				"StatusNotExtended":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNotExtended))},
				"StatusNotFound":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNotFound))},
				"StatusNotImplemented":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNotImplemented))},
				"StatusNotModified":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNotModified))},
				"StatusOK":                            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusOK))},
				"StatusPartialContent":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusPartialContent))},
				"StatusPaymentRequired":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusPaymentRequired))},
				"StatusPermanentRedirect":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusPermanentRedirect))},
				"StatusPreconditionFailed":            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusPreconditionFailed))},
				"StatusPreconditionRequired":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusPreconditionRequired))},
				"StatusProcessing":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusProcessing))},
				"StatusProxyAuthRequired":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusProxyAuthRequired))},
				"StatusRequestEntityTooLarge":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusRequestEntityTooLarge))},
				"StatusRequestHeaderFieldsTooLarge":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusRequestHeaderFieldsTooLarge))},
				"StatusRequestTimeout":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusRequestTimeout))},
				"StatusRequestURITooLong":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusRequestURITooLong))},
				"StatusRequestedRangeNotSatisfiable":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusRequestedRangeNotSatisfiable))},
				"StatusResetContent":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusResetContent))},
				"StatusSeeOther":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusSeeOther))},
				"StatusServiceUnavailable":            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusServiceUnavailable))},
				"StatusSwitchingProtocols":            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusSwitchingProtocols))},
				"StatusTeapot":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusTeapot))},
				"StatusTemporaryRedirect":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusTemporaryRedirect))},
				"StatusTooEarly":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusTooEarly))},
				"StatusTooManyRequests":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusTooManyRequests))},
				"StatusUnauthorized":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUnauthorized))},
				"StatusUnavailableForLegalReasons":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUnavailableForLegalReasons))},
				"StatusUnprocessableEntity":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUnprocessableEntity))},
				"StatusUnsupportedMediaType":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUnsupportedMediaType))},
				"StatusUpgradeRequired":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUpgradeRequired))},
				"StatusUseProxy":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUseProxy))},
				"StatusVariantAlsoNegotiates":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusVariantAlsoNegotiates))},
				"TimeFormat":                          {Typ: "untyped string", Value: constant.MakeString(string(q.TimeFormat))},
				"TrailerPrefix":                       {Typ: "untyped string", Value: constant.MakeString(string(q.TrailerPrefix))},
			},
		}
	})
}
