// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.24 && !go1.25
// +build go1.24,!go1.25

package http

import (
	q "net/http"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("net/http", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "http",
			Path: "net/http",
			Deps: map[string]string{
				"bufio":                                  "bufio",
				"bytes":                                  "bytes",
				"compress/gzip":                          "gzip",
				"container/list":                         "list",
				"context":                                "context",
				"crypto/rand":                            "rand",
				"crypto/tls":                             "tls",
				"encoding/base64":                        "base64",
				"encoding/binary":                        "binary",
				"errors":                                 "errors",
				"fmt":                                    "fmt",
				"internal/godebug":                       "godebug",
				"io":                                     "io",
				"io/fs":                                  "fs",
				"log":                                    "log",
				"maps":                                   "maps",
				"math":                                   "math",
				"math/bits":                              "bits",
				"math/rand":                              "rand",
				"mime":                                   "mime",
				"mime/multipart":                         "multipart",
				"net":                                    "net",
				"net/http/httptrace":                     "httptrace",
				"net/http/internal":                      "internal",
				"net/http/internal/ascii":                "ascii",
				"net/textproto":                          "textproto",
				"net/url":                                "url",
				"os":                                     "os",
				"path":                                   "path",
				"path/filepath":                          "filepath",
				"reflect":                                "reflect",
				"runtime":                                "runtime",
				"slices":                                 "slices",
				"sort":                                   "sort",
				"strconv":                                "strconv",
				"strings":                                "strings",
				"sync":                                   "sync",
				"sync/atomic":                            "atomic",
				"time":                                   "time",
				"unicode":                                "unicode",
				"unicode/utf8":                           "utf8",
				"unsafe":                                 "unsafe",
				"vendor/golang.org/x/net/http/httpguts":  "httpguts",
				"vendor/golang.org/x/net/http/httpproxy": "httpproxy",
				"vendor/golang.org/x/net/http2/hpack":    "hpack",
				"vendor/golang.org/x/net/idna":           "idna",
			},
			Interfaces: map[string]reflect.Type{
				"CloseNotifier":  reflect.TypeOf((*q.CloseNotifier)(nil)).Elem(),
				"CookieJar":      reflect.TypeOf((*q.CookieJar)(nil)).Elem(),
				"File":           reflect.TypeOf((*q.File)(nil)).Elem(),
				"FileSystem":     reflect.TypeOf((*q.FileSystem)(nil)).Elem(),
				"Flusher":        reflect.TypeOf((*q.Flusher)(nil)).Elem(),
				"Handler":        reflect.TypeOf((*q.Handler)(nil)).Elem(),
				"Hijacker":       reflect.TypeOf((*q.Hijacker)(nil)).Elem(),
				"Pusher":         reflect.TypeOf((*q.Pusher)(nil)).Elem(),
				"ResponseWriter": reflect.TypeOf((*q.ResponseWriter)(nil)).Elem(),
				"RoundTripper":   reflect.TypeOf((*q.RoundTripper)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Client":             reflect.TypeOf((*q.Client)(nil)).Elem(),
				"ConnState":          reflect.TypeOf((*q.ConnState)(nil)).Elem(),
				"Cookie":             reflect.TypeOf((*q.Cookie)(nil)).Elem(),
				"Dir":                reflect.TypeOf((*q.Dir)(nil)).Elem(),
				"HTTP2Config":        reflect.TypeOf((*q.HTTP2Config)(nil)).Elem(),
				"HandlerFunc":        reflect.TypeOf((*q.HandlerFunc)(nil)).Elem(),
				"Header":             reflect.TypeOf((*q.Header)(nil)).Elem(),
				"MaxBytesError":      reflect.TypeOf((*q.MaxBytesError)(nil)).Elem(),
				"ProtocolError":      reflect.TypeOf((*q.ProtocolError)(nil)).Elem(),
				"Protocols":          reflect.TypeOf((*q.Protocols)(nil)).Elem(),
				"PushOptions":        reflect.TypeOf((*q.PushOptions)(nil)).Elem(),
				"Request":            reflect.TypeOf((*q.Request)(nil)).Elem(),
				"Response":           reflect.TypeOf((*q.Response)(nil)).Elem(),
				"ResponseController": reflect.TypeOf((*q.ResponseController)(nil)).Elem(),
				"SameSite":           reflect.TypeOf((*q.SameSite)(nil)).Elem(),
				"ServeMux":           reflect.TypeOf((*q.ServeMux)(nil)).Elem(),
				"Server":             reflect.TypeOf((*q.Server)(nil)).Elem(),
				"Transport":          reflect.TypeOf((*q.Transport)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]interface{}{
				"DefaultClient":           &q.DefaultClient,
				"DefaultServeMux":         &q.DefaultServeMux,
				"DefaultTransport":        &q.DefaultTransport,
				"ErrAbortHandler":         &q.ErrAbortHandler,
				"ErrBodyNotAllowed":       &q.ErrBodyNotAllowed,
				"ErrBodyReadAfterClose":   &q.ErrBodyReadAfterClose,
				"ErrContentLength":        &q.ErrContentLength,
				"ErrHandlerTimeout":       &q.ErrHandlerTimeout,
				"ErrHeaderTooLong":        &q.ErrHeaderTooLong,
				"ErrHijacked":             &q.ErrHijacked,
				"ErrLineTooLong":          &q.ErrLineTooLong,
				"ErrMissingBoundary":      &q.ErrMissingBoundary,
				"ErrMissingContentLength": &q.ErrMissingContentLength,
				"ErrMissingFile":          &q.ErrMissingFile,
				"ErrNoCookie":             &q.ErrNoCookie,
				"ErrNoLocation":           &q.ErrNoLocation,
				"ErrNotMultipart":         &q.ErrNotMultipart,
				"ErrNotSupported":         &q.ErrNotSupported,
				"ErrSchemeMismatch":       &q.ErrSchemeMismatch,
				"ErrServerClosed":         &q.ErrServerClosed,
				"ErrShortBody":            &q.ErrShortBody,
				"ErrSkipAltProtocol":      &q.ErrSkipAltProtocol,
				"ErrUnexpectedTrailer":    &q.ErrUnexpectedTrailer,
				"ErrUseLastResponse":      &q.ErrUseLastResponse,
				"ErrWriteAfterFlush":      &q.ErrWriteAfterFlush,
				"LocalAddrContextKey":     &q.LocalAddrContextKey,
				"NoBody":                  &q.NoBody,
				"ServerContextKey":        &q.ServerContextKey,
			},
			Funcs: map[string]interface{}{
				"AllowQuerySemicolons":  q.AllowQuerySemicolons,
				"CanonicalHeaderKey":    q.CanonicalHeaderKey,
				"DetectContentType":     q.DetectContentType,
				"Error":                 q.Error,
				"FS":                    q.FS,
				"FileServer":            q.FileServer,
				"FileServerFS":          q.FileServerFS,
				"Get":                   q.Get,
				"Handle":                q.Handle,
				"HandleFunc":            q.HandleFunc,
				"Head":                  q.Head,
				"ListenAndServe":        q.ListenAndServe,
				"ListenAndServeTLS":     q.ListenAndServeTLS,
				"MaxBytesHandler":       q.MaxBytesHandler,
				"MaxBytesReader":        q.MaxBytesReader,
				"NewFileTransport":      q.NewFileTransport,
				"NewFileTransportFS":    q.NewFileTransportFS,
				"NewRequest":            q.NewRequest,
				"NewRequestWithContext": q.NewRequestWithContext,
				"NewResponseController": q.NewResponseController,
				"NewServeMux":           q.NewServeMux,
				"NotFound":              q.NotFound,
				"NotFoundHandler":       q.NotFoundHandler,
				"ParseCookie":           q.ParseCookie,
				"ParseHTTPVersion":      q.ParseHTTPVersion,
				"ParseSetCookie":        q.ParseSetCookie,
				"ParseTime":             q.ParseTime,
				"Post":                  q.Post,
				"PostForm":              q.PostForm,
				"ProxyFromEnvironment":  q.ProxyFromEnvironment,
				"ProxyURL":              q.ProxyURL,
				"ReadRequest":           q.ReadRequest,
				"ReadResponse":          q.ReadResponse,
				"Redirect":              q.Redirect,
				"RedirectHandler":       q.RedirectHandler,
				"Serve":                 q.Serve,
				"ServeContent":          q.ServeContent,
				"ServeFile":             q.ServeFile,
				"ServeFileFS":           q.ServeFileFS,
				"ServeTLS":              q.ServeTLS,
				"SetCookie":             q.SetCookie,
				"StatusText":            q.StatusText,
				"StripPrefix":           q.StripPrefix,
				"TimeoutHandler":        q.TimeoutHandler,
			},
			TypedConsts: map[string]interface{}{
				"SameSiteDefaultMode": q.SameSiteDefaultMode,
				"SameSiteLaxMode":     q.SameSiteLaxMode,
				"SameSiteNoneMode":    q.SameSiteNoneMode,
				"SameSiteStrictMode":  q.SameSiteStrictMode,
				"StateActive":         q.StateActive,
				"StateClosed":         q.StateClosed,
				"StateHijacked":       q.StateHijacked,
				"StateIdle":           q.StateIdle,
				"StateNew":            q.StateNew,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"DefaultMaxHeaderBytes":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DefaultMaxHeaderBytes))},
				"DefaultMaxIdleConnsPerHost":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.DefaultMaxIdleConnsPerHost))},
				"MethodConnect":                       {Typ: "untyped string", Value: constant.MakeString(string(q.MethodConnect))},
				"MethodDelete":                        {Typ: "untyped string", Value: constant.MakeString(string(q.MethodDelete))},
				"MethodGet":                           {Typ: "untyped string", Value: constant.MakeString(string(q.MethodGet))},
				"MethodHead":                          {Typ: "untyped string", Value: constant.MakeString(string(q.MethodHead))},
				"MethodOptions":                       {Typ: "untyped string", Value: constant.MakeString(string(q.MethodOptions))},
				"MethodPatch":                         {Typ: "untyped string", Value: constant.MakeString(string(q.MethodPatch))},
				"MethodPost":                          {Typ: "untyped string", Value: constant.MakeString(string(q.MethodPost))},
				"MethodPut":                           {Typ: "untyped string", Value: constant.MakeString(string(q.MethodPut))},
				"MethodTrace":                         {Typ: "untyped string", Value: constant.MakeString(string(q.MethodTrace))},
				"StatusAccepted":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusAccepted))},
				"StatusAlreadyReported":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusAlreadyReported))},
				"StatusBadGateway":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusBadGateway))},
				"StatusBadRequest":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusBadRequest))},
				"StatusConflict":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusConflict))},
				"StatusContinue":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusContinue))},
				"StatusCreated":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusCreated))},
				"StatusEarlyHints":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusEarlyHints))},
				"StatusExpectationFailed":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusExpectationFailed))},
				"StatusFailedDependency":              {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusFailedDependency))},
				"StatusForbidden":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusForbidden))},
				"StatusFound":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusFound))},
				"StatusGatewayTimeout":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusGatewayTimeout))},
				"StatusGone":                          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusGone))},
				"StatusHTTPVersionNotSupported":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusHTTPVersionNotSupported))},
				"StatusIMUsed":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusIMUsed))},
				"StatusInsufficientStorage":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusInsufficientStorage))},
				"StatusInternalServerError":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusInternalServerError))},
				"StatusLengthRequired":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusLengthRequired))},
				"StatusLocked":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusLocked))},
				"StatusLoopDetected":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusLoopDetected))},
				"StatusMethodNotAllowed":              {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusMethodNotAllowed))},
				"StatusMisdirectedRequest":            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusMisdirectedRequest))},
				"StatusMovedPermanently":              {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusMovedPermanently))},
				"StatusMultiStatus":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusMultiStatus))},
				"StatusMultipleChoices":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusMultipleChoices))},
				"StatusNetworkAuthenticationRequired": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNetworkAuthenticationRequired))},
				"StatusNoContent":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNoContent))},
				"StatusNonAuthoritativeInfo":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNonAuthoritativeInfo))},
				"StatusNotAcceptable":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNotAcceptable))},
				"StatusNotExtended":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNotExtended))},
				"StatusNotFound":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNotFound))},
				"StatusNotImplemented":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNotImplemented))},
				"StatusNotModified":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusNotModified))},
				"StatusOK":                            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusOK))},
				"StatusPartialContent":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusPartialContent))},
				"StatusPaymentRequired":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusPaymentRequired))},
				"StatusPermanentRedirect":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusPermanentRedirect))},
				"StatusPreconditionFailed":            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusPreconditionFailed))},
				"StatusPreconditionRequired":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusPreconditionRequired))},
				"StatusProcessing":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusProcessing))},
				"StatusProxyAuthRequired":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusProxyAuthRequired))},
				"StatusRequestEntityTooLarge":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusRequestEntityTooLarge))},
				"StatusRequestHeaderFieldsTooLarge":   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusRequestHeaderFieldsTooLarge))},
				"StatusRequestTimeout":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusRequestTimeout))},
				"StatusRequestURITooLong":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusRequestURITooLong))},
				"StatusRequestedRangeNotSatisfiable":  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusRequestedRangeNotSatisfiable))},
				"StatusResetContent":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusResetContent))},
				"StatusSeeOther":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusSeeOther))},
				"StatusServiceUnavailable":            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusServiceUnavailable))},
				"StatusSwitchingProtocols":            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusSwitchingProtocols))},
				"StatusTeapot":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusTeapot))},
				"StatusTemporaryRedirect":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusTemporaryRedirect))},
				"StatusTooEarly":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusTooEarly))},
				"StatusTooManyRequests":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusTooManyRequests))},
				"StatusUnauthorized":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUnauthorized))},
				"StatusUnavailableForLegalReasons":    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUnavailableForLegalReasons))},
				"StatusUnprocessableEntity":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUnprocessableEntity))},
				"StatusUnsupportedMediaType":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUnsupportedMediaType))},
				"StatusUpgradeRequired":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUpgradeRequired))},
				"StatusUseProxy":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusUseProxy))},
				"StatusVariantAlsoNegotiates":         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.StatusVariantAlsoNegotiates))},
				"TimeFormat":                          {Typ: "untyped string", Value: constant.MakeString(string(q.TimeFormat))},
				"TrailerPrefix":                       {Typ: "untyped string", Value: constant.MakeString(string(q.TrailerPrefix))},
			},
		}
	})
}
