// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.26
// +build go1.26

package net

import (
	q "net"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("net", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "net",
			Path: "net",
			Deps: map[string]string{
				"cmp":                                    "cmp",
				"context":                                "context",
				"errors":                                 "errors",
				"internal/bytealg":                       "bytealg",
				"internal/godebug":                       "godebug",
				"internal/nettrace":                      "nettrace",
				"internal/poll":                          "poll",
				"internal/routebsd":                      "routebsd",
				"internal/singleflight":                  "singleflight",
				"internal/strconv":                       "strconv",
				"internal/stringslite":                   "stringslite",
				"internal/syscall/unix":                  "unix",
				"io":                                     "io",
				"io/fs":                                  "fs",
				"net/netip":                              "netip",
				"os":                                     "os",
				"runtime":                                "runtime",
				"slices":                                 "slices",
				"sync":                                   "sync",
				"sync/atomic":                            "atomic",
				"syscall":                                "syscall",
				"time":                                   "time",
				"unsafe":                                 "unsafe",
				"vendor/golang.org/x/net/dns/dnsmessage": "dnsmessage",
			},
			Interfaces: map[string]reflect.Type{
				"Addr":       reflect.TypeOf((*q.Addr)(nil)).Elem(),
				"Conn":       reflect.TypeOf((*q.Conn)(nil)).Elem(),
				"Error":      reflect.TypeOf((*q.Error)(nil)).Elem(),
				"Listener":   reflect.TypeOf((*q.Listener)(nil)).Elem(),
				"PacketConn": reflect.TypeOf((*q.PacketConn)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"AddrError":           reflect.TypeOf((*q.AddrError)(nil)).Elem(),
				"Buffers":             reflect.TypeOf((*q.Buffers)(nil)).Elem(),
				"DNSConfigError":      reflect.TypeOf((*q.DNSConfigError)(nil)).Elem(),
				"DNSError":            reflect.TypeOf((*q.DNSError)(nil)).Elem(),
				"Dialer":              reflect.TypeOf((*q.Dialer)(nil)).Elem(),
				"Flags":               reflect.TypeOf((*q.Flags)(nil)).Elem(),
				"HardwareAddr":        reflect.TypeOf((*q.HardwareAddr)(nil)).Elem(),
				"IP":                  reflect.TypeOf((*q.IP)(nil)).Elem(),
				"IPAddr":              reflect.TypeOf((*q.IPAddr)(nil)).Elem(),
				"IPConn":              reflect.TypeOf((*q.IPConn)(nil)).Elem(),
				"IPMask":              reflect.TypeOf((*q.IPMask)(nil)).Elem(),
				"IPNet":               reflect.TypeOf((*q.IPNet)(nil)).Elem(),
				"Interface":           reflect.TypeOf((*q.Interface)(nil)).Elem(),
				"InvalidAddrError":    reflect.TypeOf((*q.InvalidAddrError)(nil)).Elem(),
				"KeepAliveConfig":     reflect.TypeOf((*q.KeepAliveConfig)(nil)).Elem(),
				"ListenConfig":        reflect.TypeOf((*q.ListenConfig)(nil)).Elem(),
				"MX":                  reflect.TypeOf((*q.MX)(nil)).Elem(),
				"NS":                  reflect.TypeOf((*q.NS)(nil)).Elem(),
				"OpError":             reflect.TypeOf((*q.OpError)(nil)).Elem(),
				"ParseError":          reflect.TypeOf((*q.ParseError)(nil)).Elem(),
				"Resolver":            reflect.TypeOf((*q.Resolver)(nil)).Elem(),
				"SRV":                 reflect.TypeOf((*q.SRV)(nil)).Elem(),
				"TCPAddr":             reflect.TypeOf((*q.TCPAddr)(nil)).Elem(),
				"TCPConn":             reflect.TypeOf((*q.TCPConn)(nil)).Elem(),
				"TCPListener":         reflect.TypeOf((*q.TCPListener)(nil)).Elem(),
				"UDPAddr":             reflect.TypeOf((*q.UDPAddr)(nil)).Elem(),
				"UDPConn":             reflect.TypeOf((*q.UDPConn)(nil)).Elem(),
				"UnixAddr":            reflect.TypeOf((*q.UnixAddr)(nil)).Elem(),
				"UnixConn":            reflect.TypeOf((*q.UnixConn)(nil)).Elem(),
				"UnixListener":        reflect.TypeOf((*q.UnixListener)(nil)).Elem(),
				"UnknownNetworkError": reflect.TypeOf((*q.UnknownNetworkError)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]interface{}{
				"DefaultResolver":            &q.DefaultResolver,
				"ErrClosed":                  &q.ErrClosed,
				"ErrWriteToConnected":        &q.ErrWriteToConnected,
				"IPv4allrouter":              &q.IPv4allrouter,
				"IPv4allsys":                 &q.IPv4allsys,
				"IPv4bcast":                  &q.IPv4bcast,
				"IPv4zero":                   &q.IPv4zero,
				"IPv6interfacelocalallnodes": &q.IPv6interfacelocalallnodes,
				"IPv6linklocalallnodes":      &q.IPv6linklocalallnodes,
				"IPv6linklocalallrouters":    &q.IPv6linklocalallrouters,
				"IPv6loopback":               &q.IPv6loopback,
				"IPv6unspecified":            &q.IPv6unspecified,
				"IPv6zero":                   &q.IPv6zero,
			},
			Funcs: map[string]interface{}{
				"CIDRMask":            q.CIDRMask,
				"Dial":                q.Dial,
				"DialIP":              q.DialIP,
				"DialTCP":             q.DialTCP,
				"DialTimeout":         q.DialTimeout,
				"DialUDP":             q.DialUDP,
				"DialUnix":            q.DialUnix,
				"FileConn":            q.FileConn,
				"FileListener":        q.FileListener,
				"FilePacketConn":      q.FilePacketConn,
				"IPv4":                q.IPv4,
				"IPv4Mask":            q.IPv4Mask,
				"InterfaceAddrs":      q.InterfaceAddrs,
				"InterfaceByIndex":    q.InterfaceByIndex,
				"InterfaceByName":     q.InterfaceByName,
				"Interfaces":          q.Interfaces,
				"JoinHostPort":        q.JoinHostPort,
				"Listen":              q.Listen,
				"ListenIP":            q.ListenIP,
				"ListenMulticastUDP":  q.ListenMulticastUDP,
				"ListenPacket":        q.ListenPacket,
				"ListenTCP":           q.ListenTCP,
				"ListenUDP":           q.ListenUDP,
				"ListenUnix":          q.ListenUnix,
				"ListenUnixgram":      q.ListenUnixgram,
				"LookupAddr":          q.LookupAddr,
				"LookupCNAME":         q.LookupCNAME,
				"LookupHost":          q.LookupHost,
				"LookupIP":            q.LookupIP,
				"LookupMX":            q.LookupMX,
				"LookupNS":            q.LookupNS,
				"LookupPort":          q.LookupPort,
				"LookupSRV":           q.LookupSRV,
				"LookupTXT":           q.LookupTXT,
				"ParseCIDR":           q.ParseCIDR,
				"ParseIP":             q.ParseIP,
				"ParseMAC":            q.ParseMAC,
				"Pipe":                q.Pipe,
				"ResolveIPAddr":       q.ResolveIPAddr,
				"ResolveTCPAddr":      q.ResolveTCPAddr,
				"ResolveUDPAddr":      q.ResolveUDPAddr,
				"ResolveUnixAddr":     q.ResolveUnixAddr,
				"SplitHostPort":       q.SplitHostPort,
				"TCPAddrFromAddrPort": q.TCPAddrFromAddrPort,
				"UDPAddrFromAddrPort": q.UDPAddrFromAddrPort,
			},
			TypedConsts: map[string]interface{}{
				"FlagBroadcast":    q.FlagBroadcast,
				"FlagLoopback":     q.FlagLoopback,
				"FlagMulticast":    q.FlagMulticast,
				"FlagPointToPoint": q.FlagPointToPoint,
				"FlagRunning":      q.FlagRunning,
				"FlagUp":           q.FlagUp,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"IPv4len": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPv4len))},
				"IPv6len": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IPv6len))},
			},
		}
	})
}
