// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.24 && !go1.25
// +build go1.24,!go1.25

package types

import (
	q "go/types"

	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("go/types", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "types",
			Path: "go/types",
			Deps: map[string]string{
				"bytes":                 "bytes",
				"cmp":                   "cmp",
				"container/heap":        "heap",
				"errors":                "errors",
				"fmt":                   "fmt",
				"go/ast":                "ast",
				"go/constant":           "constant",
				"go/parser":             "parser",
				"go/token":              "token",
				"go/version":            "version",
				"internal/buildcfg":     "buildcfg",
				"internal/godebug":      "godebug",
				"internal/goversion":    "goversion",
				"internal/types/errors": "errors",
				"io":                    "io",
				"iter":                  "iter",
				"math":                  "math",
				"path/filepath":         "filepath",
				"runtime":               "runtime",
				"slices":                "slices",
				"sort":                  "sort",
				"strconv":               "strconv",
				"strings":               "strings",
				"sync":                  "sync",
				"sync/atomic":           "atomic",
				"unicode":               "unicode",
				"unicode/utf8":          "utf8",
				"unsafe":                "unsafe",
			},
			Interfaces: map[string]reflect.Type{
				"Importer":     reflect.TypeOf((*q.Importer)(nil)).Elem(),
				"ImporterFrom": reflect.TypeOf((*q.ImporterFrom)(nil)).Elem(),
				"Object":       reflect.TypeOf((*q.Object)(nil)).Elem(),
				"Sizes":        reflect.TypeOf((*q.Sizes)(nil)).Elem(),
				"Type":         reflect.TypeOf((*q.Type)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Alias":         reflect.TypeOf((*q.Alias)(nil)).Elem(),
				"ArgumentError": reflect.TypeOf((*q.ArgumentError)(nil)).Elem(),
				"Array":         reflect.TypeOf((*q.Array)(nil)).Elem(),
				"Basic":         reflect.TypeOf((*q.Basic)(nil)).Elem(),
				"BasicInfo":     reflect.TypeOf((*q.BasicInfo)(nil)).Elem(),
				"BasicKind":     reflect.TypeOf((*q.BasicKind)(nil)).Elem(),
				"Builtin":       reflect.TypeOf((*q.Builtin)(nil)).Elem(),
				"Chan":          reflect.TypeOf((*q.Chan)(nil)).Elem(),
				"ChanDir":       reflect.TypeOf((*q.ChanDir)(nil)).Elem(),
				"Checker":       reflect.TypeOf((*q.Checker)(nil)).Elem(),
				"Config":        reflect.TypeOf((*q.Config)(nil)).Elem(),
				"Const":         reflect.TypeOf((*q.Const)(nil)).Elem(),
				"Context":       reflect.TypeOf((*q.Context)(nil)).Elem(),
				"Error":         reflect.TypeOf((*q.Error)(nil)).Elem(),
				"Func":          reflect.TypeOf((*q.Func)(nil)).Elem(),
				"ImportMode":    reflect.TypeOf((*q.ImportMode)(nil)).Elem(),
				"Info":          reflect.TypeOf((*q.Info)(nil)).Elem(),
				"Initializer":   reflect.TypeOf((*q.Initializer)(nil)).Elem(),
				"Instance":      reflect.TypeOf((*q.Instance)(nil)).Elem(),
				"Interface":     reflect.TypeOf((*q.Interface)(nil)).Elem(),
				"Label":         reflect.TypeOf((*q.Label)(nil)).Elem(),
				"Map":           reflect.TypeOf((*q.Map)(nil)).Elem(),
				"MethodSet":     reflect.TypeOf((*q.MethodSet)(nil)).Elem(),
				"Named":         reflect.TypeOf((*q.Named)(nil)).Elem(),
				"Nil":           reflect.TypeOf((*q.Nil)(nil)).Elem(),
				"Package":       reflect.TypeOf((*q.Package)(nil)).Elem(),
				"PkgName":       reflect.TypeOf((*q.PkgName)(nil)).Elem(),
				"Pointer":       reflect.TypeOf((*q.Pointer)(nil)).Elem(),
				"Qualifier":     reflect.TypeOf((*q.Qualifier)(nil)).Elem(),
				"Scope":         reflect.TypeOf((*q.Scope)(nil)).Elem(),
				"Selection":     reflect.TypeOf((*q.Selection)(nil)).Elem(),
				"SelectionKind": reflect.TypeOf((*q.SelectionKind)(nil)).Elem(),
				"Signature":     reflect.TypeOf((*q.Signature)(nil)).Elem(),
				"Slice":         reflect.TypeOf((*q.Slice)(nil)).Elem(),
				"StdSizes":      reflect.TypeOf((*q.StdSizes)(nil)).Elem(),
				"Struct":        reflect.TypeOf((*q.Struct)(nil)).Elem(),
				"Term":          reflect.TypeOf((*q.Term)(nil)).Elem(),
				"Tuple":         reflect.TypeOf((*q.Tuple)(nil)).Elem(),
				"TypeAndValue":  reflect.TypeOf((*q.TypeAndValue)(nil)).Elem(),
				"TypeList":      reflect.TypeOf((*q.TypeList)(nil)).Elem(),
				"TypeName":      reflect.TypeOf((*q.TypeName)(nil)).Elem(),
				"TypeParam":     reflect.TypeOf((*q.TypeParam)(nil)).Elem(),
				"TypeParamList": reflect.TypeOf((*q.TypeParamList)(nil)).Elem(),
				"Union":         reflect.TypeOf((*q.Union)(nil)).Elem(),
				"Var":           reflect.TypeOf((*q.Var)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]interface{}{
				"Typ":      &q.Typ,
				"Universe": &q.Universe,
				"Unsafe":   &q.Unsafe,
			},
			Funcs: map[string]interface{}{
				"AssertableTo":            q.AssertableTo,
				"AssignableTo":            q.AssignableTo,
				"CheckExpr":               q.CheckExpr,
				"Comparable":              q.Comparable,
				"ConvertibleTo":           q.ConvertibleTo,
				"DefPredeclaredTestFuncs": q.DefPredeclaredTestFuncs,
				"Default":                 q.Default,
				"Eval":                    q.Eval,
				"ExprString":              q.ExprString,
				"Id":                      q.Id,
				"Identical":               q.Identical,
				"IdenticalIgnoreTags":     q.IdenticalIgnoreTags,
				"Implements":              q.Implements,
				"Instantiate":             q.Instantiate,
				"IsInterface":             q.IsInterface,
				"LookupFieldOrMethod":     q.LookupFieldOrMethod,
				"MissingMethod":           q.MissingMethod,
				"NewAlias":                q.NewAlias,
				"NewArray":                q.NewArray,
				"NewChan":                 q.NewChan,
				"NewChecker":              q.NewChecker,
				"NewConst":                q.NewConst,
				"NewContext":              q.NewContext,
				"NewField":                q.NewField,
				"NewFunc":                 q.NewFunc,
				"NewInterface":            q.NewInterface,
				"NewInterfaceType":        q.NewInterfaceType,
				"NewLabel":                q.NewLabel,
				"NewMap":                  q.NewMap,
				"NewMethodSet":            q.NewMethodSet,
				"NewNamed":                q.NewNamed,
				"NewPackage":              q.NewPackage,
				"NewParam":                q.NewParam,
				"NewPkgName":              q.NewPkgName,
				"NewPointer":              q.NewPointer,
				"NewScope":                q.NewScope,
				"NewSignature":            q.NewSignature,
				"NewSignatureType":        q.NewSignatureType,
				"NewSlice":                q.NewSlice,
				"NewStruct":               q.NewStruct,
				"NewTerm":                 q.NewTerm,
				"NewTuple":                q.NewTuple,
				"NewTypeName":             q.NewTypeName,
				"NewTypeParam":            q.NewTypeParam,
				"NewUnion":                q.NewUnion,
				"NewVar":                  q.NewVar,
				"ObjectString":            q.ObjectString,
				"RelativeTo":              q.RelativeTo,
				"Satisfies":               q.Satisfies,
				"SelectionString":         q.SelectionString,
				"SizesFor":                q.SizesFor,
				"TypeString":              q.TypeString,
				"Unalias":                 q.Unalias,
				"WriteExpr":               q.WriteExpr,
				"WriteSignature":          q.WriteSignature,
				"WriteType":               q.WriteType,
			},
			TypedConsts: map[string]interface{}{
				"Bool":           q.Bool,
				"Byte":           q.Byte,
				"Complex128":     q.Complex128,
				"Complex64":      q.Complex64,
				"FieldVal":       q.FieldVal,
				"Float32":        q.Float32,
				"Float64":        q.Float64,
				"Int":            q.Int,
				"Int16":          q.Int16,
				"Int32":          q.Int32,
				"Int64":          q.Int64,
				"Int8":           q.Int8,
				"Invalid":        q.Invalid,
				"IsBoolean":      q.IsBoolean,
				"IsComplex":      q.IsComplex,
				"IsConstType":    q.IsConstType,
				"IsFloat":        q.IsFloat,
				"IsInteger":      q.IsInteger,
				"IsNumeric":      q.IsNumeric,
				"IsOrdered":      q.IsOrdered,
				"IsString":       q.IsString,
				"IsUnsigned":     q.IsUnsigned,
				"IsUntyped":      q.IsUntyped,
				"MethodExpr":     q.MethodExpr,
				"MethodVal":      q.MethodVal,
				"RecvOnly":       q.RecvOnly,
				"Rune":           q.Rune,
				"SendOnly":       q.SendOnly,
				"SendRecv":       q.SendRecv,
				"String":         q.String,
				"Uint":           q.Uint,
				"Uint16":         q.Uint16,
				"Uint32":         q.Uint32,
				"Uint64":         q.Uint64,
				"Uint8":          q.Uint8,
				"Uintptr":        q.Uintptr,
				"UnsafePointer":  q.UnsafePointer,
				"UntypedBool":    q.UntypedBool,
				"UntypedComplex": q.UntypedComplex,
				"UntypedFloat":   q.UntypedFloat,
				"UntypedInt":     q.UntypedInt,
				"UntypedNil":     q.UntypedNil,
				"UntypedRune":    q.UntypedRune,
				"UntypedString":  q.UntypedString,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{},
		}
	})
}
