// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.24 && !go1.25
// +build go1.24,!go1.25

package types

import (
	q "go/types"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackageLazy("go/types", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "types",
			Path: "go/types",
			Deps: map[string]string{
				"bytes":                 "bytes",
				"cmp":                   "cmp",
				"container/heap":        "heap",
				"errors":                "errors",
				"fmt":                   "fmt",
				"go/ast":                "ast",
				"go/constant":           "constant",
				"go/parser":             "parser",
				"go/token":              "token",
				"go/version":            "version",
				"internal/buildcfg":     "buildcfg",
				"internal/godebug":      "godebug",
				"internal/goversion":    "goversion",
				"internal/types/errors": "errors",
				"io":                    "io",
				"iter":                  "iter",
				"math":                  "math",
				"path/filepath":         "filepath",
				"runtime":               "runtime",
				"slices":                "slices",
				"sort":                  "sort",
				"strconv":               "strconv",
				"strings":               "strings",
				"sync":                  "sync",
				"sync/atomic":           "atomic",
				"unicode":               "unicode",
				"unicode/utf8":          "utf8",
				"unsafe":                "unsafe",
			},
			Interfaces: map[string]reflect.Type{
				"Importer":     reflect.TypeOf((*q.Importer)(nil)).Elem(),
				"ImporterFrom": reflect.TypeOf((*q.ImporterFrom)(nil)).Elem(),
				"Object":       reflect.TypeOf((*q.Object)(nil)).Elem(),
				"Sizes":        reflect.TypeOf((*q.Sizes)(nil)).Elem(),
				"Type":         reflect.TypeOf((*q.Type)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Alias":         reflect.TypeOf((*q.Alias)(nil)).Elem(),
				"ArgumentError": reflect.TypeOf((*q.ArgumentError)(nil)).Elem(),
				"Array":         reflect.TypeOf((*q.Array)(nil)).Elem(),
				"Basic":         reflect.TypeOf((*q.Basic)(nil)).Elem(),
				"BasicInfo":     reflect.TypeOf((*q.BasicInfo)(nil)).Elem(),
				"BasicKind":     reflect.TypeOf((*q.BasicKind)(nil)).Elem(),
				"Builtin":       reflect.TypeOf((*q.Builtin)(nil)).Elem(),
				"Chan":          reflect.TypeOf((*q.Chan)(nil)).Elem(),
				"ChanDir":       reflect.TypeOf((*q.ChanDir)(nil)).Elem(),
				"Checker":       reflect.TypeOf((*q.Checker)(nil)).Elem(),
				"Config":        reflect.TypeOf((*q.Config)(nil)).Elem(),
				"Const":         reflect.TypeOf((*q.Const)(nil)).Elem(),
				"Context":       reflect.TypeOf((*q.Context)(nil)).Elem(),
				"Error":         reflect.TypeOf((*q.Error)(nil)).Elem(),
				"Func":          reflect.TypeOf((*q.Func)(nil)).Elem(),
				"ImportMode":    reflect.TypeOf((*q.ImportMode)(nil)).Elem(),
				"Info":          reflect.TypeOf((*q.Info)(nil)).Elem(),
				"Initializer":   reflect.TypeOf((*q.Initializer)(nil)).Elem(),
				"Instance":      reflect.TypeOf((*q.Instance)(nil)).Elem(),
				"Interface":     reflect.TypeOf((*q.Interface)(nil)).Elem(),
				"Label":         reflect.TypeOf((*q.Label)(nil)).Elem(),
				"Map":           reflect.TypeOf((*q.Map)(nil)).Elem(),
				"MethodSet":     reflect.TypeOf((*q.MethodSet)(nil)).Elem(),
				"Named":         reflect.TypeOf((*q.Named)(nil)).Elem(),
				"Nil":           reflect.TypeOf((*q.Nil)(nil)).Elem(),
				"Package":       reflect.TypeOf((*q.Package)(nil)).Elem(),
				"PkgName":       reflect.TypeOf((*q.PkgName)(nil)).Elem(),
				"Pointer":       reflect.TypeOf((*q.Pointer)(nil)).Elem(),
				"Qualifier":     reflect.TypeOf((*q.Qualifier)(nil)).Elem(),
				"Scope":         reflect.TypeOf((*q.Scope)(nil)).Elem(),
				"Selection":     reflect.TypeOf((*q.Selection)(nil)).Elem(),
				"SelectionKind": reflect.TypeOf((*q.SelectionKind)(nil)).Elem(),
				"Signature":     reflect.TypeOf((*q.Signature)(nil)).Elem(),
				"Slice":         reflect.TypeOf((*q.Slice)(nil)).Elem(),
				"StdSizes":      reflect.TypeOf((*q.StdSizes)(nil)).Elem(),
				"Struct":        reflect.TypeOf((*q.Struct)(nil)).Elem(),
				"Term":          reflect.TypeOf((*q.Term)(nil)).Elem(),
				"Tuple":         reflect.TypeOf((*q.Tuple)(nil)).Elem(),
				"TypeAndValue":  reflect.TypeOf((*q.TypeAndValue)(nil)).Elem(),
				"TypeList":      reflect.TypeOf((*q.TypeList)(nil)).Elem(),
				"TypeName":      reflect.TypeOf((*q.TypeName)(nil)).Elem(),
				"TypeParam":     reflect.TypeOf((*q.TypeParam)(nil)).Elem(),
				"TypeParamList": reflect.TypeOf((*q.TypeParamList)(nil)).Elem(),
				"Union":         reflect.TypeOf((*q.Union)(nil)).Elem(),
				"Var":           reflect.TypeOf((*q.Var)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]reflect.Value{
				"Typ":      reflect.ValueOf(&q.Typ),
				"Universe": reflect.ValueOf(&q.Universe),
				"Unsafe":   reflect.ValueOf(&q.Unsafe),
			},
			Funcs: map[string]reflect.Value{
				"AssertableTo":            reflect.ValueOf(q.AssertableTo),
				"AssignableTo":            reflect.ValueOf(q.AssignableTo),
				"CheckExpr":               reflect.ValueOf(q.CheckExpr),
				"Comparable":              reflect.ValueOf(q.Comparable),
				"ConvertibleTo":           reflect.ValueOf(q.ConvertibleTo),
				"DefPredeclaredTestFuncs": reflect.ValueOf(q.DefPredeclaredTestFuncs),
				"Default":                 reflect.ValueOf(q.Default),
				"Eval":                    reflect.ValueOf(q.Eval),
				"ExprString":              reflect.ValueOf(q.ExprString),
				"Id":                      reflect.ValueOf(q.Id),
				"Identical":               reflect.ValueOf(q.Identical),
				"IdenticalIgnoreTags":     reflect.ValueOf(q.IdenticalIgnoreTags),
				"Implements":              reflect.ValueOf(q.Implements),
				"Instantiate":             reflect.ValueOf(q.Instantiate),
				"IsInterface":             reflect.ValueOf(q.IsInterface),
				"LookupFieldOrMethod":     reflect.ValueOf(q.LookupFieldOrMethod),
				"MissingMethod":           reflect.ValueOf(q.MissingMethod),
				"NewAlias":                reflect.ValueOf(q.NewAlias),
				"NewArray":                reflect.ValueOf(q.NewArray),
				"NewChan":                 reflect.ValueOf(q.NewChan),
				"NewChecker":              reflect.ValueOf(q.NewChecker),
				"NewConst":                reflect.ValueOf(q.NewConst),
				"NewContext":              reflect.ValueOf(q.NewContext),
				"NewField":                reflect.ValueOf(q.NewField),
				"NewFunc":                 reflect.ValueOf(q.NewFunc),
				"NewInterface":            reflect.ValueOf(q.NewInterface),
				"NewInterfaceType":        reflect.ValueOf(q.NewInterfaceType),
				"NewLabel":                reflect.ValueOf(q.NewLabel),
				"NewMap":                  reflect.ValueOf(q.NewMap),
				"NewMethodSet":            reflect.ValueOf(q.NewMethodSet),
				"NewNamed":                reflect.ValueOf(q.NewNamed),
				"NewPackage":              reflect.ValueOf(q.NewPackage),
				"NewParam":                reflect.ValueOf(q.NewParam),
				"NewPkgName":              reflect.ValueOf(q.NewPkgName),
				"NewPointer":              reflect.ValueOf(q.NewPointer),
				"NewScope":                reflect.ValueOf(q.NewScope),
				"NewSignature":            reflect.ValueOf(q.NewSignature),
				"NewSignatureType":        reflect.ValueOf(q.NewSignatureType),
				"NewSlice":                reflect.ValueOf(q.NewSlice),
				"NewStruct":               reflect.ValueOf(q.NewStruct),
				"NewTerm":                 reflect.ValueOf(q.NewTerm),
				"NewTuple":                reflect.ValueOf(q.NewTuple),
				"NewTypeName":             reflect.ValueOf(q.NewTypeName),
				"NewTypeParam":            reflect.ValueOf(q.NewTypeParam),
				"NewUnion":                reflect.ValueOf(q.NewUnion),
				"NewVar":                  reflect.ValueOf(q.NewVar),
				"ObjectString":            reflect.ValueOf(q.ObjectString),
				"RelativeTo":              reflect.ValueOf(q.RelativeTo),
				"Satisfies":               reflect.ValueOf(q.Satisfies),
				"SelectionString":         reflect.ValueOf(q.SelectionString),
				"SizesFor":                reflect.ValueOf(q.SizesFor),
				"TypeString":              reflect.ValueOf(q.TypeString),
				"Unalias":                 reflect.ValueOf(q.Unalias),
				"WriteExpr":               reflect.ValueOf(q.WriteExpr),
				"WriteSignature":          reflect.ValueOf(q.WriteSignature),
				"WriteType":               reflect.ValueOf(q.WriteType),
			},
			TypedConsts: map[string]ixgo.TypedConst{
				"Bool":           {Typ: reflect.TypeOf(q.Bool), Value: constant.MakeInt64(int64(q.Bool))},
				"Byte":           {Typ: reflect.TypeOf(q.Byte), Value: constant.MakeInt64(int64(q.Byte))},
				"Complex128":     {Typ: reflect.TypeOf(q.Complex128), Value: constant.MakeInt64(int64(q.Complex128))},
				"Complex64":      {Typ: reflect.TypeOf(q.Complex64), Value: constant.MakeInt64(int64(q.Complex64))},
				"FieldVal":       {Typ: reflect.TypeOf(q.FieldVal), Value: constant.MakeInt64(int64(q.FieldVal))},
				"Float32":        {Typ: reflect.TypeOf(q.Float32), Value: constant.MakeInt64(int64(q.Float32))},
				"Float64":        {Typ: reflect.TypeOf(q.Float64), Value: constant.MakeInt64(int64(q.Float64))},
				"Int":            {Typ: reflect.TypeOf(q.Int), Value: constant.MakeInt64(int64(q.Int))},
				"Int16":          {Typ: reflect.TypeOf(q.Int16), Value: constant.MakeInt64(int64(q.Int16))},
				"Int32":          {Typ: reflect.TypeOf(q.Int32), Value: constant.MakeInt64(int64(q.Int32))},
				"Int64":          {Typ: reflect.TypeOf(q.Int64), Value: constant.MakeInt64(int64(q.Int64))},
				"Int8":           {Typ: reflect.TypeOf(q.Int8), Value: constant.MakeInt64(int64(q.Int8))},
				"Invalid":        {Typ: reflect.TypeOf(q.Invalid), Value: constant.MakeInt64(int64(q.Invalid))},
				"IsBoolean":      {Typ: reflect.TypeOf(q.IsBoolean), Value: constant.MakeInt64(int64(q.IsBoolean))},
				"IsComplex":      {Typ: reflect.TypeOf(q.IsComplex), Value: constant.MakeInt64(int64(q.IsComplex))},
				"IsConstType":    {Typ: reflect.TypeOf(q.IsConstType), Value: constant.MakeInt64(int64(q.IsConstType))},
				"IsFloat":        {Typ: reflect.TypeOf(q.IsFloat), Value: constant.MakeInt64(int64(q.IsFloat))},
				"IsInteger":      {Typ: reflect.TypeOf(q.IsInteger), Value: constant.MakeInt64(int64(q.IsInteger))},
				"IsNumeric":      {Typ: reflect.TypeOf(q.IsNumeric), Value: constant.MakeInt64(int64(q.IsNumeric))},
				"IsOrdered":      {Typ: reflect.TypeOf(q.IsOrdered), Value: constant.MakeInt64(int64(q.IsOrdered))},
				"IsString":       {Typ: reflect.TypeOf(q.IsString), Value: constant.MakeInt64(int64(q.IsString))},
				"IsUnsigned":     {Typ: reflect.TypeOf(q.IsUnsigned), Value: constant.MakeInt64(int64(q.IsUnsigned))},
				"IsUntyped":      {Typ: reflect.TypeOf(q.IsUntyped), Value: constant.MakeInt64(int64(q.IsUntyped))},
				"MethodExpr":     {Typ: reflect.TypeOf(q.MethodExpr), Value: constant.MakeInt64(int64(q.MethodExpr))},
				"MethodVal":      {Typ: reflect.TypeOf(q.MethodVal), Value: constant.MakeInt64(int64(q.MethodVal))},
				"RecvOnly":       {Typ: reflect.TypeOf(q.RecvOnly), Value: constant.MakeInt64(int64(q.RecvOnly))},
				"Rune":           {Typ: reflect.TypeOf(q.Rune), Value: constant.MakeInt64(int64(q.Rune))},
				"SendOnly":       {Typ: reflect.TypeOf(q.SendOnly), Value: constant.MakeInt64(int64(q.SendOnly))},
				"SendRecv":       {Typ: reflect.TypeOf(q.SendRecv), Value: constant.MakeInt64(int64(q.SendRecv))},
				"String":         {Typ: reflect.TypeOf(q.String), Value: constant.MakeInt64(int64(q.String))},
				"Uint":           {Typ: reflect.TypeOf(q.Uint), Value: constant.MakeInt64(int64(q.Uint))},
				"Uint16":         {Typ: reflect.TypeOf(q.Uint16), Value: constant.MakeInt64(int64(q.Uint16))},
				"Uint32":         {Typ: reflect.TypeOf(q.Uint32), Value: constant.MakeInt64(int64(q.Uint32))},
				"Uint64":         {Typ: reflect.TypeOf(q.Uint64), Value: constant.MakeInt64(int64(q.Uint64))},
				"Uint8":          {Typ: reflect.TypeOf(q.Uint8), Value: constant.MakeInt64(int64(q.Uint8))},
				"Uintptr":        {Typ: reflect.TypeOf(q.Uintptr), Value: constant.MakeInt64(int64(q.Uintptr))},
				"UnsafePointer":  {Typ: reflect.TypeOf(q.UnsafePointer), Value: constant.MakeInt64(int64(q.UnsafePointer))},
				"UntypedBool":    {Typ: reflect.TypeOf(q.UntypedBool), Value: constant.MakeInt64(int64(q.UntypedBool))},
				"UntypedComplex": {Typ: reflect.TypeOf(q.UntypedComplex), Value: constant.MakeInt64(int64(q.UntypedComplex))},
				"UntypedFloat":   {Typ: reflect.TypeOf(q.UntypedFloat), Value: constant.MakeInt64(int64(q.UntypedFloat))},
				"UntypedInt":     {Typ: reflect.TypeOf(q.UntypedInt), Value: constant.MakeInt64(int64(q.UntypedInt))},
				"UntypedNil":     {Typ: reflect.TypeOf(q.UntypedNil), Value: constant.MakeInt64(int64(q.UntypedNil))},
				"UntypedRune":    {Typ: reflect.TypeOf(q.UntypedRune), Value: constant.MakeInt64(int64(q.UntypedRune))},
				"UntypedString":  {Typ: reflect.TypeOf(q.UntypedString), Value: constant.MakeInt64(int64(q.UntypedString))},
			},
			UntypedConsts: map[string]ixgo.UntypedConst{},
		}
	})
}
