// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.24 && !go1.25
// +build go1.24,!go1.25

package x509

import (
	q "crypto/x509"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackageLazy("crypto/x509", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "x509",
			Path: "crypto/x509",
			Deps: map[string]string{
				"bytes":                                 "bytes",
				"crypto":                                "crypto",
				"crypto/aes":                            "aes",
				"crypto/cipher":                         "cipher",
				"crypto/des":                            "des",
				"crypto/dsa":                            "dsa",
				"crypto/ecdh":                           "ecdh",
				"crypto/ecdsa":                          "ecdsa",
				"crypto/ed25519":                        "ed25519",
				"crypto/elliptic":                       "elliptic",
				"crypto/md5":                            "md5",
				"crypto/rand":                           "rand",
				"crypto/rsa":                            "rsa",
				"crypto/sha1":                           "sha1",
				"crypto/sha256":                         "sha256",
				"crypto/sha512":                         "sha512",
				"crypto/x509/internal/macos":            "macOS",
				"crypto/x509/pkix":                      "pkix",
				"encoding/asn1":                         "asn1",
				"encoding/hex":                          "hex",
				"encoding/pem":                          "pem",
				"errors":                                "errors",
				"fmt":                                   "fmt",
				"internal/godebug":                      "godebug",
				"io":                                    "io",
				"iter":                                  "iter",
				"maps":                                  "maps",
				"math":                                  "math",
				"math/big":                              "big",
				"math/bits":                             "bits",
				"net":                                   "net",
				"net/netip":                             "netip",
				"net/url":                               "url",
				"reflect":                               "reflect",
				"runtime":                               "runtime",
				"strconv":                               "strconv",
				"strings":                               "strings",
				"sync":                                  "sync",
				"time":                                  "time",
				"unicode":                               "unicode",
				"unicode/utf16":                         "utf16",
				"unicode/utf8":                          "utf8",
				"unsafe":                                "unsafe",
				"vendor/golang.org/x/crypto/cryptobyte": "cryptobyte",
				"vendor/golang.org/x/crypto/cryptobyte/asn1": "asn1",
			},
			Interfaces: map[string]reflect.Type{},
			NamedTypes: map[string]reflect.Type{
				"CertPool":                   reflect.TypeOf((*q.CertPool)(nil)).Elem(),
				"Certificate":                reflect.TypeOf((*q.Certificate)(nil)).Elem(),
				"CertificateInvalidError":    reflect.TypeOf((*q.CertificateInvalidError)(nil)).Elem(),
				"CertificateRequest":         reflect.TypeOf((*q.CertificateRequest)(nil)).Elem(),
				"ConstraintViolationError":   reflect.TypeOf((*q.ConstraintViolationError)(nil)).Elem(),
				"ExtKeyUsage":                reflect.TypeOf((*q.ExtKeyUsage)(nil)).Elem(),
				"HostnameError":              reflect.TypeOf((*q.HostnameError)(nil)).Elem(),
				"InsecureAlgorithmError":     reflect.TypeOf((*q.InsecureAlgorithmError)(nil)).Elem(),
				"InvalidReason":              reflect.TypeOf((*q.InvalidReason)(nil)).Elem(),
				"KeyUsage":                   reflect.TypeOf((*q.KeyUsage)(nil)).Elem(),
				"OID":                        reflect.TypeOf((*q.OID)(nil)).Elem(),
				"PEMCipher":                  reflect.TypeOf((*q.PEMCipher)(nil)).Elem(),
				"PolicyMapping":              reflect.TypeOf((*q.PolicyMapping)(nil)).Elem(),
				"PublicKeyAlgorithm":         reflect.TypeOf((*q.PublicKeyAlgorithm)(nil)).Elem(),
				"RevocationList":             reflect.TypeOf((*q.RevocationList)(nil)).Elem(),
				"RevocationListEntry":        reflect.TypeOf((*q.RevocationListEntry)(nil)).Elem(),
				"SignatureAlgorithm":         reflect.TypeOf((*q.SignatureAlgorithm)(nil)).Elem(),
				"SystemRootsError":           reflect.TypeOf((*q.SystemRootsError)(nil)).Elem(),
				"UnhandledCriticalExtension": reflect.TypeOf((*q.UnhandledCriticalExtension)(nil)).Elem(),
				"UnknownAuthorityError":      reflect.TypeOf((*q.UnknownAuthorityError)(nil)).Elem(),
				"VerifyOptions":              reflect.TypeOf((*q.VerifyOptions)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]reflect.Value{
				"ErrUnsupportedAlgorithm": reflect.ValueOf(&q.ErrUnsupportedAlgorithm),
				"IncorrectPasswordError":  reflect.ValueOf(&q.IncorrectPasswordError),
			},
			Funcs: map[string]reflect.Value{
				"CreateCertificate":        reflect.ValueOf(q.CreateCertificate),
				"CreateCertificateRequest": reflect.ValueOf(q.CreateCertificateRequest),
				"CreateRevocationList":     reflect.ValueOf(q.CreateRevocationList),
				"DecryptPEMBlock":          reflect.ValueOf(q.DecryptPEMBlock),
				"EncryptPEMBlock":          reflect.ValueOf(q.EncryptPEMBlock),
				"IsEncryptedPEMBlock":      reflect.ValueOf(q.IsEncryptedPEMBlock),
				"MarshalECPrivateKey":      reflect.ValueOf(q.MarshalECPrivateKey),
				"MarshalPKCS1PrivateKey":   reflect.ValueOf(q.MarshalPKCS1PrivateKey),
				"MarshalPKCS1PublicKey":    reflect.ValueOf(q.MarshalPKCS1PublicKey),
				"MarshalPKCS8PrivateKey":   reflect.ValueOf(q.MarshalPKCS8PrivateKey),
				"MarshalPKIXPublicKey":     reflect.ValueOf(q.MarshalPKIXPublicKey),
				"NewCertPool":              reflect.ValueOf(q.NewCertPool),
				"OIDFromInts":              reflect.ValueOf(q.OIDFromInts),
				"ParseCRL":                 reflect.ValueOf(q.ParseCRL),
				"ParseCertificate":         reflect.ValueOf(q.ParseCertificate),
				"ParseCertificateRequest":  reflect.ValueOf(q.ParseCertificateRequest),
				"ParseCertificates":        reflect.ValueOf(q.ParseCertificates),
				"ParseDERCRL":              reflect.ValueOf(q.ParseDERCRL),
				"ParseECPrivateKey":        reflect.ValueOf(q.ParseECPrivateKey),
				"ParseOID":                 reflect.ValueOf(q.ParseOID),
				"ParsePKCS1PrivateKey":     reflect.ValueOf(q.ParsePKCS1PrivateKey),
				"ParsePKCS1PublicKey":      reflect.ValueOf(q.ParsePKCS1PublicKey),
				"ParsePKCS8PrivateKey":     reflect.ValueOf(q.ParsePKCS8PrivateKey),
				"ParsePKIXPublicKey":       reflect.ValueOf(q.ParsePKIXPublicKey),
				"ParseRevocationList":      reflect.ValueOf(q.ParseRevocationList),
				"SetFallbackRoots":         reflect.ValueOf(q.SetFallbackRoots),
				"SystemCertPool":           reflect.ValueOf(q.SystemCertPool),
			},
			TypedConsts: map[string]ixgo.TypedConst{
				"CANotAuthorizedForExtKeyUsage": {Typ: reflect.TypeOf(q.CANotAuthorizedForExtKeyUsage), Value: constant.MakeInt64(int64(q.CANotAuthorizedForExtKeyUsage))},
				"CANotAuthorizedForThisName":    {Typ: reflect.TypeOf(q.CANotAuthorizedForThisName), Value: constant.MakeInt64(int64(q.CANotAuthorizedForThisName))},
				"DSA":                           {Typ: reflect.TypeOf(q.DSA), Value: constant.MakeInt64(int64(q.DSA))},
				"DSAWithSHA1":                   {Typ: reflect.TypeOf(q.DSAWithSHA1), Value: constant.MakeInt64(int64(q.DSAWithSHA1))},
				"DSAWithSHA256":                 {Typ: reflect.TypeOf(q.DSAWithSHA256), Value: constant.MakeInt64(int64(q.DSAWithSHA256))},
				"ECDSA":                         {Typ: reflect.TypeOf(q.ECDSA), Value: constant.MakeInt64(int64(q.ECDSA))},
				"ECDSAWithSHA1":                 {Typ: reflect.TypeOf(q.ECDSAWithSHA1), Value: constant.MakeInt64(int64(q.ECDSAWithSHA1))},
				"ECDSAWithSHA256":               {Typ: reflect.TypeOf(q.ECDSAWithSHA256), Value: constant.MakeInt64(int64(q.ECDSAWithSHA256))},
				"ECDSAWithSHA384":               {Typ: reflect.TypeOf(q.ECDSAWithSHA384), Value: constant.MakeInt64(int64(q.ECDSAWithSHA384))},
				"ECDSAWithSHA512":               {Typ: reflect.TypeOf(q.ECDSAWithSHA512), Value: constant.MakeInt64(int64(q.ECDSAWithSHA512))},
				"Ed25519":                       {Typ: reflect.TypeOf(q.Ed25519), Value: constant.MakeInt64(int64(q.Ed25519))},
				"Expired":                       {Typ: reflect.TypeOf(q.Expired), Value: constant.MakeInt64(int64(q.Expired))},
				"ExtKeyUsageAny":                {Typ: reflect.TypeOf(q.ExtKeyUsageAny), Value: constant.MakeInt64(int64(q.ExtKeyUsageAny))},
				"ExtKeyUsageClientAuth":         {Typ: reflect.TypeOf(q.ExtKeyUsageClientAuth), Value: constant.MakeInt64(int64(q.ExtKeyUsageClientAuth))},
				"ExtKeyUsageCodeSigning":        {Typ: reflect.TypeOf(q.ExtKeyUsageCodeSigning), Value: constant.MakeInt64(int64(q.ExtKeyUsageCodeSigning))},
				"ExtKeyUsageEmailProtection":    {Typ: reflect.TypeOf(q.ExtKeyUsageEmailProtection), Value: constant.MakeInt64(int64(q.ExtKeyUsageEmailProtection))},
				"ExtKeyUsageIPSECEndSystem":     {Typ: reflect.TypeOf(q.ExtKeyUsageIPSECEndSystem), Value: constant.MakeInt64(int64(q.ExtKeyUsageIPSECEndSystem))},
				"ExtKeyUsageIPSECTunnel":        {Typ: reflect.TypeOf(q.ExtKeyUsageIPSECTunnel), Value: constant.MakeInt64(int64(q.ExtKeyUsageIPSECTunnel))},
				"ExtKeyUsageIPSECUser":          {Typ: reflect.TypeOf(q.ExtKeyUsageIPSECUser), Value: constant.MakeInt64(int64(q.ExtKeyUsageIPSECUser))},
				"ExtKeyUsageMicrosoftCommercialCodeSigning": {Typ: reflect.TypeOf(q.ExtKeyUsageMicrosoftCommercialCodeSigning), Value: constant.MakeInt64(int64(q.ExtKeyUsageMicrosoftCommercialCodeSigning))},
				"ExtKeyUsageMicrosoftKernelCodeSigning":     {Typ: reflect.TypeOf(q.ExtKeyUsageMicrosoftKernelCodeSigning), Value: constant.MakeInt64(int64(q.ExtKeyUsageMicrosoftKernelCodeSigning))},
				"ExtKeyUsageMicrosoftServerGatedCrypto":     {Typ: reflect.TypeOf(q.ExtKeyUsageMicrosoftServerGatedCrypto), Value: constant.MakeInt64(int64(q.ExtKeyUsageMicrosoftServerGatedCrypto))},
				"ExtKeyUsageNetscapeServerGatedCrypto":      {Typ: reflect.TypeOf(q.ExtKeyUsageNetscapeServerGatedCrypto), Value: constant.MakeInt64(int64(q.ExtKeyUsageNetscapeServerGatedCrypto))},
				"ExtKeyUsageOCSPSigning":                    {Typ: reflect.TypeOf(q.ExtKeyUsageOCSPSigning), Value: constant.MakeInt64(int64(q.ExtKeyUsageOCSPSigning))},
				"ExtKeyUsageServerAuth":                     {Typ: reflect.TypeOf(q.ExtKeyUsageServerAuth), Value: constant.MakeInt64(int64(q.ExtKeyUsageServerAuth))},
				"ExtKeyUsageTimeStamping":                   {Typ: reflect.TypeOf(q.ExtKeyUsageTimeStamping), Value: constant.MakeInt64(int64(q.ExtKeyUsageTimeStamping))},
				"IncompatibleUsage":                         {Typ: reflect.TypeOf(q.IncompatibleUsage), Value: constant.MakeInt64(int64(q.IncompatibleUsage))},
				"KeyUsageCRLSign":                           {Typ: reflect.TypeOf(q.KeyUsageCRLSign), Value: constant.MakeInt64(int64(q.KeyUsageCRLSign))},
				"KeyUsageCertSign":                          {Typ: reflect.TypeOf(q.KeyUsageCertSign), Value: constant.MakeInt64(int64(q.KeyUsageCertSign))},
				"KeyUsageContentCommitment":                 {Typ: reflect.TypeOf(q.KeyUsageContentCommitment), Value: constant.MakeInt64(int64(q.KeyUsageContentCommitment))},
				"KeyUsageDataEncipherment":                  {Typ: reflect.TypeOf(q.KeyUsageDataEncipherment), Value: constant.MakeInt64(int64(q.KeyUsageDataEncipherment))},
				"KeyUsageDecipherOnly":                      {Typ: reflect.TypeOf(q.KeyUsageDecipherOnly), Value: constant.MakeInt64(int64(q.KeyUsageDecipherOnly))},
				"KeyUsageDigitalSignature":                  {Typ: reflect.TypeOf(q.KeyUsageDigitalSignature), Value: constant.MakeInt64(int64(q.KeyUsageDigitalSignature))},
				"KeyUsageEncipherOnly":                      {Typ: reflect.TypeOf(q.KeyUsageEncipherOnly), Value: constant.MakeInt64(int64(q.KeyUsageEncipherOnly))},
				"KeyUsageKeyAgreement":                      {Typ: reflect.TypeOf(q.KeyUsageKeyAgreement), Value: constant.MakeInt64(int64(q.KeyUsageKeyAgreement))},
				"KeyUsageKeyEncipherment":                   {Typ: reflect.TypeOf(q.KeyUsageKeyEncipherment), Value: constant.MakeInt64(int64(q.KeyUsageKeyEncipherment))},
				"MD2WithRSA":                                {Typ: reflect.TypeOf(q.MD2WithRSA), Value: constant.MakeInt64(int64(q.MD2WithRSA))},
				"MD5WithRSA":                                {Typ: reflect.TypeOf(q.MD5WithRSA), Value: constant.MakeInt64(int64(q.MD5WithRSA))},
				"NameConstraintsWithoutSANs":                {Typ: reflect.TypeOf(q.NameConstraintsWithoutSANs), Value: constant.MakeInt64(int64(q.NameConstraintsWithoutSANs))},
				"NameMismatch":                              {Typ: reflect.TypeOf(q.NameMismatch), Value: constant.MakeInt64(int64(q.NameMismatch))},
				"NoValidChains":                             {Typ: reflect.TypeOf(q.NoValidChains), Value: constant.MakeInt64(int64(q.NoValidChains))},
				"NotAuthorizedToSign":                       {Typ: reflect.TypeOf(q.NotAuthorizedToSign), Value: constant.MakeInt64(int64(q.NotAuthorizedToSign))},
				"PEMCipher3DES":                             {Typ: reflect.TypeOf(q.PEMCipher3DES), Value: constant.MakeInt64(int64(q.PEMCipher3DES))},
				"PEMCipherAES128":                           {Typ: reflect.TypeOf(q.PEMCipherAES128), Value: constant.MakeInt64(int64(q.PEMCipherAES128))},
				"PEMCipherAES192":                           {Typ: reflect.TypeOf(q.PEMCipherAES192), Value: constant.MakeInt64(int64(q.PEMCipherAES192))},
				"PEMCipherAES256":                           {Typ: reflect.TypeOf(q.PEMCipherAES256), Value: constant.MakeInt64(int64(q.PEMCipherAES256))},
				"PEMCipherDES":                              {Typ: reflect.TypeOf(q.PEMCipherDES), Value: constant.MakeInt64(int64(q.PEMCipherDES))},
				"PureEd25519":                               {Typ: reflect.TypeOf(q.PureEd25519), Value: constant.MakeInt64(int64(q.PureEd25519))},
				"RSA":                                       {Typ: reflect.TypeOf(q.RSA), Value: constant.MakeInt64(int64(q.RSA))},
				"SHA1WithRSA":                               {Typ: reflect.TypeOf(q.SHA1WithRSA), Value: constant.MakeInt64(int64(q.SHA1WithRSA))},
				"SHA256WithRSA":                             {Typ: reflect.TypeOf(q.SHA256WithRSA), Value: constant.MakeInt64(int64(q.SHA256WithRSA))},
				"SHA256WithRSAPSS":                          {Typ: reflect.TypeOf(q.SHA256WithRSAPSS), Value: constant.MakeInt64(int64(q.SHA256WithRSAPSS))},
				"SHA384WithRSA":                             {Typ: reflect.TypeOf(q.SHA384WithRSA), Value: constant.MakeInt64(int64(q.SHA384WithRSA))},
				"SHA384WithRSAPSS":                          {Typ: reflect.TypeOf(q.SHA384WithRSAPSS), Value: constant.MakeInt64(int64(q.SHA384WithRSAPSS))},
				"SHA512WithRSA":                             {Typ: reflect.TypeOf(q.SHA512WithRSA), Value: constant.MakeInt64(int64(q.SHA512WithRSA))},
				"SHA512WithRSAPSS":                          {Typ: reflect.TypeOf(q.SHA512WithRSAPSS), Value: constant.MakeInt64(int64(q.SHA512WithRSAPSS))},
				"TooManyConstraints":                        {Typ: reflect.TypeOf(q.TooManyConstraints), Value: constant.MakeInt64(int64(q.TooManyConstraints))},
				"TooManyIntermediates":                      {Typ: reflect.TypeOf(q.TooManyIntermediates), Value: constant.MakeInt64(int64(q.TooManyIntermediates))},
				"UnconstrainedName":                         {Typ: reflect.TypeOf(q.UnconstrainedName), Value: constant.MakeInt64(int64(q.UnconstrainedName))},
				"UnknownPublicKeyAlgorithm":                 {Typ: reflect.TypeOf(q.UnknownPublicKeyAlgorithm), Value: constant.MakeInt64(int64(q.UnknownPublicKeyAlgorithm))},
				"UnknownSignatureAlgorithm":                 {Typ: reflect.TypeOf(q.UnknownSignatureAlgorithm), Value: constant.MakeInt64(int64(q.UnknownSignatureAlgorithm))},
			},
			UntypedConsts: map[string]ixgo.UntypedConst{},
		}
	})
}
