// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.25 && !go1.26
// +build go1.25,!go1.26

package x509

import (
	q "crypto/x509"

	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("crypto/x509", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "x509",
			Path: "crypto/x509",
			Deps: map[string]string{
				"bytes":                                 "bytes",
				"crypto":                                "crypto",
				"crypto/aes":                            "aes",
				"crypto/cipher":                         "cipher",
				"crypto/des":                            "des",
				"crypto/dsa":                            "dsa",
				"crypto/ecdh":                           "ecdh",
				"crypto/ecdsa":                          "ecdsa",
				"crypto/ed25519":                        "ed25519",
				"crypto/elliptic":                       "elliptic",
				"crypto/md5":                            "md5",
				"crypto/rsa":                            "rsa",
				"crypto/sha1":                           "sha1",
				"crypto/sha256":                         "sha256",
				"crypto/sha512":                         "sha512",
				"crypto/x509/internal/macos":            "macOS",
				"crypto/x509/pkix":                      "pkix",
				"encoding/asn1":                         "asn1",
				"encoding/hex":                          "hex",
				"encoding/pem":                          "pem",
				"errors":                                "errors",
				"fmt":                                   "fmt",
				"internal/godebug":                      "godebug",
				"io":                                    "io",
				"iter":                                  "iter",
				"maps":                                  "maps",
				"math":                                  "math",
				"math/big":                              "big",
				"math/bits":                             "bits",
				"net":                                   "net",
				"net/netip":                             "netip",
				"net/url":                               "url",
				"reflect":                               "reflect",
				"runtime":                               "runtime",
				"strconv":                               "strconv",
				"strings":                               "strings",
				"sync":                                  "sync",
				"time":                                  "time",
				"unicode":                               "unicode",
				"unicode/utf16":                         "utf16",
				"unicode/utf8":                          "utf8",
				"unsafe":                                "unsafe",
				"vendor/golang.org/x/crypto/cryptobyte": "cryptobyte",
				"vendor/golang.org/x/crypto/cryptobyte/asn1": "asn1",
			},
			Interfaces: map[string]reflect.Type{},
			NamedTypes: map[string]reflect.Type{
				"CertPool":                   reflect.TypeOf((*q.CertPool)(nil)).Elem(),
				"Certificate":                reflect.TypeOf((*q.Certificate)(nil)).Elem(),
				"CertificateInvalidError":    reflect.TypeOf((*q.CertificateInvalidError)(nil)).Elem(),
				"CertificateRequest":         reflect.TypeOf((*q.CertificateRequest)(nil)).Elem(),
				"ConstraintViolationError":   reflect.TypeOf((*q.ConstraintViolationError)(nil)).Elem(),
				"ExtKeyUsage":                reflect.TypeOf((*q.ExtKeyUsage)(nil)).Elem(),
				"HostnameError":              reflect.TypeOf((*q.HostnameError)(nil)).Elem(),
				"InsecureAlgorithmError":     reflect.TypeOf((*q.InsecureAlgorithmError)(nil)).Elem(),
				"InvalidReason":              reflect.TypeOf((*q.InvalidReason)(nil)).Elem(),
				"KeyUsage":                   reflect.TypeOf((*q.KeyUsage)(nil)).Elem(),
				"OID":                        reflect.TypeOf((*q.OID)(nil)).Elem(),
				"PEMCipher":                  reflect.TypeOf((*q.PEMCipher)(nil)).Elem(),
				"PolicyMapping":              reflect.TypeOf((*q.PolicyMapping)(nil)).Elem(),
				"PublicKeyAlgorithm":         reflect.TypeOf((*q.PublicKeyAlgorithm)(nil)).Elem(),
				"RevocationList":             reflect.TypeOf((*q.RevocationList)(nil)).Elem(),
				"RevocationListEntry":        reflect.TypeOf((*q.RevocationListEntry)(nil)).Elem(),
				"SignatureAlgorithm":         reflect.TypeOf((*q.SignatureAlgorithm)(nil)).Elem(),
				"SystemRootsError":           reflect.TypeOf((*q.SystemRootsError)(nil)).Elem(),
				"UnhandledCriticalExtension": reflect.TypeOf((*q.UnhandledCriticalExtension)(nil)).Elem(),
				"UnknownAuthorityError":      reflect.TypeOf((*q.UnknownAuthorityError)(nil)).Elem(),
				"VerifyOptions":              reflect.TypeOf((*q.VerifyOptions)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]interface{}{
				"ErrUnsupportedAlgorithm": &q.ErrUnsupportedAlgorithm,
				"IncorrectPasswordError":  &q.IncorrectPasswordError,
			},
			Funcs: map[string]interface{}{
				"CreateCertificate":        q.CreateCertificate,
				"CreateCertificateRequest": q.CreateCertificateRequest,
				"CreateRevocationList":     q.CreateRevocationList,
				"DecryptPEMBlock":          q.DecryptPEMBlock,
				"EncryptPEMBlock":          q.EncryptPEMBlock,
				"IsEncryptedPEMBlock":      q.IsEncryptedPEMBlock,
				"MarshalECPrivateKey":      q.MarshalECPrivateKey,
				"MarshalPKCS1PrivateKey":   q.MarshalPKCS1PrivateKey,
				"MarshalPKCS1PublicKey":    q.MarshalPKCS1PublicKey,
				"MarshalPKCS8PrivateKey":   q.MarshalPKCS8PrivateKey,
				"MarshalPKIXPublicKey":     q.MarshalPKIXPublicKey,
				"NewCertPool":              q.NewCertPool,
				"OIDFromInts":              q.OIDFromInts,
				"ParseCRL":                 q.ParseCRL,
				"ParseCertificate":         q.ParseCertificate,
				"ParseCertificateRequest":  q.ParseCertificateRequest,
				"ParseCertificates":        q.ParseCertificates,
				"ParseDERCRL":              q.ParseDERCRL,
				"ParseECPrivateKey":        q.ParseECPrivateKey,
				"ParseOID":                 q.ParseOID,
				"ParsePKCS1PrivateKey":     q.ParsePKCS1PrivateKey,
				"ParsePKCS1PublicKey":      q.ParsePKCS1PublicKey,
				"ParsePKCS8PrivateKey":     q.ParsePKCS8PrivateKey,
				"ParsePKIXPublicKey":       q.ParsePKIXPublicKey,
				"ParseRevocationList":      q.ParseRevocationList,
				"SetFallbackRoots":         q.SetFallbackRoots,
				"SystemCertPool":           q.SystemCertPool,
			},
			TypedConsts: map[string]interface{}{
				"CANotAuthorizedForExtKeyUsage": q.CANotAuthorizedForExtKeyUsage,
				"CANotAuthorizedForThisName":    q.CANotAuthorizedForThisName,
				"DSA":                           q.DSA,
				"DSAWithSHA1":                   q.DSAWithSHA1,
				"DSAWithSHA256":                 q.DSAWithSHA256,
				"ECDSA":                         q.ECDSA,
				"ECDSAWithSHA1":                 q.ECDSAWithSHA1,
				"ECDSAWithSHA256":               q.ECDSAWithSHA256,
				"ECDSAWithSHA384":               q.ECDSAWithSHA384,
				"ECDSAWithSHA512":               q.ECDSAWithSHA512,
				"Ed25519":                       q.Ed25519,
				"Expired":                       q.Expired,
				"ExtKeyUsageAny":                q.ExtKeyUsageAny,
				"ExtKeyUsageClientAuth":         q.ExtKeyUsageClientAuth,
				"ExtKeyUsageCodeSigning":        q.ExtKeyUsageCodeSigning,
				"ExtKeyUsageEmailProtection":    q.ExtKeyUsageEmailProtection,
				"ExtKeyUsageIPSECEndSystem":     q.ExtKeyUsageIPSECEndSystem,
				"ExtKeyUsageIPSECTunnel":        q.ExtKeyUsageIPSECTunnel,
				"ExtKeyUsageIPSECUser":          q.ExtKeyUsageIPSECUser,
				"ExtKeyUsageMicrosoftCommercialCodeSigning": q.ExtKeyUsageMicrosoftCommercialCodeSigning,
				"ExtKeyUsageMicrosoftKernelCodeSigning":     q.ExtKeyUsageMicrosoftKernelCodeSigning,
				"ExtKeyUsageMicrosoftServerGatedCrypto":     q.ExtKeyUsageMicrosoftServerGatedCrypto,
				"ExtKeyUsageNetscapeServerGatedCrypto":      q.ExtKeyUsageNetscapeServerGatedCrypto,
				"ExtKeyUsageOCSPSigning":                    q.ExtKeyUsageOCSPSigning,
				"ExtKeyUsageServerAuth":                     q.ExtKeyUsageServerAuth,
				"ExtKeyUsageTimeStamping":                   q.ExtKeyUsageTimeStamping,
				"IncompatibleUsage":                         q.IncompatibleUsage,
				"KeyUsageCRLSign":                           q.KeyUsageCRLSign,
				"KeyUsageCertSign":                          q.KeyUsageCertSign,
				"KeyUsageContentCommitment":                 q.KeyUsageContentCommitment,
				"KeyUsageDataEncipherment":                  q.KeyUsageDataEncipherment,
				"KeyUsageDecipherOnly":                      q.KeyUsageDecipherOnly,
				"KeyUsageDigitalSignature":                  q.KeyUsageDigitalSignature,
				"KeyUsageEncipherOnly":                      q.KeyUsageEncipherOnly,
				"KeyUsageKeyAgreement":                      q.KeyUsageKeyAgreement,
				"KeyUsageKeyEncipherment":                   q.KeyUsageKeyEncipherment,
				"MD2WithRSA":                                q.MD2WithRSA,
				"MD5WithRSA":                                q.MD5WithRSA,
				"NameConstraintsWithoutSANs":                q.NameConstraintsWithoutSANs,
				"NameMismatch":                              q.NameMismatch,
				"NoValidChains":                             q.NoValidChains,
				"NotAuthorizedToSign":                       q.NotAuthorizedToSign,
				"PEMCipher3DES":                             q.PEMCipher3DES,
				"PEMCipherAES128":                           q.PEMCipherAES128,
				"PEMCipherAES192":                           q.PEMCipherAES192,
				"PEMCipherAES256":                           q.PEMCipherAES256,
				"PEMCipherDES":                              q.PEMCipherDES,
				"PureEd25519":                               q.PureEd25519,
				"RSA":                                       q.RSA,
				"SHA1WithRSA":                               q.SHA1WithRSA,
				"SHA256WithRSA":                             q.SHA256WithRSA,
				"SHA256WithRSAPSS":                          q.SHA256WithRSAPSS,
				"SHA384WithRSA":                             q.SHA384WithRSA,
				"SHA384WithRSAPSS":                          q.SHA384WithRSAPSS,
				"SHA512WithRSA":                             q.SHA512WithRSA,
				"SHA512WithRSAPSS":                          q.SHA512WithRSAPSS,
				"TooManyConstraints":                        q.TooManyConstraints,
				"TooManyIntermediates":                      q.TooManyIntermediates,
				"UnconstrainedName":                         q.UnconstrainedName,
				"UnknownPublicKeyAlgorithm":                 q.UnknownPublicKeyAlgorithm,
				"UnknownSignatureAlgorithm":                 q.UnknownSignatureAlgorithm,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{},
		}
	})
}
