// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.24 && !go1.25
// +build go1.24,!go1.25

package pe

import (
	q "debug/pe"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("debug/pe", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "pe",
			Path: "debug/pe",
			Deps: map[string]string{
				"bytes":            "bytes",
				"compress/zlib":    "zlib",
				"debug/dwarf":      "dwarf",
				"encoding/binary":  "binary",
				"errors":           "errors",
				"fmt":              "fmt",
				"internal/saferio": "saferio",
				"io":               "io",
				"os":               "os",
				"strconv":          "strconv",
				"strings":          "strings",
				"unsafe":           "unsafe",
			},
			Interfaces: map[string]reflect.Type{},
			NamedTypes: map[string]reflect.Type{
				"COFFSymbol":           reflect.TypeOf((*q.COFFSymbol)(nil)).Elem(),
				"COFFSymbolAuxFormat5": reflect.TypeOf((*q.COFFSymbolAuxFormat5)(nil)).Elem(),
				"DataDirectory":        reflect.TypeOf((*q.DataDirectory)(nil)).Elem(),
				"File":                 reflect.TypeOf((*q.File)(nil)).Elem(),
				"FileHeader":           reflect.TypeOf((*q.FileHeader)(nil)).Elem(),
				"FormatError":          reflect.TypeOf((*q.FormatError)(nil)).Elem(),
				"ImportDirectory":      reflect.TypeOf((*q.ImportDirectory)(nil)).Elem(),
				"OptionalHeader32":     reflect.TypeOf((*q.OptionalHeader32)(nil)).Elem(),
				"OptionalHeader64":     reflect.TypeOf((*q.OptionalHeader64)(nil)).Elem(),
				"Reloc":                reflect.TypeOf((*q.Reloc)(nil)).Elem(),
				"Section":              reflect.TypeOf((*q.Section)(nil)).Elem(),
				"SectionHeader":        reflect.TypeOf((*q.SectionHeader)(nil)).Elem(),
				"SectionHeader32":      reflect.TypeOf((*q.SectionHeader32)(nil)).Elem(),
				"StringTable":          reflect.TypeOf((*q.StringTable)(nil)).Elem(),
				"Symbol":               reflect.TypeOf((*q.Symbol)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars:       map[string]interface{}{},
			Funcs: map[string]interface{}{
				"NewFile": q.NewFile,
				"Open":    q.Open,
			},
			TypedConsts: map[string]interface{}{},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"COFFSymbolSize":                                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.COFFSymbolSize))},
				"IMAGE_COMDAT_SELECT_ANY":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_COMDAT_SELECT_ANY))},
				"IMAGE_COMDAT_SELECT_ASSOCIATIVE":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_COMDAT_SELECT_ASSOCIATIVE))},
				"IMAGE_COMDAT_SELECT_EXACT_MATCH":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_COMDAT_SELECT_EXACT_MATCH))},
				"IMAGE_COMDAT_SELECT_LARGEST":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_COMDAT_SELECT_LARGEST))},
				"IMAGE_COMDAT_SELECT_NODUPLICATES":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_COMDAT_SELECT_NODUPLICATES))},
				"IMAGE_COMDAT_SELECT_SAME_SIZE":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_COMDAT_SELECT_SAME_SIZE))},
				"IMAGE_DIRECTORY_ENTRY_ARCHITECTURE":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_ARCHITECTURE))},
				"IMAGE_DIRECTORY_ENTRY_BASERELOC":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_BASERELOC))},
				"IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT))},
				"IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR":           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR))},
				"IMAGE_DIRECTORY_ENTRY_DEBUG":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_DEBUG))},
				"IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT))},
				"IMAGE_DIRECTORY_ENTRY_EXCEPTION":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_EXCEPTION))},
				"IMAGE_DIRECTORY_ENTRY_EXPORT":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_EXPORT))},
				"IMAGE_DIRECTORY_ENTRY_GLOBALPTR":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_GLOBALPTR))},
				"IMAGE_DIRECTORY_ENTRY_IAT":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_IAT))},
				"IMAGE_DIRECTORY_ENTRY_IMPORT":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_IMPORT))},
				"IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG":              {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG))},
				"IMAGE_DIRECTORY_ENTRY_RESOURCE":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_RESOURCE))},
				"IMAGE_DIRECTORY_ENTRY_SECURITY":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_SECURITY))},
				"IMAGE_DIRECTORY_ENTRY_TLS":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DIRECTORY_ENTRY_TLS))},
				"IMAGE_DLLCHARACTERISTICS_APPCONTAINER":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DLLCHARACTERISTICS_APPCONTAINER))},
				"IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE))},
				"IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY))},
				"IMAGE_DLLCHARACTERISTICS_GUARD_CF":              {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DLLCHARACTERISTICS_GUARD_CF))},
				"IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA))},
				"IMAGE_DLLCHARACTERISTICS_NO_BIND":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DLLCHARACTERISTICS_NO_BIND))},
				"IMAGE_DLLCHARACTERISTICS_NO_ISOLATION":          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DLLCHARACTERISTICS_NO_ISOLATION))},
				"IMAGE_DLLCHARACTERISTICS_NO_SEH":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DLLCHARACTERISTICS_NO_SEH))},
				"IMAGE_DLLCHARACTERISTICS_NX_COMPAT":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DLLCHARACTERISTICS_NX_COMPAT))},
				"IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE": {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE))},
				"IMAGE_DLLCHARACTERISTICS_WDM_DRIVER":            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_DLLCHARACTERISTICS_WDM_DRIVER))},
				"IMAGE_FILE_32BIT_MACHINE":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_32BIT_MACHINE))},
				"IMAGE_FILE_AGGRESIVE_WS_TRIM":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_AGGRESIVE_WS_TRIM))},
				"IMAGE_FILE_BYTES_REVERSED_HI":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_BYTES_REVERSED_HI))},
				"IMAGE_FILE_BYTES_REVERSED_LO":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_BYTES_REVERSED_LO))},
				"IMAGE_FILE_DEBUG_STRIPPED":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_DEBUG_STRIPPED))},
				"IMAGE_FILE_DLL":                                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_DLL))},
				"IMAGE_FILE_EXECUTABLE_IMAGE":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_EXECUTABLE_IMAGE))},
				"IMAGE_FILE_LARGE_ADDRESS_AWARE":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_LARGE_ADDRESS_AWARE))},
				"IMAGE_FILE_LINE_NUMS_STRIPPED":                  {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_LINE_NUMS_STRIPPED))},
				"IMAGE_FILE_LOCAL_SYMS_STRIPPED":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_LOCAL_SYMS_STRIPPED))},
				"IMAGE_FILE_MACHINE_AM33":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_AM33))},
				"IMAGE_FILE_MACHINE_AMD64":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_AMD64))},
				"IMAGE_FILE_MACHINE_ARM":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_ARM))},
				"IMAGE_FILE_MACHINE_ARM64":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_ARM64))},
				"IMAGE_FILE_MACHINE_ARMNT":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_ARMNT))},
				"IMAGE_FILE_MACHINE_EBC":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_EBC))},
				"IMAGE_FILE_MACHINE_I386":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_I386))},
				"IMAGE_FILE_MACHINE_IA64":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_IA64))},
				"IMAGE_FILE_MACHINE_LOONGARCH32":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_LOONGARCH32))},
				"IMAGE_FILE_MACHINE_LOONGARCH64":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_LOONGARCH64))},
				"IMAGE_FILE_MACHINE_M32R":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_M32R))},
				"IMAGE_FILE_MACHINE_MIPS16":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_MIPS16))},
				"IMAGE_FILE_MACHINE_MIPSFPU":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_MIPSFPU))},
				"IMAGE_FILE_MACHINE_MIPSFPU16":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_MIPSFPU16))},
				"IMAGE_FILE_MACHINE_POWERPC":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_POWERPC))},
				"IMAGE_FILE_MACHINE_POWERPCFP":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_POWERPCFP))},
				"IMAGE_FILE_MACHINE_R4000":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_R4000))},
				"IMAGE_FILE_MACHINE_RISCV128":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_RISCV128))},
				"IMAGE_FILE_MACHINE_RISCV32":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_RISCV32))},
				"IMAGE_FILE_MACHINE_RISCV64":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_RISCV64))},
				"IMAGE_FILE_MACHINE_SH3":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_SH3))},
				"IMAGE_FILE_MACHINE_SH3DSP":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_SH3DSP))},
				"IMAGE_FILE_MACHINE_SH4":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_SH4))},
				"IMAGE_FILE_MACHINE_SH5":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_SH5))},
				"IMAGE_FILE_MACHINE_THUMB":                       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_THUMB))},
				"IMAGE_FILE_MACHINE_UNKNOWN":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_UNKNOWN))},
				"IMAGE_FILE_MACHINE_WCEMIPSV2":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_MACHINE_WCEMIPSV2))},
				"IMAGE_FILE_NET_RUN_FROM_SWAP":                   {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_NET_RUN_FROM_SWAP))},
				"IMAGE_FILE_RELOCS_STRIPPED":                     {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_RELOCS_STRIPPED))},
				"IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP))},
				"IMAGE_FILE_SYSTEM":                              {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_SYSTEM))},
				"IMAGE_FILE_UP_SYSTEM_ONLY":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_FILE_UP_SYSTEM_ONLY))},
				"IMAGE_SCN_CNT_CODE":                             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SCN_CNT_CODE))},
				"IMAGE_SCN_CNT_INITIALIZED_DATA":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SCN_CNT_INITIALIZED_DATA))},
				"IMAGE_SCN_CNT_UNINITIALIZED_DATA":               {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SCN_CNT_UNINITIALIZED_DATA))},
				"IMAGE_SCN_LNK_COMDAT":                           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SCN_LNK_COMDAT))},
				"IMAGE_SCN_MEM_DISCARDABLE":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SCN_MEM_DISCARDABLE))},
				"IMAGE_SCN_MEM_EXECUTE":                          {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SCN_MEM_EXECUTE))},
				"IMAGE_SCN_MEM_READ":                             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SCN_MEM_READ))},
				"IMAGE_SCN_MEM_WRITE":                            {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SCN_MEM_WRITE))},
				"IMAGE_SUBSYSTEM_EFI_APPLICATION":                {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_EFI_APPLICATION))},
				"IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER":        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER))},
				"IMAGE_SUBSYSTEM_EFI_ROM":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_EFI_ROM))},
				"IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER":             {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER))},
				"IMAGE_SUBSYSTEM_NATIVE":                         {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_NATIVE))},
				"IMAGE_SUBSYSTEM_NATIVE_WINDOWS":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_NATIVE_WINDOWS))},
				"IMAGE_SUBSYSTEM_OS2_CUI":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_OS2_CUI))},
				"IMAGE_SUBSYSTEM_POSIX_CUI":                      {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_POSIX_CUI))},
				"IMAGE_SUBSYSTEM_UNKNOWN":                        {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_UNKNOWN))},
				"IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION":       {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION))},
				"IMAGE_SUBSYSTEM_WINDOWS_CE_GUI":                 {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_WINDOWS_CE_GUI))},
				"IMAGE_SUBSYSTEM_WINDOWS_CUI":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_WINDOWS_CUI))},
				"IMAGE_SUBSYSTEM_WINDOWS_GUI":                    {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_WINDOWS_GUI))},
				"IMAGE_SUBSYSTEM_XBOX":                           {Typ: "untyped int", Value: constant.MakeInt64(int64(q.IMAGE_SUBSYSTEM_XBOX))},
			},
		}
	})
}
