// export by github.com/goplus/ixgo/cmd/qexp

package abi

import (
	q "github.com/goplus/ixgo/x/abi"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage(&ixgo.Package{
		Name: "abi",
		Path: "github.com/goplus/ixgo/x/abi",
		Deps: map[string]string{
			"unsafe": "unsafe",
		},
		Interfaces: map[string]reflect.Type{},
		NamedTypes: map[string]reflect.Type{
			"ArrayType":      reflect.TypeOf((*q.ArrayType)(nil)).Elem(),
			"ChanDir":        reflect.TypeOf((*q.ChanDir)(nil)).Elem(),
			"ChanType":       reflect.TypeOf((*q.ChanType)(nil)).Elem(),
			"EmptyInterface": reflect.TypeOf((*q.EmptyInterface)(nil)).Elem(),
			"FuncType":       reflect.TypeOf((*q.FuncType)(nil)).Elem(),
			"ITab":           reflect.TypeOf((*q.ITab)(nil)).Elem(),
			"Imethod":        reflect.TypeOf((*q.Imethod)(nil)).Elem(),
			"InterfaceType":  reflect.TypeOf((*q.InterfaceType)(nil)).Elem(),
			"Kind":           reflect.TypeOf((*q.Kind)(nil)).Elem(),
			"Method":         reflect.TypeOf((*q.Method)(nil)).Elem(),
			"Name":           reflect.TypeOf((*q.Name)(nil)).Elem(),
			"NameOff":        reflect.TypeOf((*q.NameOff)(nil)).Elem(),
			"OldMapType":     reflect.TypeOf((*q.OldMapType)(nil)).Elem(),
			"PtrType":        reflect.TypeOf((*q.PtrType)(nil)).Elem(),
			"SliceType":      reflect.TypeOf((*q.SliceType)(nil)).Elem(),
			"StructField":    reflect.TypeOf((*q.StructField)(nil)).Elem(),
			"StructType":     reflect.TypeOf((*q.StructType)(nil)).Elem(),
			"SwissMapType":   reflect.TypeOf((*q.SwissMapType)(nil)).Elem(),
			"TFlag":          reflect.TypeOf((*q.TFlag)(nil)).Elem(),
			"TextOff":        reflect.TypeOf((*q.TextOff)(nil)).Elem(),
			"Type":           reflect.TypeOf((*q.Type)(nil)).Elem(),
			"TypeOff":        reflect.TypeOf((*q.TypeOff)(nil)).Elem(),
			"UncommonType":   reflect.TypeOf((*q.UncommonType)(nil)).Elem(),
		},
		AliasTypes: map[string]reflect.Type{},
		Vars:       map[string]reflect.Value{},
		Funcs: map[string]reflect.Value{
			"NewName":  reflect.ValueOf(q.NewName),
			"NoEscape": reflect.ValueOf(q.NoEscape),
			"TypeOf":   reflect.ValueOf(q.TypeOf),
		},
		TypedConsts: map[string]ixgo.TypedConst{
			"Array":               {reflect.TypeOf(q.Array), constant.MakeInt64(int64(q.Array))},
			"Bool":                {reflect.TypeOf(q.Bool), constant.MakeInt64(int64(q.Bool))},
			"BothDir":             {reflect.TypeOf(q.BothDir), constant.MakeInt64(int64(q.BothDir))},
			"Chan":                {reflect.TypeOf(q.Chan), constant.MakeInt64(int64(q.Chan))},
			"Complex128":          {reflect.TypeOf(q.Complex128), constant.MakeInt64(int64(q.Complex128))},
			"Complex64":           {reflect.TypeOf(q.Complex64), constant.MakeInt64(int64(q.Complex64))},
			"Float32":             {reflect.TypeOf(q.Float32), constant.MakeInt64(int64(q.Float32))},
			"Float64":             {reflect.TypeOf(q.Float64), constant.MakeInt64(int64(q.Float64))},
			"Func":                {reflect.TypeOf(q.Func), constant.MakeInt64(int64(q.Func))},
			"Int":                 {reflect.TypeOf(q.Int), constant.MakeInt64(int64(q.Int))},
			"Int16":               {reflect.TypeOf(q.Int16), constant.MakeInt64(int64(q.Int16))},
			"Int32":               {reflect.TypeOf(q.Int32), constant.MakeInt64(int64(q.Int32))},
			"Int64":               {reflect.TypeOf(q.Int64), constant.MakeInt64(int64(q.Int64))},
			"Int8":                {reflect.TypeOf(q.Int8), constant.MakeInt64(int64(q.Int8))},
			"Interface":           {reflect.TypeOf(q.Interface), constant.MakeInt64(int64(q.Interface))},
			"Invalid":             {reflect.TypeOf(q.Invalid), constant.MakeInt64(int64(q.Invalid))},
			"InvalidDir":          {reflect.TypeOf(q.InvalidDir), constant.MakeInt64(int64(q.InvalidDir))},
			"KindDirectIface":     {reflect.TypeOf(q.KindDirectIface), constant.MakeInt64(int64(q.KindDirectIface))},
			"KindMask":            {reflect.TypeOf(q.KindMask), constant.MakeInt64(int64(q.KindMask))},
			"Map":                 {reflect.TypeOf(q.Map), constant.MakeInt64(int64(q.Map))},
			"Pointer":             {reflect.TypeOf(q.Pointer), constant.MakeInt64(int64(q.Pointer))},
			"RecvDir":             {reflect.TypeOf(q.RecvDir), constant.MakeInt64(int64(q.RecvDir))},
			"SendDir":             {reflect.TypeOf(q.SendDir), constant.MakeInt64(int64(q.SendDir))},
			"Slice":               {reflect.TypeOf(q.Slice), constant.MakeInt64(int64(q.Slice))},
			"String":              {reflect.TypeOf(q.String), constant.MakeInt64(int64(q.String))},
			"Struct":              {reflect.TypeOf(q.Struct), constant.MakeInt64(int64(q.Struct))},
			"SwissMapCtrlEmpty":   {reflect.TypeOf(q.SwissMapCtrlEmpty), constant.MakeUint64(uint64(q.SwissMapCtrlEmpty))},
			"TFlagExtraStar":      {reflect.TypeOf(q.TFlagExtraStar), constant.MakeInt64(int64(q.TFlagExtraStar))},
			"TFlagGCMaskOnDemand": {reflect.TypeOf(q.TFlagGCMaskOnDemand), constant.MakeInt64(int64(q.TFlagGCMaskOnDemand))},
			"TFlagNamed":          {reflect.TypeOf(q.TFlagNamed), constant.MakeInt64(int64(q.TFlagNamed))},
			"TFlagRegularMemory":  {reflect.TypeOf(q.TFlagRegularMemory), constant.MakeInt64(int64(q.TFlagRegularMemory))},
			"TFlagUncommon":       {reflect.TypeOf(q.TFlagUncommon), constant.MakeInt64(int64(q.TFlagUncommon))},
			"Uint":                {reflect.TypeOf(q.Uint), constant.MakeInt64(int64(q.Uint))},
			"Uint16":              {reflect.TypeOf(q.Uint16), constant.MakeInt64(int64(q.Uint16))},
			"Uint32":              {reflect.TypeOf(q.Uint32), constant.MakeInt64(int64(q.Uint32))},
			"Uint64":              {reflect.TypeOf(q.Uint64), constant.MakeInt64(int64(q.Uint64))},
			"Uint8":               {reflect.TypeOf(q.Uint8), constant.MakeInt64(int64(q.Uint8))},
			"Uintptr":             {reflect.TypeOf(q.Uintptr), constant.MakeInt64(int64(q.Uintptr))},
			"UnsafePointer":       {reflect.TypeOf(q.UnsafePointer), constant.MakeInt64(int64(q.UnsafePointer))},
		},
		UntypedConsts: map[string]ixgo.UntypedConst{
			"MaxPtrmaskBytes":         {"untyped int", constant.MakeInt64(int64(q.MaxPtrmaskBytes))},
			"OldMapBucketCount":       {"untyped int", constant.MakeInt64(int64(q.OldMapBucketCount))},
			"OldMapBucketCountBits":   {"untyped int", constant.MakeInt64(int64(q.OldMapBucketCountBits))},
			"OldMapMaxElemBytes":      {"untyped int", constant.MakeInt64(int64(q.OldMapMaxElemBytes))},
			"OldMapMaxKeyBytes":       {"untyped int", constant.MakeInt64(int64(q.OldMapMaxKeyBytes))},
			"SwissMapGroupSlots":      {"untyped int", constant.MakeInt64(int64(q.SwissMapGroupSlots))},
			"SwissMapGroupSlotsBits":  {"untyped int", constant.MakeInt64(int64(q.SwissMapGroupSlotsBits))},
			"SwissMapHashMightPanic":  {"untyped int", constant.MakeInt64(int64(q.SwissMapHashMightPanic))},
			"SwissMapIndirectElem":    {"untyped int", constant.MakeInt64(int64(q.SwissMapIndirectElem))},
			"SwissMapIndirectKey":     {"untyped int", constant.MakeInt64(int64(q.SwissMapIndirectKey))},
			"SwissMapMaxElemBytes":    {"untyped int", constant.MakeInt64(int64(q.SwissMapMaxElemBytes))},
			"SwissMapMaxKeyBytes":     {"untyped int", constant.MakeInt64(int64(q.SwissMapMaxKeyBytes))},
			"SwissMapNeedKeyUpdate":   {"untyped int", constant.MakeInt64(int64(q.SwissMapNeedKeyUpdate))},
			"TraceArgsDotdotdot":      {"untyped int", constant.MakeInt64(int64(q.TraceArgsDotdotdot))},
			"TraceArgsEndAgg":         {"untyped int", constant.MakeInt64(int64(q.TraceArgsEndAgg))},
			"TraceArgsEndSeq":         {"untyped int", constant.MakeInt64(int64(q.TraceArgsEndSeq))},
			"TraceArgsLimit":          {"untyped int", constant.MakeInt64(int64(q.TraceArgsLimit))},
			"TraceArgsMaxDepth":       {"untyped int", constant.MakeInt64(int64(q.TraceArgsMaxDepth))},
			"TraceArgsMaxLen":         {"untyped int", constant.MakeInt64(int64(q.TraceArgsMaxLen))},
			"TraceArgsOffsetTooLarge": {"untyped int", constant.MakeInt64(int64(q.TraceArgsOffsetTooLarge))},
			"TraceArgsSpecial":        {"untyped int", constant.MakeInt64(int64(q.TraceArgsSpecial))},
			"TraceArgsStartAgg":       {"untyped int", constant.MakeInt64(int64(q.TraceArgsStartAgg))},
		},
	})
}
