// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.26
// +build go1.26

package macho

import (
	q "debug/macho"

	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("debug/macho", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "macho",
			Path: "debug/macho",
			Deps: map[string]string{
				"bytes":            "bytes",
				"compress/zlib":    "zlib",
				"debug/dwarf":      "dwarf",
				"encoding/binary":  "binary",
				"fmt":              "fmt",
				"internal/saferio": "saferio",
				"io":               "io",
				"os":               "os",
				"strconv":          "strconv",
				"strings":          "strings",
			},
			Interfaces: map[string]reflect.Type{
				"Load": reflect.TypeOf((*q.Load)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Cpu":              reflect.TypeOf((*q.Cpu)(nil)).Elem(),
				"Dylib":            reflect.TypeOf((*q.Dylib)(nil)).Elem(),
				"DylibCmd":         reflect.TypeOf((*q.DylibCmd)(nil)).Elem(),
				"Dysymtab":         reflect.TypeOf((*q.Dysymtab)(nil)).Elem(),
				"DysymtabCmd":      reflect.TypeOf((*q.DysymtabCmd)(nil)).Elem(),
				"FatArch":          reflect.TypeOf((*q.FatArch)(nil)).Elem(),
				"FatArchHeader":    reflect.TypeOf((*q.FatArchHeader)(nil)).Elem(),
				"FatFile":          reflect.TypeOf((*q.FatFile)(nil)).Elem(),
				"File":             reflect.TypeOf((*q.File)(nil)).Elem(),
				"FileHeader":       reflect.TypeOf((*q.FileHeader)(nil)).Elem(),
				"FormatError":      reflect.TypeOf((*q.FormatError)(nil)).Elem(),
				"LoadBytes":        reflect.TypeOf((*q.LoadBytes)(nil)).Elem(),
				"LoadCmd":          reflect.TypeOf((*q.LoadCmd)(nil)).Elem(),
				"Nlist32":          reflect.TypeOf((*q.Nlist32)(nil)).Elem(),
				"Nlist64":          reflect.TypeOf((*q.Nlist64)(nil)).Elem(),
				"Regs386":          reflect.TypeOf((*q.Regs386)(nil)).Elem(),
				"RegsAMD64":        reflect.TypeOf((*q.RegsAMD64)(nil)).Elem(),
				"Reloc":            reflect.TypeOf((*q.Reloc)(nil)).Elem(),
				"RelocTypeARM":     reflect.TypeOf((*q.RelocTypeARM)(nil)).Elem(),
				"RelocTypeARM64":   reflect.TypeOf((*q.RelocTypeARM64)(nil)).Elem(),
				"RelocTypeGeneric": reflect.TypeOf((*q.RelocTypeGeneric)(nil)).Elem(),
				"RelocTypeX86_64":  reflect.TypeOf((*q.RelocTypeX86_64)(nil)).Elem(),
				"Rpath":            reflect.TypeOf((*q.Rpath)(nil)).Elem(),
				"RpathCmd":         reflect.TypeOf((*q.RpathCmd)(nil)).Elem(),
				"Section":          reflect.TypeOf((*q.Section)(nil)).Elem(),
				"Section32":        reflect.TypeOf((*q.Section32)(nil)).Elem(),
				"Section64":        reflect.TypeOf((*q.Section64)(nil)).Elem(),
				"SectionHeader":    reflect.TypeOf((*q.SectionHeader)(nil)).Elem(),
				"Segment":          reflect.TypeOf((*q.Segment)(nil)).Elem(),
				"Segment32":        reflect.TypeOf((*q.Segment32)(nil)).Elem(),
				"Segment64":        reflect.TypeOf((*q.Segment64)(nil)).Elem(),
				"SegmentHeader":    reflect.TypeOf((*q.SegmentHeader)(nil)).Elem(),
				"Symbol":           reflect.TypeOf((*q.Symbol)(nil)).Elem(),
				"Symtab":           reflect.TypeOf((*q.Symtab)(nil)).Elem(),
				"SymtabCmd":        reflect.TypeOf((*q.SymtabCmd)(nil)).Elem(),
				"Thread":           reflect.TypeOf((*q.Thread)(nil)).Elem(),
				"Type":             reflect.TypeOf((*q.Type)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]interface{}{
				"ErrNotFat": &q.ErrNotFat,
			},
			Funcs: map[string]interface{}{
				"NewFatFile": q.NewFatFile,
				"NewFile":    q.NewFile,
				"Open":       q.Open,
				"OpenFat":    q.OpenFat,
			},
			TypedConsts: map[string]interface{}{
				"ARM64_RELOC_ADDEND":              q.ARM64_RELOC_ADDEND,
				"ARM64_RELOC_BRANCH26":            q.ARM64_RELOC_BRANCH26,
				"ARM64_RELOC_GOT_LOAD_PAGE21":     q.ARM64_RELOC_GOT_LOAD_PAGE21,
				"ARM64_RELOC_GOT_LOAD_PAGEOFF12":  q.ARM64_RELOC_GOT_LOAD_PAGEOFF12,
				"ARM64_RELOC_PAGE21":              q.ARM64_RELOC_PAGE21,
				"ARM64_RELOC_PAGEOFF12":           q.ARM64_RELOC_PAGEOFF12,
				"ARM64_RELOC_POINTER_TO_GOT":      q.ARM64_RELOC_POINTER_TO_GOT,
				"ARM64_RELOC_SUBTRACTOR":          q.ARM64_RELOC_SUBTRACTOR,
				"ARM64_RELOC_TLVP_LOAD_PAGE21":    q.ARM64_RELOC_TLVP_LOAD_PAGE21,
				"ARM64_RELOC_TLVP_LOAD_PAGEOFF12": q.ARM64_RELOC_TLVP_LOAD_PAGEOFF12,
				"ARM64_RELOC_UNSIGNED":            q.ARM64_RELOC_UNSIGNED,
				"ARM_RELOC_BR24":                  q.ARM_RELOC_BR24,
				"ARM_RELOC_HALF":                  q.ARM_RELOC_HALF,
				"ARM_RELOC_HALF_SECTDIFF":         q.ARM_RELOC_HALF_SECTDIFF,
				"ARM_RELOC_LOCAL_SECTDIFF":        q.ARM_RELOC_LOCAL_SECTDIFF,
				"ARM_RELOC_PAIR":                  q.ARM_RELOC_PAIR,
				"ARM_RELOC_PB_LA_PTR":             q.ARM_RELOC_PB_LA_PTR,
				"ARM_RELOC_SECTDIFF":              q.ARM_RELOC_SECTDIFF,
				"ARM_RELOC_VANILLA":               q.ARM_RELOC_VANILLA,
				"ARM_THUMB_32BIT_BRANCH":          q.ARM_THUMB_32BIT_BRANCH,
				"ARM_THUMB_RELOC_BR22":            q.ARM_THUMB_RELOC_BR22,
				"Cpu386":                          q.Cpu386,
				"CpuAmd64":                        q.CpuAmd64,
				"CpuArm":                          q.CpuArm,
				"CpuArm64":                        q.CpuArm64,
				"CpuPpc":                          q.CpuPpc,
				"CpuPpc64":                        q.CpuPpc64,
				"FlagAllModsBound":                q.FlagAllModsBound,
				"FlagAllowStackExecution":         q.FlagAllowStackExecution,
				"FlagAppExtensionSafe":            q.FlagAppExtensionSafe,
				"FlagBindAtLoad":                  q.FlagBindAtLoad,
				"FlagBindsToWeak":                 q.FlagBindsToWeak,
				"FlagCanonical":                   q.FlagCanonical,
				"FlagDeadStrippableDylib":         q.FlagDeadStrippableDylib,
				"FlagDyldLink":                    q.FlagDyldLink,
				"FlagForceFlat":                   q.FlagForceFlat,
				"FlagHasTLVDescriptors":           q.FlagHasTLVDescriptors,
				"FlagIncrLink":                    q.FlagIncrLink,
				"FlagLazyInit":                    q.FlagLazyInit,
				"FlagNoFixPrebinding":             q.FlagNoFixPrebinding,
				"FlagNoHeapExecution":             q.FlagNoHeapExecution,
				"FlagNoMultiDefs":                 q.FlagNoMultiDefs,
				"FlagNoReexportedDylibs":          q.FlagNoReexportedDylibs,
				"FlagNoUndefs":                    q.FlagNoUndefs,
				"FlagPIE":                         q.FlagPIE,
				"FlagPrebindable":                 q.FlagPrebindable,
				"FlagPrebound":                    q.FlagPrebound,
				"FlagRootSafe":                    q.FlagRootSafe,
				"FlagSetuidSafe":                  q.FlagSetuidSafe,
				"FlagSplitSegs":                   q.FlagSplitSegs,
				"FlagSubsectionsViaSymbols":       q.FlagSubsectionsViaSymbols,
				"FlagTwoLevel":                    q.FlagTwoLevel,
				"FlagWeakDefines":                 q.FlagWeakDefines,
				"GENERIC_RELOC_LOCAL_SECTDIFF":    q.GENERIC_RELOC_LOCAL_SECTDIFF,
				"GENERIC_RELOC_PAIR":              q.GENERIC_RELOC_PAIR,
				"GENERIC_RELOC_PB_LA_PTR":         q.GENERIC_RELOC_PB_LA_PTR,
				"GENERIC_RELOC_SECTDIFF":          q.GENERIC_RELOC_SECTDIFF,
				"GENERIC_RELOC_TLV":               q.GENERIC_RELOC_TLV,
				"GENERIC_RELOC_VANILLA":           q.GENERIC_RELOC_VANILLA,
				"LoadCmdDylib":                    q.LoadCmdDylib,
				"LoadCmdDylinker":                 q.LoadCmdDylinker,
				"LoadCmdDysymtab":                 q.LoadCmdDysymtab,
				"LoadCmdRpath":                    q.LoadCmdRpath,
				"LoadCmdSegment":                  q.LoadCmdSegment,
				"LoadCmdSegment64":                q.LoadCmdSegment64,
				"LoadCmdSymtab":                   q.LoadCmdSymtab,
				"LoadCmdThread":                   q.LoadCmdThread,
				"LoadCmdUnixThread":               q.LoadCmdUnixThread,
				"Magic32":                         q.Magic32,
				"Magic64":                         q.Magic64,
				"MagicFat":                        q.MagicFat,
				"TypeBundle":                      q.TypeBundle,
				"TypeDylib":                       q.TypeDylib,
				"TypeExec":                        q.TypeExec,
				"TypeObj":                         q.TypeObj,
				"X86_64_RELOC_BRANCH":             q.X86_64_RELOC_BRANCH,
				"X86_64_RELOC_GOT":                q.X86_64_RELOC_GOT,
				"X86_64_RELOC_GOT_LOAD":           q.X86_64_RELOC_GOT_LOAD,
				"X86_64_RELOC_SIGNED":             q.X86_64_RELOC_SIGNED,
				"X86_64_RELOC_SIGNED_1":           q.X86_64_RELOC_SIGNED_1,
				"X86_64_RELOC_SIGNED_2":           q.X86_64_RELOC_SIGNED_2,
				"X86_64_RELOC_SIGNED_4":           q.X86_64_RELOC_SIGNED_4,
				"X86_64_RELOC_SUBTRACTOR":         q.X86_64_RELOC_SUBTRACTOR,
				"X86_64_RELOC_TLV":                q.X86_64_RELOC_TLV,
				"X86_64_RELOC_UNSIGNED":           q.X86_64_RELOC_UNSIGNED,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{},
		}
	})
}
