// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.24 && !go1.25
// +build go1.24,!go1.25

package macho

import (
	q "debug/macho"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackageLazy("debug/macho", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "macho",
			Path: "debug/macho",
			Deps: map[string]string{
				"bytes":            "bytes",
				"compress/zlib":    "zlib",
				"debug/dwarf":      "dwarf",
				"encoding/binary":  "binary",
				"fmt":              "fmt",
				"internal/saferio": "saferio",
				"io":               "io",
				"os":               "os",
				"strconv":          "strconv",
				"strings":          "strings",
			},
			Interfaces: map[string]reflect.Type{
				"Load": reflect.TypeOf((*q.Load)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"Cpu":              reflect.TypeOf((*q.Cpu)(nil)).Elem(),
				"Dylib":            reflect.TypeOf((*q.Dylib)(nil)).Elem(),
				"DylibCmd":         reflect.TypeOf((*q.DylibCmd)(nil)).Elem(),
				"Dysymtab":         reflect.TypeOf((*q.Dysymtab)(nil)).Elem(),
				"DysymtabCmd":      reflect.TypeOf((*q.DysymtabCmd)(nil)).Elem(),
				"FatArch":          reflect.TypeOf((*q.FatArch)(nil)).Elem(),
				"FatArchHeader":    reflect.TypeOf((*q.FatArchHeader)(nil)).Elem(),
				"FatFile":          reflect.TypeOf((*q.FatFile)(nil)).Elem(),
				"File":             reflect.TypeOf((*q.File)(nil)).Elem(),
				"FileHeader":       reflect.TypeOf((*q.FileHeader)(nil)).Elem(),
				"FormatError":      reflect.TypeOf((*q.FormatError)(nil)).Elem(),
				"LoadBytes":        reflect.TypeOf((*q.LoadBytes)(nil)).Elem(),
				"LoadCmd":          reflect.TypeOf((*q.LoadCmd)(nil)).Elem(),
				"Nlist32":          reflect.TypeOf((*q.Nlist32)(nil)).Elem(),
				"Nlist64":          reflect.TypeOf((*q.Nlist64)(nil)).Elem(),
				"Regs386":          reflect.TypeOf((*q.Regs386)(nil)).Elem(),
				"RegsAMD64":        reflect.TypeOf((*q.RegsAMD64)(nil)).Elem(),
				"Reloc":            reflect.TypeOf((*q.Reloc)(nil)).Elem(),
				"RelocTypeARM":     reflect.TypeOf((*q.RelocTypeARM)(nil)).Elem(),
				"RelocTypeARM64":   reflect.TypeOf((*q.RelocTypeARM64)(nil)).Elem(),
				"RelocTypeGeneric": reflect.TypeOf((*q.RelocTypeGeneric)(nil)).Elem(),
				"RelocTypeX86_64":  reflect.TypeOf((*q.RelocTypeX86_64)(nil)).Elem(),
				"Rpath":            reflect.TypeOf((*q.Rpath)(nil)).Elem(),
				"RpathCmd":         reflect.TypeOf((*q.RpathCmd)(nil)).Elem(),
				"Section":          reflect.TypeOf((*q.Section)(nil)).Elem(),
				"Section32":        reflect.TypeOf((*q.Section32)(nil)).Elem(),
				"Section64":        reflect.TypeOf((*q.Section64)(nil)).Elem(),
				"SectionHeader":    reflect.TypeOf((*q.SectionHeader)(nil)).Elem(),
				"Segment":          reflect.TypeOf((*q.Segment)(nil)).Elem(),
				"Segment32":        reflect.TypeOf((*q.Segment32)(nil)).Elem(),
				"Segment64":        reflect.TypeOf((*q.Segment64)(nil)).Elem(),
				"SegmentHeader":    reflect.TypeOf((*q.SegmentHeader)(nil)).Elem(),
				"Symbol":           reflect.TypeOf((*q.Symbol)(nil)).Elem(),
				"Symtab":           reflect.TypeOf((*q.Symtab)(nil)).Elem(),
				"SymtabCmd":        reflect.TypeOf((*q.SymtabCmd)(nil)).Elem(),
				"Thread":           reflect.TypeOf((*q.Thread)(nil)).Elem(),
				"Type":             reflect.TypeOf((*q.Type)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]reflect.Value{
				"ErrNotFat": reflect.ValueOf(&q.ErrNotFat),
			},
			Funcs: map[string]reflect.Value{
				"NewFatFile": reflect.ValueOf(q.NewFatFile),
				"NewFile":    reflect.ValueOf(q.NewFile),
				"Open":       reflect.ValueOf(q.Open),
				"OpenFat":    reflect.ValueOf(q.OpenFat),
			},
			TypedConsts: map[string]ixgo.TypedConst{
				"ARM64_RELOC_ADDEND":              {Typ: reflect.TypeOf(q.ARM64_RELOC_ADDEND), Value: constant.MakeInt64(int64(q.ARM64_RELOC_ADDEND))},
				"ARM64_RELOC_BRANCH26":            {Typ: reflect.TypeOf(q.ARM64_RELOC_BRANCH26), Value: constant.MakeInt64(int64(q.ARM64_RELOC_BRANCH26))},
				"ARM64_RELOC_GOT_LOAD_PAGE21":     {Typ: reflect.TypeOf(q.ARM64_RELOC_GOT_LOAD_PAGE21), Value: constant.MakeInt64(int64(q.ARM64_RELOC_GOT_LOAD_PAGE21))},
				"ARM64_RELOC_GOT_LOAD_PAGEOFF12":  {Typ: reflect.TypeOf(q.ARM64_RELOC_GOT_LOAD_PAGEOFF12), Value: constant.MakeInt64(int64(q.ARM64_RELOC_GOT_LOAD_PAGEOFF12))},
				"ARM64_RELOC_PAGE21":              {Typ: reflect.TypeOf(q.ARM64_RELOC_PAGE21), Value: constant.MakeInt64(int64(q.ARM64_RELOC_PAGE21))},
				"ARM64_RELOC_PAGEOFF12":           {Typ: reflect.TypeOf(q.ARM64_RELOC_PAGEOFF12), Value: constant.MakeInt64(int64(q.ARM64_RELOC_PAGEOFF12))},
				"ARM64_RELOC_POINTER_TO_GOT":      {Typ: reflect.TypeOf(q.ARM64_RELOC_POINTER_TO_GOT), Value: constant.MakeInt64(int64(q.ARM64_RELOC_POINTER_TO_GOT))},
				"ARM64_RELOC_SUBTRACTOR":          {Typ: reflect.TypeOf(q.ARM64_RELOC_SUBTRACTOR), Value: constant.MakeInt64(int64(q.ARM64_RELOC_SUBTRACTOR))},
				"ARM64_RELOC_TLVP_LOAD_PAGE21":    {Typ: reflect.TypeOf(q.ARM64_RELOC_TLVP_LOAD_PAGE21), Value: constant.MakeInt64(int64(q.ARM64_RELOC_TLVP_LOAD_PAGE21))},
				"ARM64_RELOC_TLVP_LOAD_PAGEOFF12": {Typ: reflect.TypeOf(q.ARM64_RELOC_TLVP_LOAD_PAGEOFF12), Value: constant.MakeInt64(int64(q.ARM64_RELOC_TLVP_LOAD_PAGEOFF12))},
				"ARM64_RELOC_UNSIGNED":            {Typ: reflect.TypeOf(q.ARM64_RELOC_UNSIGNED), Value: constant.MakeInt64(int64(q.ARM64_RELOC_UNSIGNED))},
				"ARM_RELOC_BR24":                  {Typ: reflect.TypeOf(q.ARM_RELOC_BR24), Value: constant.MakeInt64(int64(q.ARM_RELOC_BR24))},
				"ARM_RELOC_HALF":                  {Typ: reflect.TypeOf(q.ARM_RELOC_HALF), Value: constant.MakeInt64(int64(q.ARM_RELOC_HALF))},
				"ARM_RELOC_HALF_SECTDIFF":         {Typ: reflect.TypeOf(q.ARM_RELOC_HALF_SECTDIFF), Value: constant.MakeInt64(int64(q.ARM_RELOC_HALF_SECTDIFF))},
				"ARM_RELOC_LOCAL_SECTDIFF":        {Typ: reflect.TypeOf(q.ARM_RELOC_LOCAL_SECTDIFF), Value: constant.MakeInt64(int64(q.ARM_RELOC_LOCAL_SECTDIFF))},
				"ARM_RELOC_PAIR":                  {Typ: reflect.TypeOf(q.ARM_RELOC_PAIR), Value: constant.MakeInt64(int64(q.ARM_RELOC_PAIR))},
				"ARM_RELOC_PB_LA_PTR":             {Typ: reflect.TypeOf(q.ARM_RELOC_PB_LA_PTR), Value: constant.MakeInt64(int64(q.ARM_RELOC_PB_LA_PTR))},
				"ARM_RELOC_SECTDIFF":              {Typ: reflect.TypeOf(q.ARM_RELOC_SECTDIFF), Value: constant.MakeInt64(int64(q.ARM_RELOC_SECTDIFF))},
				"ARM_RELOC_VANILLA":               {Typ: reflect.TypeOf(q.ARM_RELOC_VANILLA), Value: constant.MakeInt64(int64(q.ARM_RELOC_VANILLA))},
				"ARM_THUMB_32BIT_BRANCH":          {Typ: reflect.TypeOf(q.ARM_THUMB_32BIT_BRANCH), Value: constant.MakeInt64(int64(q.ARM_THUMB_32BIT_BRANCH))},
				"ARM_THUMB_RELOC_BR22":            {Typ: reflect.TypeOf(q.ARM_THUMB_RELOC_BR22), Value: constant.MakeInt64(int64(q.ARM_THUMB_RELOC_BR22))},
				"Cpu386":                          {Typ: reflect.TypeOf(q.Cpu386), Value: constant.MakeInt64(int64(q.Cpu386))},
				"CpuAmd64":                        {Typ: reflect.TypeOf(q.CpuAmd64), Value: constant.MakeInt64(int64(q.CpuAmd64))},
				"CpuArm":                          {Typ: reflect.TypeOf(q.CpuArm), Value: constant.MakeInt64(int64(q.CpuArm))},
				"CpuArm64":                        {Typ: reflect.TypeOf(q.CpuArm64), Value: constant.MakeInt64(int64(q.CpuArm64))},
				"CpuPpc":                          {Typ: reflect.TypeOf(q.CpuPpc), Value: constant.MakeInt64(int64(q.CpuPpc))},
				"CpuPpc64":                        {Typ: reflect.TypeOf(q.CpuPpc64), Value: constant.MakeInt64(int64(q.CpuPpc64))},
				"FlagAllModsBound":                {Typ: reflect.TypeOf(q.FlagAllModsBound), Value: constant.MakeInt64(int64(q.FlagAllModsBound))},
				"FlagAllowStackExecution":         {Typ: reflect.TypeOf(q.FlagAllowStackExecution), Value: constant.MakeInt64(int64(q.FlagAllowStackExecution))},
				"FlagAppExtensionSafe":            {Typ: reflect.TypeOf(q.FlagAppExtensionSafe), Value: constant.MakeInt64(int64(q.FlagAppExtensionSafe))},
				"FlagBindAtLoad":                  {Typ: reflect.TypeOf(q.FlagBindAtLoad), Value: constant.MakeInt64(int64(q.FlagBindAtLoad))},
				"FlagBindsToWeak":                 {Typ: reflect.TypeOf(q.FlagBindsToWeak), Value: constant.MakeInt64(int64(q.FlagBindsToWeak))},
				"FlagCanonical":                   {Typ: reflect.TypeOf(q.FlagCanonical), Value: constant.MakeInt64(int64(q.FlagCanonical))},
				"FlagDeadStrippableDylib":         {Typ: reflect.TypeOf(q.FlagDeadStrippableDylib), Value: constant.MakeInt64(int64(q.FlagDeadStrippableDylib))},
				"FlagDyldLink":                    {Typ: reflect.TypeOf(q.FlagDyldLink), Value: constant.MakeInt64(int64(q.FlagDyldLink))},
				"FlagForceFlat":                   {Typ: reflect.TypeOf(q.FlagForceFlat), Value: constant.MakeInt64(int64(q.FlagForceFlat))},
				"FlagHasTLVDescriptors":           {Typ: reflect.TypeOf(q.FlagHasTLVDescriptors), Value: constant.MakeInt64(int64(q.FlagHasTLVDescriptors))},
				"FlagIncrLink":                    {Typ: reflect.TypeOf(q.FlagIncrLink), Value: constant.MakeInt64(int64(q.FlagIncrLink))},
				"FlagLazyInit":                    {Typ: reflect.TypeOf(q.FlagLazyInit), Value: constant.MakeInt64(int64(q.FlagLazyInit))},
				"FlagNoFixPrebinding":             {Typ: reflect.TypeOf(q.FlagNoFixPrebinding), Value: constant.MakeInt64(int64(q.FlagNoFixPrebinding))},
				"FlagNoHeapExecution":             {Typ: reflect.TypeOf(q.FlagNoHeapExecution), Value: constant.MakeInt64(int64(q.FlagNoHeapExecution))},
				"FlagNoMultiDefs":                 {Typ: reflect.TypeOf(q.FlagNoMultiDefs), Value: constant.MakeInt64(int64(q.FlagNoMultiDefs))},
				"FlagNoReexportedDylibs":          {Typ: reflect.TypeOf(q.FlagNoReexportedDylibs), Value: constant.MakeInt64(int64(q.FlagNoReexportedDylibs))},
				"FlagNoUndefs":                    {Typ: reflect.TypeOf(q.FlagNoUndefs), Value: constant.MakeInt64(int64(q.FlagNoUndefs))},
				"FlagPIE":                         {Typ: reflect.TypeOf(q.FlagPIE), Value: constant.MakeInt64(int64(q.FlagPIE))},
				"FlagPrebindable":                 {Typ: reflect.TypeOf(q.FlagPrebindable), Value: constant.MakeInt64(int64(q.FlagPrebindable))},
				"FlagPrebound":                    {Typ: reflect.TypeOf(q.FlagPrebound), Value: constant.MakeInt64(int64(q.FlagPrebound))},
				"FlagRootSafe":                    {Typ: reflect.TypeOf(q.FlagRootSafe), Value: constant.MakeInt64(int64(q.FlagRootSafe))},
				"FlagSetuidSafe":                  {Typ: reflect.TypeOf(q.FlagSetuidSafe), Value: constant.MakeInt64(int64(q.FlagSetuidSafe))},
				"FlagSplitSegs":                   {Typ: reflect.TypeOf(q.FlagSplitSegs), Value: constant.MakeInt64(int64(q.FlagSplitSegs))},
				"FlagSubsectionsViaSymbols":       {Typ: reflect.TypeOf(q.FlagSubsectionsViaSymbols), Value: constant.MakeInt64(int64(q.FlagSubsectionsViaSymbols))},
				"FlagTwoLevel":                    {Typ: reflect.TypeOf(q.FlagTwoLevel), Value: constant.MakeInt64(int64(q.FlagTwoLevel))},
				"FlagWeakDefines":                 {Typ: reflect.TypeOf(q.FlagWeakDefines), Value: constant.MakeInt64(int64(q.FlagWeakDefines))},
				"GENERIC_RELOC_LOCAL_SECTDIFF":    {Typ: reflect.TypeOf(q.GENERIC_RELOC_LOCAL_SECTDIFF), Value: constant.MakeInt64(int64(q.GENERIC_RELOC_LOCAL_SECTDIFF))},
				"GENERIC_RELOC_PAIR":              {Typ: reflect.TypeOf(q.GENERIC_RELOC_PAIR), Value: constant.MakeInt64(int64(q.GENERIC_RELOC_PAIR))},
				"GENERIC_RELOC_PB_LA_PTR":         {Typ: reflect.TypeOf(q.GENERIC_RELOC_PB_LA_PTR), Value: constant.MakeInt64(int64(q.GENERIC_RELOC_PB_LA_PTR))},
				"GENERIC_RELOC_SECTDIFF":          {Typ: reflect.TypeOf(q.GENERIC_RELOC_SECTDIFF), Value: constant.MakeInt64(int64(q.GENERIC_RELOC_SECTDIFF))},
				"GENERIC_RELOC_TLV":               {Typ: reflect.TypeOf(q.GENERIC_RELOC_TLV), Value: constant.MakeInt64(int64(q.GENERIC_RELOC_TLV))},
				"GENERIC_RELOC_VANILLA":           {Typ: reflect.TypeOf(q.GENERIC_RELOC_VANILLA), Value: constant.MakeInt64(int64(q.GENERIC_RELOC_VANILLA))},
				"LoadCmdDylib":                    {Typ: reflect.TypeOf(q.LoadCmdDylib), Value: constant.MakeInt64(int64(q.LoadCmdDylib))},
				"LoadCmdDylinker":                 {Typ: reflect.TypeOf(q.LoadCmdDylinker), Value: constant.MakeInt64(int64(q.LoadCmdDylinker))},
				"LoadCmdDysymtab":                 {Typ: reflect.TypeOf(q.LoadCmdDysymtab), Value: constant.MakeInt64(int64(q.LoadCmdDysymtab))},
				"LoadCmdRpath":                    {Typ: reflect.TypeOf(q.LoadCmdRpath), Value: constant.MakeInt64(int64(q.LoadCmdRpath))},
				"LoadCmdSegment":                  {Typ: reflect.TypeOf(q.LoadCmdSegment), Value: constant.MakeInt64(int64(q.LoadCmdSegment))},
				"LoadCmdSegment64":                {Typ: reflect.TypeOf(q.LoadCmdSegment64), Value: constant.MakeInt64(int64(q.LoadCmdSegment64))},
				"LoadCmdSymtab":                   {Typ: reflect.TypeOf(q.LoadCmdSymtab), Value: constant.MakeInt64(int64(q.LoadCmdSymtab))},
				"LoadCmdThread":                   {Typ: reflect.TypeOf(q.LoadCmdThread), Value: constant.MakeInt64(int64(q.LoadCmdThread))},
				"LoadCmdUnixThread":               {Typ: reflect.TypeOf(q.LoadCmdUnixThread), Value: constant.MakeInt64(int64(q.LoadCmdUnixThread))},
				"Magic32":                         {Typ: reflect.TypeOf(q.Magic32), Value: constant.MakeInt64(int64(q.Magic32))},
				"Magic64":                         {Typ: reflect.TypeOf(q.Magic64), Value: constant.MakeInt64(int64(q.Magic64))},
				"MagicFat":                        {Typ: reflect.TypeOf(q.MagicFat), Value: constant.MakeInt64(int64(q.MagicFat))},
				"TypeBundle":                      {Typ: reflect.TypeOf(q.TypeBundle), Value: constant.MakeInt64(int64(q.TypeBundle))},
				"TypeDylib":                       {Typ: reflect.TypeOf(q.TypeDylib), Value: constant.MakeInt64(int64(q.TypeDylib))},
				"TypeExec":                        {Typ: reflect.TypeOf(q.TypeExec), Value: constant.MakeInt64(int64(q.TypeExec))},
				"TypeObj":                         {Typ: reflect.TypeOf(q.TypeObj), Value: constant.MakeInt64(int64(q.TypeObj))},
				"X86_64_RELOC_BRANCH":             {Typ: reflect.TypeOf(q.X86_64_RELOC_BRANCH), Value: constant.MakeInt64(int64(q.X86_64_RELOC_BRANCH))},
				"X86_64_RELOC_GOT":                {Typ: reflect.TypeOf(q.X86_64_RELOC_GOT), Value: constant.MakeInt64(int64(q.X86_64_RELOC_GOT))},
				"X86_64_RELOC_GOT_LOAD":           {Typ: reflect.TypeOf(q.X86_64_RELOC_GOT_LOAD), Value: constant.MakeInt64(int64(q.X86_64_RELOC_GOT_LOAD))},
				"X86_64_RELOC_SIGNED":             {Typ: reflect.TypeOf(q.X86_64_RELOC_SIGNED), Value: constant.MakeInt64(int64(q.X86_64_RELOC_SIGNED))},
				"X86_64_RELOC_SIGNED_1":           {Typ: reflect.TypeOf(q.X86_64_RELOC_SIGNED_1), Value: constant.MakeInt64(int64(q.X86_64_RELOC_SIGNED_1))},
				"X86_64_RELOC_SIGNED_2":           {Typ: reflect.TypeOf(q.X86_64_RELOC_SIGNED_2), Value: constant.MakeInt64(int64(q.X86_64_RELOC_SIGNED_2))},
				"X86_64_RELOC_SIGNED_4":           {Typ: reflect.TypeOf(q.X86_64_RELOC_SIGNED_4), Value: constant.MakeInt64(int64(q.X86_64_RELOC_SIGNED_4))},
				"X86_64_RELOC_SUBTRACTOR":         {Typ: reflect.TypeOf(q.X86_64_RELOC_SUBTRACTOR), Value: constant.MakeInt64(int64(q.X86_64_RELOC_SUBTRACTOR))},
				"X86_64_RELOC_TLV":                {Typ: reflect.TypeOf(q.X86_64_RELOC_TLV), Value: constant.MakeInt64(int64(q.X86_64_RELOC_TLV))},
				"X86_64_RELOC_UNSIGNED":           {Typ: reflect.TypeOf(q.X86_64_RELOC_UNSIGNED), Value: constant.MakeInt64(int64(q.X86_64_RELOC_UNSIGNED))},
			},
			UntypedConsts: map[string]ixgo.UntypedConst{},
		}
	})
}
