// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.24 && !go1.25
// +build go1.24,!go1.25

package ast

import (
	q "go/ast"

	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("go/ast", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "ast",
			Path: "go/ast",
			Deps: map[string]string{
				"bytes":      "bytes",
				"cmp":        "cmp",
				"fmt":        "fmt",
				"go/scanner": "scanner",
				"go/token":   "token",
				"io":         "io",
				"iter":       "iter",
				"os":         "os",
				"reflect":    "reflect",
				"slices":     "slices",
				"strconv":    "strconv",
				"strings":    "strings",
			},
			Interfaces: map[string]reflect.Type{
				"Decl":    reflect.TypeOf((*q.Decl)(nil)).Elem(),
				"Expr":    reflect.TypeOf((*q.Expr)(nil)).Elem(),
				"Node":    reflect.TypeOf((*q.Node)(nil)).Elem(),
				"Spec":    reflect.TypeOf((*q.Spec)(nil)).Elem(),
				"Stmt":    reflect.TypeOf((*q.Stmt)(nil)).Elem(),
				"Visitor": reflect.TypeOf((*q.Visitor)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"ArrayType":      reflect.TypeOf((*q.ArrayType)(nil)).Elem(),
				"AssignStmt":     reflect.TypeOf((*q.AssignStmt)(nil)).Elem(),
				"BadDecl":        reflect.TypeOf((*q.BadDecl)(nil)).Elem(),
				"BadExpr":        reflect.TypeOf((*q.BadExpr)(nil)).Elem(),
				"BadStmt":        reflect.TypeOf((*q.BadStmt)(nil)).Elem(),
				"BasicLit":       reflect.TypeOf((*q.BasicLit)(nil)).Elem(),
				"BinaryExpr":     reflect.TypeOf((*q.BinaryExpr)(nil)).Elem(),
				"BlockStmt":      reflect.TypeOf((*q.BlockStmt)(nil)).Elem(),
				"BranchStmt":     reflect.TypeOf((*q.BranchStmt)(nil)).Elem(),
				"CallExpr":       reflect.TypeOf((*q.CallExpr)(nil)).Elem(),
				"CaseClause":     reflect.TypeOf((*q.CaseClause)(nil)).Elem(),
				"ChanDir":        reflect.TypeOf((*q.ChanDir)(nil)).Elem(),
				"ChanType":       reflect.TypeOf((*q.ChanType)(nil)).Elem(),
				"CommClause":     reflect.TypeOf((*q.CommClause)(nil)).Elem(),
				"Comment":        reflect.TypeOf((*q.Comment)(nil)).Elem(),
				"CommentGroup":   reflect.TypeOf((*q.CommentGroup)(nil)).Elem(),
				"CommentMap":     reflect.TypeOf((*q.CommentMap)(nil)).Elem(),
				"CompositeLit":   reflect.TypeOf((*q.CompositeLit)(nil)).Elem(),
				"DeclStmt":       reflect.TypeOf((*q.DeclStmt)(nil)).Elem(),
				"DeferStmt":      reflect.TypeOf((*q.DeferStmt)(nil)).Elem(),
				"Ellipsis":       reflect.TypeOf((*q.Ellipsis)(nil)).Elem(),
				"EmptyStmt":      reflect.TypeOf((*q.EmptyStmt)(nil)).Elem(),
				"ExprStmt":       reflect.TypeOf((*q.ExprStmt)(nil)).Elem(),
				"Field":          reflect.TypeOf((*q.Field)(nil)).Elem(),
				"FieldFilter":    reflect.TypeOf((*q.FieldFilter)(nil)).Elem(),
				"FieldList":      reflect.TypeOf((*q.FieldList)(nil)).Elem(),
				"File":           reflect.TypeOf((*q.File)(nil)).Elem(),
				"Filter":         reflect.TypeOf((*q.Filter)(nil)).Elem(),
				"ForStmt":        reflect.TypeOf((*q.ForStmt)(nil)).Elem(),
				"FuncDecl":       reflect.TypeOf((*q.FuncDecl)(nil)).Elem(),
				"FuncLit":        reflect.TypeOf((*q.FuncLit)(nil)).Elem(),
				"FuncType":       reflect.TypeOf((*q.FuncType)(nil)).Elem(),
				"GenDecl":        reflect.TypeOf((*q.GenDecl)(nil)).Elem(),
				"GoStmt":         reflect.TypeOf((*q.GoStmt)(nil)).Elem(),
				"Ident":          reflect.TypeOf((*q.Ident)(nil)).Elem(),
				"IfStmt":         reflect.TypeOf((*q.IfStmt)(nil)).Elem(),
				"ImportSpec":     reflect.TypeOf((*q.ImportSpec)(nil)).Elem(),
				"Importer":       reflect.TypeOf((*q.Importer)(nil)).Elem(),
				"IncDecStmt":     reflect.TypeOf((*q.IncDecStmt)(nil)).Elem(),
				"IndexExpr":      reflect.TypeOf((*q.IndexExpr)(nil)).Elem(),
				"IndexListExpr":  reflect.TypeOf((*q.IndexListExpr)(nil)).Elem(),
				"InterfaceType":  reflect.TypeOf((*q.InterfaceType)(nil)).Elem(),
				"KeyValueExpr":   reflect.TypeOf((*q.KeyValueExpr)(nil)).Elem(),
				"LabeledStmt":    reflect.TypeOf((*q.LabeledStmt)(nil)).Elem(),
				"MapType":        reflect.TypeOf((*q.MapType)(nil)).Elem(),
				"MergeMode":      reflect.TypeOf((*q.MergeMode)(nil)).Elem(),
				"ObjKind":        reflect.TypeOf((*q.ObjKind)(nil)).Elem(),
				"Object":         reflect.TypeOf((*q.Object)(nil)).Elem(),
				"Package":        reflect.TypeOf((*q.Package)(nil)).Elem(),
				"ParenExpr":      reflect.TypeOf((*q.ParenExpr)(nil)).Elem(),
				"RangeStmt":      reflect.TypeOf((*q.RangeStmt)(nil)).Elem(),
				"ReturnStmt":     reflect.TypeOf((*q.ReturnStmt)(nil)).Elem(),
				"Scope":          reflect.TypeOf((*q.Scope)(nil)).Elem(),
				"SelectStmt":     reflect.TypeOf((*q.SelectStmt)(nil)).Elem(),
				"SelectorExpr":   reflect.TypeOf((*q.SelectorExpr)(nil)).Elem(),
				"SendStmt":       reflect.TypeOf((*q.SendStmt)(nil)).Elem(),
				"SliceExpr":      reflect.TypeOf((*q.SliceExpr)(nil)).Elem(),
				"StarExpr":       reflect.TypeOf((*q.StarExpr)(nil)).Elem(),
				"StructType":     reflect.TypeOf((*q.StructType)(nil)).Elem(),
				"SwitchStmt":     reflect.TypeOf((*q.SwitchStmt)(nil)).Elem(),
				"TypeAssertExpr": reflect.TypeOf((*q.TypeAssertExpr)(nil)).Elem(),
				"TypeSpec":       reflect.TypeOf((*q.TypeSpec)(nil)).Elem(),
				"TypeSwitchStmt": reflect.TypeOf((*q.TypeSwitchStmt)(nil)).Elem(),
				"UnaryExpr":      reflect.TypeOf((*q.UnaryExpr)(nil)).Elem(),
				"ValueSpec":      reflect.TypeOf((*q.ValueSpec)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars:       map[string]interface{}{},
			Funcs: map[string]interface{}{
				"FileExports":       q.FileExports,
				"FilterDecl":        q.FilterDecl,
				"FilterFile":        q.FilterFile,
				"FilterPackage":     q.FilterPackage,
				"Fprint":            q.Fprint,
				"Inspect":           q.Inspect,
				"IsExported":        q.IsExported,
				"IsGenerated":       q.IsGenerated,
				"MergePackageFiles": q.MergePackageFiles,
				"NewCommentMap":     q.NewCommentMap,
				"NewIdent":          q.NewIdent,
				"NewObj":            q.NewObj,
				"NewPackage":        q.NewPackage,
				"NewScope":          q.NewScope,
				"NotNilFilter":      q.NotNilFilter,
				"PackageExports":    q.PackageExports,
				"Preorder":          q.Preorder,
				"Print":             q.Print,
				"SortImports":       q.SortImports,
				"Unparen":           q.Unparen,
				"Walk":              q.Walk,
			},
			TypedConsts: map[string]interface{}{
				"Bad":                        q.Bad,
				"Con":                        q.Con,
				"FilterFuncDuplicates":       q.FilterFuncDuplicates,
				"FilterImportDuplicates":     q.FilterImportDuplicates,
				"FilterUnassociatedComments": q.FilterUnassociatedComments,
				"Fun":                        q.Fun,
				"Lbl":                        q.Lbl,
				"Pkg":                        q.Pkg,
				"RECV":                       q.RECV,
				"SEND":                       q.SEND,
				"Typ":                        q.Typ,
				"Var":                        q.Var,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{},
		}
	})
}
