// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.25 && !go1.26
// +build go1.25,!go1.26

package dwarf

import (
	q "debug/dwarf"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackageLazy("debug/dwarf", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "dwarf",
			Path: "debug/dwarf",
			Deps: map[string]string{
				"bytes":           "bytes",
				"encoding/binary": "binary",
				"errors":          "errors",
				"fmt":             "fmt",
				"io":              "io",
				"path":            "path",
				"sort":            "sort",
				"strconv":         "strconv",
				"strings":         "strings",
			},
			Interfaces: map[string]reflect.Type{
				"Type": reflect.TypeOf((*q.Type)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"AddrType":        reflect.TypeOf((*q.AddrType)(nil)).Elem(),
				"ArrayType":       reflect.TypeOf((*q.ArrayType)(nil)).Elem(),
				"Attr":            reflect.TypeOf((*q.Attr)(nil)).Elem(),
				"BasicType":       reflect.TypeOf((*q.BasicType)(nil)).Elem(),
				"BoolType":        reflect.TypeOf((*q.BoolType)(nil)).Elem(),
				"CharType":        reflect.TypeOf((*q.CharType)(nil)).Elem(),
				"Class":           reflect.TypeOf((*q.Class)(nil)).Elem(),
				"CommonType":      reflect.TypeOf((*q.CommonType)(nil)).Elem(),
				"ComplexType":     reflect.TypeOf((*q.ComplexType)(nil)).Elem(),
				"Data":            reflect.TypeOf((*q.Data)(nil)).Elem(),
				"DecodeError":     reflect.TypeOf((*q.DecodeError)(nil)).Elem(),
				"DotDotDotType":   reflect.TypeOf((*q.DotDotDotType)(nil)).Elem(),
				"Entry":           reflect.TypeOf((*q.Entry)(nil)).Elem(),
				"EnumType":        reflect.TypeOf((*q.EnumType)(nil)).Elem(),
				"EnumValue":       reflect.TypeOf((*q.EnumValue)(nil)).Elem(),
				"Field":           reflect.TypeOf((*q.Field)(nil)).Elem(),
				"FloatType":       reflect.TypeOf((*q.FloatType)(nil)).Elem(),
				"FuncType":        reflect.TypeOf((*q.FuncType)(nil)).Elem(),
				"IntType":         reflect.TypeOf((*q.IntType)(nil)).Elem(),
				"LineEntry":       reflect.TypeOf((*q.LineEntry)(nil)).Elem(),
				"LineFile":        reflect.TypeOf((*q.LineFile)(nil)).Elem(),
				"LineReader":      reflect.TypeOf((*q.LineReader)(nil)).Elem(),
				"LineReaderPos":   reflect.TypeOf((*q.LineReaderPos)(nil)).Elem(),
				"Offset":          reflect.TypeOf((*q.Offset)(nil)).Elem(),
				"PtrType":         reflect.TypeOf((*q.PtrType)(nil)).Elem(),
				"QualType":        reflect.TypeOf((*q.QualType)(nil)).Elem(),
				"Reader":          reflect.TypeOf((*q.Reader)(nil)).Elem(),
				"StructField":     reflect.TypeOf((*q.StructField)(nil)).Elem(),
				"StructType":      reflect.TypeOf((*q.StructType)(nil)).Elem(),
				"Tag":             reflect.TypeOf((*q.Tag)(nil)).Elem(),
				"TypedefType":     reflect.TypeOf((*q.TypedefType)(nil)).Elem(),
				"UcharType":       reflect.TypeOf((*q.UcharType)(nil)).Elem(),
				"UintType":        reflect.TypeOf((*q.UintType)(nil)).Elem(),
				"UnspecifiedType": reflect.TypeOf((*q.UnspecifiedType)(nil)).Elem(),
				"UnsupportedType": reflect.TypeOf((*q.UnsupportedType)(nil)).Elem(),
				"VoidType":        reflect.TypeOf((*q.VoidType)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{},
			Vars: map[string]reflect.Value{
				"ErrUnknownPC": reflect.ValueOf(&q.ErrUnknownPC),
			},
			Funcs: map[string]reflect.Value{
				"New": reflect.ValueOf(q.New),
			},
			TypedConsts: map[string]ixgo.TypedConst{
				"AttrAbstractOrigin":        {Typ: reflect.TypeOf(q.AttrAbstractOrigin), Value: constant.MakeInt64(int64(q.AttrAbstractOrigin))},
				"AttrAccessibility":         {Typ: reflect.TypeOf(q.AttrAccessibility), Value: constant.MakeInt64(int64(q.AttrAccessibility))},
				"AttrAddrBase":              {Typ: reflect.TypeOf(q.AttrAddrBase), Value: constant.MakeInt64(int64(q.AttrAddrBase))},
				"AttrAddrClass":             {Typ: reflect.TypeOf(q.AttrAddrClass), Value: constant.MakeInt64(int64(q.AttrAddrClass))},
				"AttrAlignment":             {Typ: reflect.TypeOf(q.AttrAlignment), Value: constant.MakeInt64(int64(q.AttrAlignment))},
				"AttrAllocated":             {Typ: reflect.TypeOf(q.AttrAllocated), Value: constant.MakeInt64(int64(q.AttrAllocated))},
				"AttrArtificial":            {Typ: reflect.TypeOf(q.AttrArtificial), Value: constant.MakeInt64(int64(q.AttrArtificial))},
				"AttrAssociated":            {Typ: reflect.TypeOf(q.AttrAssociated), Value: constant.MakeInt64(int64(q.AttrAssociated))},
				"AttrBaseTypes":             {Typ: reflect.TypeOf(q.AttrBaseTypes), Value: constant.MakeInt64(int64(q.AttrBaseTypes))},
				"AttrBinaryScale":           {Typ: reflect.TypeOf(q.AttrBinaryScale), Value: constant.MakeInt64(int64(q.AttrBinaryScale))},
				"AttrBitOffset":             {Typ: reflect.TypeOf(q.AttrBitOffset), Value: constant.MakeInt64(int64(q.AttrBitOffset))},
				"AttrBitSize":               {Typ: reflect.TypeOf(q.AttrBitSize), Value: constant.MakeInt64(int64(q.AttrBitSize))},
				"AttrByteSize":              {Typ: reflect.TypeOf(q.AttrByteSize), Value: constant.MakeInt64(int64(q.AttrByteSize))},
				"AttrCallAllCalls":          {Typ: reflect.TypeOf(q.AttrCallAllCalls), Value: constant.MakeInt64(int64(q.AttrCallAllCalls))},
				"AttrCallAllSourceCalls":    {Typ: reflect.TypeOf(q.AttrCallAllSourceCalls), Value: constant.MakeInt64(int64(q.AttrCallAllSourceCalls))},
				"AttrCallAllTailCalls":      {Typ: reflect.TypeOf(q.AttrCallAllTailCalls), Value: constant.MakeInt64(int64(q.AttrCallAllTailCalls))},
				"AttrCallColumn":            {Typ: reflect.TypeOf(q.AttrCallColumn), Value: constant.MakeInt64(int64(q.AttrCallColumn))},
				"AttrCallDataLocation":      {Typ: reflect.TypeOf(q.AttrCallDataLocation), Value: constant.MakeInt64(int64(q.AttrCallDataLocation))},
				"AttrCallDataValue":         {Typ: reflect.TypeOf(q.AttrCallDataValue), Value: constant.MakeInt64(int64(q.AttrCallDataValue))},
				"AttrCallFile":              {Typ: reflect.TypeOf(q.AttrCallFile), Value: constant.MakeInt64(int64(q.AttrCallFile))},
				"AttrCallLine":              {Typ: reflect.TypeOf(q.AttrCallLine), Value: constant.MakeInt64(int64(q.AttrCallLine))},
				"AttrCallOrigin":            {Typ: reflect.TypeOf(q.AttrCallOrigin), Value: constant.MakeInt64(int64(q.AttrCallOrigin))},
				"AttrCallPC":                {Typ: reflect.TypeOf(q.AttrCallPC), Value: constant.MakeInt64(int64(q.AttrCallPC))},
				"AttrCallParameter":         {Typ: reflect.TypeOf(q.AttrCallParameter), Value: constant.MakeInt64(int64(q.AttrCallParameter))},
				"AttrCallReturnPC":          {Typ: reflect.TypeOf(q.AttrCallReturnPC), Value: constant.MakeInt64(int64(q.AttrCallReturnPC))},
				"AttrCallTailCall":          {Typ: reflect.TypeOf(q.AttrCallTailCall), Value: constant.MakeInt64(int64(q.AttrCallTailCall))},
				"AttrCallTarget":            {Typ: reflect.TypeOf(q.AttrCallTarget), Value: constant.MakeInt64(int64(q.AttrCallTarget))},
				"AttrCallTargetClobbered":   {Typ: reflect.TypeOf(q.AttrCallTargetClobbered), Value: constant.MakeInt64(int64(q.AttrCallTargetClobbered))},
				"AttrCallValue":             {Typ: reflect.TypeOf(q.AttrCallValue), Value: constant.MakeInt64(int64(q.AttrCallValue))},
				"AttrCalling":               {Typ: reflect.TypeOf(q.AttrCalling), Value: constant.MakeInt64(int64(q.AttrCalling))},
				"AttrCommonRef":             {Typ: reflect.TypeOf(q.AttrCommonRef), Value: constant.MakeInt64(int64(q.AttrCommonRef))},
				"AttrCompDir":               {Typ: reflect.TypeOf(q.AttrCompDir), Value: constant.MakeInt64(int64(q.AttrCompDir))},
				"AttrConstExpr":             {Typ: reflect.TypeOf(q.AttrConstExpr), Value: constant.MakeInt64(int64(q.AttrConstExpr))},
				"AttrConstValue":            {Typ: reflect.TypeOf(q.AttrConstValue), Value: constant.MakeInt64(int64(q.AttrConstValue))},
				"AttrContainingType":        {Typ: reflect.TypeOf(q.AttrContainingType), Value: constant.MakeInt64(int64(q.AttrContainingType))},
				"AttrCount":                 {Typ: reflect.TypeOf(q.AttrCount), Value: constant.MakeInt64(int64(q.AttrCount))},
				"AttrDataBitOffset":         {Typ: reflect.TypeOf(q.AttrDataBitOffset), Value: constant.MakeInt64(int64(q.AttrDataBitOffset))},
				"AttrDataLocation":          {Typ: reflect.TypeOf(q.AttrDataLocation), Value: constant.MakeInt64(int64(q.AttrDataLocation))},
				"AttrDataMemberLoc":         {Typ: reflect.TypeOf(q.AttrDataMemberLoc), Value: constant.MakeInt64(int64(q.AttrDataMemberLoc))},
				"AttrDecimalScale":          {Typ: reflect.TypeOf(q.AttrDecimalScale), Value: constant.MakeInt64(int64(q.AttrDecimalScale))},
				"AttrDecimalSign":           {Typ: reflect.TypeOf(q.AttrDecimalSign), Value: constant.MakeInt64(int64(q.AttrDecimalSign))},
				"AttrDeclColumn":            {Typ: reflect.TypeOf(q.AttrDeclColumn), Value: constant.MakeInt64(int64(q.AttrDeclColumn))},
				"AttrDeclFile":              {Typ: reflect.TypeOf(q.AttrDeclFile), Value: constant.MakeInt64(int64(q.AttrDeclFile))},
				"AttrDeclLine":              {Typ: reflect.TypeOf(q.AttrDeclLine), Value: constant.MakeInt64(int64(q.AttrDeclLine))},
				"AttrDeclaration":           {Typ: reflect.TypeOf(q.AttrDeclaration), Value: constant.MakeInt64(int64(q.AttrDeclaration))},
				"AttrDefaultValue":          {Typ: reflect.TypeOf(q.AttrDefaultValue), Value: constant.MakeInt64(int64(q.AttrDefaultValue))},
				"AttrDefaulted":             {Typ: reflect.TypeOf(q.AttrDefaulted), Value: constant.MakeInt64(int64(q.AttrDefaulted))},
				"AttrDeleted":               {Typ: reflect.TypeOf(q.AttrDeleted), Value: constant.MakeInt64(int64(q.AttrDeleted))},
				"AttrDescription":           {Typ: reflect.TypeOf(q.AttrDescription), Value: constant.MakeInt64(int64(q.AttrDescription))},
				"AttrDigitCount":            {Typ: reflect.TypeOf(q.AttrDigitCount), Value: constant.MakeInt64(int64(q.AttrDigitCount))},
				"AttrDiscr":                 {Typ: reflect.TypeOf(q.AttrDiscr), Value: constant.MakeInt64(int64(q.AttrDiscr))},
				"AttrDiscrList":             {Typ: reflect.TypeOf(q.AttrDiscrList), Value: constant.MakeInt64(int64(q.AttrDiscrList))},
				"AttrDiscrValue":            {Typ: reflect.TypeOf(q.AttrDiscrValue), Value: constant.MakeInt64(int64(q.AttrDiscrValue))},
				"AttrDwoName":               {Typ: reflect.TypeOf(q.AttrDwoName), Value: constant.MakeInt64(int64(q.AttrDwoName))},
				"AttrElemental":             {Typ: reflect.TypeOf(q.AttrElemental), Value: constant.MakeInt64(int64(q.AttrElemental))},
				"AttrEncoding":              {Typ: reflect.TypeOf(q.AttrEncoding), Value: constant.MakeInt64(int64(q.AttrEncoding))},
				"AttrEndianity":             {Typ: reflect.TypeOf(q.AttrEndianity), Value: constant.MakeInt64(int64(q.AttrEndianity))},
				"AttrEntrypc":               {Typ: reflect.TypeOf(q.AttrEntrypc), Value: constant.MakeInt64(int64(q.AttrEntrypc))},
				"AttrEnumClass":             {Typ: reflect.TypeOf(q.AttrEnumClass), Value: constant.MakeInt64(int64(q.AttrEnumClass))},
				"AttrExplicit":              {Typ: reflect.TypeOf(q.AttrExplicit), Value: constant.MakeInt64(int64(q.AttrExplicit))},
				"AttrExportSymbols":         {Typ: reflect.TypeOf(q.AttrExportSymbols), Value: constant.MakeInt64(int64(q.AttrExportSymbols))},
				"AttrExtension":             {Typ: reflect.TypeOf(q.AttrExtension), Value: constant.MakeInt64(int64(q.AttrExtension))},
				"AttrExternal":              {Typ: reflect.TypeOf(q.AttrExternal), Value: constant.MakeInt64(int64(q.AttrExternal))},
				"AttrFrameBase":             {Typ: reflect.TypeOf(q.AttrFrameBase), Value: constant.MakeInt64(int64(q.AttrFrameBase))},
				"AttrFriend":                {Typ: reflect.TypeOf(q.AttrFriend), Value: constant.MakeInt64(int64(q.AttrFriend))},
				"AttrHighpc":                {Typ: reflect.TypeOf(q.AttrHighpc), Value: constant.MakeInt64(int64(q.AttrHighpc))},
				"AttrIdentifierCase":        {Typ: reflect.TypeOf(q.AttrIdentifierCase), Value: constant.MakeInt64(int64(q.AttrIdentifierCase))},
				"AttrImport":                {Typ: reflect.TypeOf(q.AttrImport), Value: constant.MakeInt64(int64(q.AttrImport))},
				"AttrInline":                {Typ: reflect.TypeOf(q.AttrInline), Value: constant.MakeInt64(int64(q.AttrInline))},
				"AttrIsOptional":            {Typ: reflect.TypeOf(q.AttrIsOptional), Value: constant.MakeInt64(int64(q.AttrIsOptional))},
				"AttrLanguage":              {Typ: reflect.TypeOf(q.AttrLanguage), Value: constant.MakeInt64(int64(q.AttrLanguage))},
				"AttrLinkageName":           {Typ: reflect.TypeOf(q.AttrLinkageName), Value: constant.MakeInt64(int64(q.AttrLinkageName))},
				"AttrLocation":              {Typ: reflect.TypeOf(q.AttrLocation), Value: constant.MakeInt64(int64(q.AttrLocation))},
				"AttrLoclistsBase":          {Typ: reflect.TypeOf(q.AttrLoclistsBase), Value: constant.MakeInt64(int64(q.AttrLoclistsBase))},
				"AttrLowerBound":            {Typ: reflect.TypeOf(q.AttrLowerBound), Value: constant.MakeInt64(int64(q.AttrLowerBound))},
				"AttrLowpc":                 {Typ: reflect.TypeOf(q.AttrLowpc), Value: constant.MakeInt64(int64(q.AttrLowpc))},
				"AttrMacroInfo":             {Typ: reflect.TypeOf(q.AttrMacroInfo), Value: constant.MakeInt64(int64(q.AttrMacroInfo))},
				"AttrMacros":                {Typ: reflect.TypeOf(q.AttrMacros), Value: constant.MakeInt64(int64(q.AttrMacros))},
				"AttrMainSubprogram":        {Typ: reflect.TypeOf(q.AttrMainSubprogram), Value: constant.MakeInt64(int64(q.AttrMainSubprogram))},
				"AttrMutable":               {Typ: reflect.TypeOf(q.AttrMutable), Value: constant.MakeInt64(int64(q.AttrMutable))},
				"AttrName":                  {Typ: reflect.TypeOf(q.AttrName), Value: constant.MakeInt64(int64(q.AttrName))},
				"AttrNamelistItem":          {Typ: reflect.TypeOf(q.AttrNamelistItem), Value: constant.MakeInt64(int64(q.AttrNamelistItem))},
				"AttrNoreturn":              {Typ: reflect.TypeOf(q.AttrNoreturn), Value: constant.MakeInt64(int64(q.AttrNoreturn))},
				"AttrObjectPointer":         {Typ: reflect.TypeOf(q.AttrObjectPointer), Value: constant.MakeInt64(int64(q.AttrObjectPointer))},
				"AttrOrdering":              {Typ: reflect.TypeOf(q.AttrOrdering), Value: constant.MakeInt64(int64(q.AttrOrdering))},
				"AttrPictureString":         {Typ: reflect.TypeOf(q.AttrPictureString), Value: constant.MakeInt64(int64(q.AttrPictureString))},
				"AttrPriority":              {Typ: reflect.TypeOf(q.AttrPriority), Value: constant.MakeInt64(int64(q.AttrPriority))},
				"AttrProducer":              {Typ: reflect.TypeOf(q.AttrProducer), Value: constant.MakeInt64(int64(q.AttrProducer))},
				"AttrPrototyped":            {Typ: reflect.TypeOf(q.AttrPrototyped), Value: constant.MakeInt64(int64(q.AttrPrototyped))},
				"AttrPure":                  {Typ: reflect.TypeOf(q.AttrPure), Value: constant.MakeInt64(int64(q.AttrPure))},
				"AttrRanges":                {Typ: reflect.TypeOf(q.AttrRanges), Value: constant.MakeInt64(int64(q.AttrRanges))},
				"AttrRank":                  {Typ: reflect.TypeOf(q.AttrRank), Value: constant.MakeInt64(int64(q.AttrRank))},
				"AttrRecursive":             {Typ: reflect.TypeOf(q.AttrRecursive), Value: constant.MakeInt64(int64(q.AttrRecursive))},
				"AttrReference":             {Typ: reflect.TypeOf(q.AttrReference), Value: constant.MakeInt64(int64(q.AttrReference))},
				"AttrReturnAddr":            {Typ: reflect.TypeOf(q.AttrReturnAddr), Value: constant.MakeInt64(int64(q.AttrReturnAddr))},
				"AttrRnglistsBase":          {Typ: reflect.TypeOf(q.AttrRnglistsBase), Value: constant.MakeInt64(int64(q.AttrRnglistsBase))},
				"AttrRvalueReference":       {Typ: reflect.TypeOf(q.AttrRvalueReference), Value: constant.MakeInt64(int64(q.AttrRvalueReference))},
				"AttrSegment":               {Typ: reflect.TypeOf(q.AttrSegment), Value: constant.MakeInt64(int64(q.AttrSegment))},
				"AttrSibling":               {Typ: reflect.TypeOf(q.AttrSibling), Value: constant.MakeInt64(int64(q.AttrSibling))},
				"AttrSignature":             {Typ: reflect.TypeOf(q.AttrSignature), Value: constant.MakeInt64(int64(q.AttrSignature))},
				"AttrSmall":                 {Typ: reflect.TypeOf(q.AttrSmall), Value: constant.MakeInt64(int64(q.AttrSmall))},
				"AttrSpecification":         {Typ: reflect.TypeOf(q.AttrSpecification), Value: constant.MakeInt64(int64(q.AttrSpecification))},
				"AttrStartScope":            {Typ: reflect.TypeOf(q.AttrStartScope), Value: constant.MakeInt64(int64(q.AttrStartScope))},
				"AttrStaticLink":            {Typ: reflect.TypeOf(q.AttrStaticLink), Value: constant.MakeInt64(int64(q.AttrStaticLink))},
				"AttrStmtList":              {Typ: reflect.TypeOf(q.AttrStmtList), Value: constant.MakeInt64(int64(q.AttrStmtList))},
				"AttrStrOffsetsBase":        {Typ: reflect.TypeOf(q.AttrStrOffsetsBase), Value: constant.MakeInt64(int64(q.AttrStrOffsetsBase))},
				"AttrStride":                {Typ: reflect.TypeOf(q.AttrStride), Value: constant.MakeInt64(int64(q.AttrStride))},
				"AttrStrideSize":            {Typ: reflect.TypeOf(q.AttrStrideSize), Value: constant.MakeInt64(int64(q.AttrStrideSize))},
				"AttrStringLength":          {Typ: reflect.TypeOf(q.AttrStringLength), Value: constant.MakeInt64(int64(q.AttrStringLength))},
				"AttrStringLengthBitSize":   {Typ: reflect.TypeOf(q.AttrStringLengthBitSize), Value: constant.MakeInt64(int64(q.AttrStringLengthBitSize))},
				"AttrStringLengthByteSize":  {Typ: reflect.TypeOf(q.AttrStringLengthByteSize), Value: constant.MakeInt64(int64(q.AttrStringLengthByteSize))},
				"AttrThreadsScaled":         {Typ: reflect.TypeOf(q.AttrThreadsScaled), Value: constant.MakeInt64(int64(q.AttrThreadsScaled))},
				"AttrTrampoline":            {Typ: reflect.TypeOf(q.AttrTrampoline), Value: constant.MakeInt64(int64(q.AttrTrampoline))},
				"AttrType":                  {Typ: reflect.TypeOf(q.AttrType), Value: constant.MakeInt64(int64(q.AttrType))},
				"AttrUpperBound":            {Typ: reflect.TypeOf(q.AttrUpperBound), Value: constant.MakeInt64(int64(q.AttrUpperBound))},
				"AttrUseLocation":           {Typ: reflect.TypeOf(q.AttrUseLocation), Value: constant.MakeInt64(int64(q.AttrUseLocation))},
				"AttrUseUTF8":               {Typ: reflect.TypeOf(q.AttrUseUTF8), Value: constant.MakeInt64(int64(q.AttrUseUTF8))},
				"AttrVarParam":              {Typ: reflect.TypeOf(q.AttrVarParam), Value: constant.MakeInt64(int64(q.AttrVarParam))},
				"AttrVirtuality":            {Typ: reflect.TypeOf(q.AttrVirtuality), Value: constant.MakeInt64(int64(q.AttrVirtuality))},
				"AttrVisibility":            {Typ: reflect.TypeOf(q.AttrVisibility), Value: constant.MakeInt64(int64(q.AttrVisibility))},
				"AttrVtableElemLoc":         {Typ: reflect.TypeOf(q.AttrVtableElemLoc), Value: constant.MakeInt64(int64(q.AttrVtableElemLoc))},
				"ClassAddrPtr":              {Typ: reflect.TypeOf(q.ClassAddrPtr), Value: constant.MakeInt64(int64(q.ClassAddrPtr))},
				"ClassAddress":              {Typ: reflect.TypeOf(q.ClassAddress), Value: constant.MakeInt64(int64(q.ClassAddress))},
				"ClassBlock":                {Typ: reflect.TypeOf(q.ClassBlock), Value: constant.MakeInt64(int64(q.ClassBlock))},
				"ClassConstant":             {Typ: reflect.TypeOf(q.ClassConstant), Value: constant.MakeInt64(int64(q.ClassConstant))},
				"ClassExprLoc":              {Typ: reflect.TypeOf(q.ClassExprLoc), Value: constant.MakeInt64(int64(q.ClassExprLoc))},
				"ClassFlag":                 {Typ: reflect.TypeOf(q.ClassFlag), Value: constant.MakeInt64(int64(q.ClassFlag))},
				"ClassLinePtr":              {Typ: reflect.TypeOf(q.ClassLinePtr), Value: constant.MakeInt64(int64(q.ClassLinePtr))},
				"ClassLocList":              {Typ: reflect.TypeOf(q.ClassLocList), Value: constant.MakeInt64(int64(q.ClassLocList))},
				"ClassLocListPtr":           {Typ: reflect.TypeOf(q.ClassLocListPtr), Value: constant.MakeInt64(int64(q.ClassLocListPtr))},
				"ClassMacPtr":               {Typ: reflect.TypeOf(q.ClassMacPtr), Value: constant.MakeInt64(int64(q.ClassMacPtr))},
				"ClassRangeListPtr":         {Typ: reflect.TypeOf(q.ClassRangeListPtr), Value: constant.MakeInt64(int64(q.ClassRangeListPtr))},
				"ClassReference":            {Typ: reflect.TypeOf(q.ClassReference), Value: constant.MakeInt64(int64(q.ClassReference))},
				"ClassReferenceAlt":         {Typ: reflect.TypeOf(q.ClassReferenceAlt), Value: constant.MakeInt64(int64(q.ClassReferenceAlt))},
				"ClassReferenceSig":         {Typ: reflect.TypeOf(q.ClassReferenceSig), Value: constant.MakeInt64(int64(q.ClassReferenceSig))},
				"ClassRngList":              {Typ: reflect.TypeOf(q.ClassRngList), Value: constant.MakeInt64(int64(q.ClassRngList))},
				"ClassRngListsPtr":          {Typ: reflect.TypeOf(q.ClassRngListsPtr), Value: constant.MakeInt64(int64(q.ClassRngListsPtr))},
				"ClassStrOffsetsPtr":        {Typ: reflect.TypeOf(q.ClassStrOffsetsPtr), Value: constant.MakeInt64(int64(q.ClassStrOffsetsPtr))},
				"ClassString":               {Typ: reflect.TypeOf(q.ClassString), Value: constant.MakeInt64(int64(q.ClassString))},
				"ClassStringAlt":            {Typ: reflect.TypeOf(q.ClassStringAlt), Value: constant.MakeInt64(int64(q.ClassStringAlt))},
				"ClassUnknown":              {Typ: reflect.TypeOf(q.ClassUnknown), Value: constant.MakeInt64(int64(q.ClassUnknown))},
				"TagAccessDeclaration":      {Typ: reflect.TypeOf(q.TagAccessDeclaration), Value: constant.MakeInt64(int64(q.TagAccessDeclaration))},
				"TagArrayType":              {Typ: reflect.TypeOf(q.TagArrayType), Value: constant.MakeInt64(int64(q.TagArrayType))},
				"TagAtomicType":             {Typ: reflect.TypeOf(q.TagAtomicType), Value: constant.MakeInt64(int64(q.TagAtomicType))},
				"TagBaseType":               {Typ: reflect.TypeOf(q.TagBaseType), Value: constant.MakeInt64(int64(q.TagBaseType))},
				"TagCallSite":               {Typ: reflect.TypeOf(q.TagCallSite), Value: constant.MakeInt64(int64(q.TagCallSite))},
				"TagCallSiteParameter":      {Typ: reflect.TypeOf(q.TagCallSiteParameter), Value: constant.MakeInt64(int64(q.TagCallSiteParameter))},
				"TagCatchDwarfBlock":        {Typ: reflect.TypeOf(q.TagCatchDwarfBlock), Value: constant.MakeInt64(int64(q.TagCatchDwarfBlock))},
				"TagClassType":              {Typ: reflect.TypeOf(q.TagClassType), Value: constant.MakeInt64(int64(q.TagClassType))},
				"TagCoarrayType":            {Typ: reflect.TypeOf(q.TagCoarrayType), Value: constant.MakeInt64(int64(q.TagCoarrayType))},
				"TagCommonDwarfBlock":       {Typ: reflect.TypeOf(q.TagCommonDwarfBlock), Value: constant.MakeInt64(int64(q.TagCommonDwarfBlock))},
				"TagCommonInclusion":        {Typ: reflect.TypeOf(q.TagCommonInclusion), Value: constant.MakeInt64(int64(q.TagCommonInclusion))},
				"TagCompileUnit":            {Typ: reflect.TypeOf(q.TagCompileUnit), Value: constant.MakeInt64(int64(q.TagCompileUnit))},
				"TagCondition":              {Typ: reflect.TypeOf(q.TagCondition), Value: constant.MakeInt64(int64(q.TagCondition))},
				"TagConstType":              {Typ: reflect.TypeOf(q.TagConstType), Value: constant.MakeInt64(int64(q.TagConstType))},
				"TagConstant":               {Typ: reflect.TypeOf(q.TagConstant), Value: constant.MakeInt64(int64(q.TagConstant))},
				"TagDwarfProcedure":         {Typ: reflect.TypeOf(q.TagDwarfProcedure), Value: constant.MakeInt64(int64(q.TagDwarfProcedure))},
				"TagDynamicType":            {Typ: reflect.TypeOf(q.TagDynamicType), Value: constant.MakeInt64(int64(q.TagDynamicType))},
				"TagEntryPoint":             {Typ: reflect.TypeOf(q.TagEntryPoint), Value: constant.MakeInt64(int64(q.TagEntryPoint))},
				"TagEnumerationType":        {Typ: reflect.TypeOf(q.TagEnumerationType), Value: constant.MakeInt64(int64(q.TagEnumerationType))},
				"TagEnumerator":             {Typ: reflect.TypeOf(q.TagEnumerator), Value: constant.MakeInt64(int64(q.TagEnumerator))},
				"TagFileType":               {Typ: reflect.TypeOf(q.TagFileType), Value: constant.MakeInt64(int64(q.TagFileType))},
				"TagFormalParameter":        {Typ: reflect.TypeOf(q.TagFormalParameter), Value: constant.MakeInt64(int64(q.TagFormalParameter))},
				"TagFriend":                 {Typ: reflect.TypeOf(q.TagFriend), Value: constant.MakeInt64(int64(q.TagFriend))},
				"TagGenericSubrange":        {Typ: reflect.TypeOf(q.TagGenericSubrange), Value: constant.MakeInt64(int64(q.TagGenericSubrange))},
				"TagImmutableType":          {Typ: reflect.TypeOf(q.TagImmutableType), Value: constant.MakeInt64(int64(q.TagImmutableType))},
				"TagImportedDeclaration":    {Typ: reflect.TypeOf(q.TagImportedDeclaration), Value: constant.MakeInt64(int64(q.TagImportedDeclaration))},
				"TagImportedModule":         {Typ: reflect.TypeOf(q.TagImportedModule), Value: constant.MakeInt64(int64(q.TagImportedModule))},
				"TagImportedUnit":           {Typ: reflect.TypeOf(q.TagImportedUnit), Value: constant.MakeInt64(int64(q.TagImportedUnit))},
				"TagInheritance":            {Typ: reflect.TypeOf(q.TagInheritance), Value: constant.MakeInt64(int64(q.TagInheritance))},
				"TagInlinedSubroutine":      {Typ: reflect.TypeOf(q.TagInlinedSubroutine), Value: constant.MakeInt64(int64(q.TagInlinedSubroutine))},
				"TagInterfaceType":          {Typ: reflect.TypeOf(q.TagInterfaceType), Value: constant.MakeInt64(int64(q.TagInterfaceType))},
				"TagLabel":                  {Typ: reflect.TypeOf(q.TagLabel), Value: constant.MakeInt64(int64(q.TagLabel))},
				"TagLexDwarfBlock":          {Typ: reflect.TypeOf(q.TagLexDwarfBlock), Value: constant.MakeInt64(int64(q.TagLexDwarfBlock))},
				"TagMember":                 {Typ: reflect.TypeOf(q.TagMember), Value: constant.MakeInt64(int64(q.TagMember))},
				"TagModule":                 {Typ: reflect.TypeOf(q.TagModule), Value: constant.MakeInt64(int64(q.TagModule))},
				"TagMutableType":            {Typ: reflect.TypeOf(q.TagMutableType), Value: constant.MakeInt64(int64(q.TagMutableType))},
				"TagNamelist":               {Typ: reflect.TypeOf(q.TagNamelist), Value: constant.MakeInt64(int64(q.TagNamelist))},
				"TagNamelistItem":           {Typ: reflect.TypeOf(q.TagNamelistItem), Value: constant.MakeInt64(int64(q.TagNamelistItem))},
				"TagNamespace":              {Typ: reflect.TypeOf(q.TagNamespace), Value: constant.MakeInt64(int64(q.TagNamespace))},
				"TagPackedType":             {Typ: reflect.TypeOf(q.TagPackedType), Value: constant.MakeInt64(int64(q.TagPackedType))},
				"TagPartialUnit":            {Typ: reflect.TypeOf(q.TagPartialUnit), Value: constant.MakeInt64(int64(q.TagPartialUnit))},
				"TagPointerType":            {Typ: reflect.TypeOf(q.TagPointerType), Value: constant.MakeInt64(int64(q.TagPointerType))},
				"TagPtrToMemberType":        {Typ: reflect.TypeOf(q.TagPtrToMemberType), Value: constant.MakeInt64(int64(q.TagPtrToMemberType))},
				"TagReferenceType":          {Typ: reflect.TypeOf(q.TagReferenceType), Value: constant.MakeInt64(int64(q.TagReferenceType))},
				"TagRestrictType":           {Typ: reflect.TypeOf(q.TagRestrictType), Value: constant.MakeInt64(int64(q.TagRestrictType))},
				"TagRvalueReferenceType":    {Typ: reflect.TypeOf(q.TagRvalueReferenceType), Value: constant.MakeInt64(int64(q.TagRvalueReferenceType))},
				"TagSetType":                {Typ: reflect.TypeOf(q.TagSetType), Value: constant.MakeInt64(int64(q.TagSetType))},
				"TagSharedType":             {Typ: reflect.TypeOf(q.TagSharedType), Value: constant.MakeInt64(int64(q.TagSharedType))},
				"TagSkeletonUnit":           {Typ: reflect.TypeOf(q.TagSkeletonUnit), Value: constant.MakeInt64(int64(q.TagSkeletonUnit))},
				"TagStringType":             {Typ: reflect.TypeOf(q.TagStringType), Value: constant.MakeInt64(int64(q.TagStringType))},
				"TagStructType":             {Typ: reflect.TypeOf(q.TagStructType), Value: constant.MakeInt64(int64(q.TagStructType))},
				"TagSubprogram":             {Typ: reflect.TypeOf(q.TagSubprogram), Value: constant.MakeInt64(int64(q.TagSubprogram))},
				"TagSubrangeType":           {Typ: reflect.TypeOf(q.TagSubrangeType), Value: constant.MakeInt64(int64(q.TagSubrangeType))},
				"TagSubroutineType":         {Typ: reflect.TypeOf(q.TagSubroutineType), Value: constant.MakeInt64(int64(q.TagSubroutineType))},
				"TagTemplateAlias":          {Typ: reflect.TypeOf(q.TagTemplateAlias), Value: constant.MakeInt64(int64(q.TagTemplateAlias))},
				"TagTemplateTypeParameter":  {Typ: reflect.TypeOf(q.TagTemplateTypeParameter), Value: constant.MakeInt64(int64(q.TagTemplateTypeParameter))},
				"TagTemplateValueParameter": {Typ: reflect.TypeOf(q.TagTemplateValueParameter), Value: constant.MakeInt64(int64(q.TagTemplateValueParameter))},
				"TagThrownType":             {Typ: reflect.TypeOf(q.TagThrownType), Value: constant.MakeInt64(int64(q.TagThrownType))},
				"TagTryDwarfBlock":          {Typ: reflect.TypeOf(q.TagTryDwarfBlock), Value: constant.MakeInt64(int64(q.TagTryDwarfBlock))},
				"TagTypeUnit":               {Typ: reflect.TypeOf(q.TagTypeUnit), Value: constant.MakeInt64(int64(q.TagTypeUnit))},
				"TagTypedef":                {Typ: reflect.TypeOf(q.TagTypedef), Value: constant.MakeInt64(int64(q.TagTypedef))},
				"TagUnionType":              {Typ: reflect.TypeOf(q.TagUnionType), Value: constant.MakeInt64(int64(q.TagUnionType))},
				"TagUnspecifiedParameters":  {Typ: reflect.TypeOf(q.TagUnspecifiedParameters), Value: constant.MakeInt64(int64(q.TagUnspecifiedParameters))},
				"TagUnspecifiedType":        {Typ: reflect.TypeOf(q.TagUnspecifiedType), Value: constant.MakeInt64(int64(q.TagUnspecifiedType))},
				"TagVariable":               {Typ: reflect.TypeOf(q.TagVariable), Value: constant.MakeInt64(int64(q.TagVariable))},
				"TagVariant":                {Typ: reflect.TypeOf(q.TagVariant), Value: constant.MakeInt64(int64(q.TagVariant))},
				"TagVariantPart":            {Typ: reflect.TypeOf(q.TagVariantPart), Value: constant.MakeInt64(int64(q.TagVariantPart))},
				"TagVolatileType":           {Typ: reflect.TypeOf(q.TagVolatileType), Value: constant.MakeInt64(int64(q.TagVolatileType))},
				"TagWithStmt":               {Typ: reflect.TypeOf(q.TagWithStmt), Value: constant.MakeInt64(int64(q.TagWithStmt))},
			},
			UntypedConsts: map[string]ixgo.UntypedConst{},
		}
	})
}
