// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.25 && !go1.26
// +build go1.25,!go1.26

package os

import (
	q "os"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage("os", func() *ixgo.Package {
		return &ixgo.Package{
			Name: "os",
			Path: "os",
			Deps: map[string]string{
				"errors":                   "errors",
				"internal/bytealg":         "bytealg",
				"internal/filepathlite":    "filepathlite",
				"internal/itoa":            "itoa",
				"internal/poll":            "poll",
				"internal/stringslite":     "stringslite",
				"internal/syscall/execenv": "execenv",
				"internal/syscall/unix":    "unix",
				"internal/testlog":         "testlog",
				"io":                       "io",
				"io/fs":                    "fs",
				"runtime":                  "runtime",
				"slices":                   "slices",
				"sync":                     "sync",
				"sync/atomic":              "atomic",
				"syscall":                  "syscall",
				"time":                     "time",
				"unsafe":                   "unsafe",
			},
			Interfaces: map[string]reflect.Type{
				"Signal": reflect.TypeOf((*q.Signal)(nil)).Elem(),
			},
			NamedTypes: map[string]reflect.Type{
				"File":         reflect.TypeOf((*q.File)(nil)).Elem(),
				"LinkError":    reflect.TypeOf((*q.LinkError)(nil)).Elem(),
				"ProcAttr":     reflect.TypeOf((*q.ProcAttr)(nil)).Elem(),
				"Process":      reflect.TypeOf((*q.Process)(nil)).Elem(),
				"ProcessState": reflect.TypeOf((*q.ProcessState)(nil)).Elem(),
				"Root":         reflect.TypeOf((*q.Root)(nil)).Elem(),
				"SyscallError": reflect.TypeOf((*q.SyscallError)(nil)).Elem(),
			},
			AliasTypes: map[string]reflect.Type{
				"DirEntry":  reflect.TypeOf((*q.DirEntry)(nil)).Elem(),
				"FileInfo":  reflect.TypeOf((*q.FileInfo)(nil)).Elem(),
				"FileMode":  reflect.TypeOf((*q.FileMode)(nil)).Elem(),
				"PathError": reflect.TypeOf((*q.PathError)(nil)).Elem(),
			},
			Vars: map[string]interface{}{
				"Args":                &q.Args,
				"ErrClosed":           &q.ErrClosed,
				"ErrDeadlineExceeded": &q.ErrDeadlineExceeded,
				"ErrExist":            &q.ErrExist,
				"ErrInvalid":          &q.ErrInvalid,
				"ErrNoDeadline":       &q.ErrNoDeadline,
				"ErrNotExist":         &q.ErrNotExist,
				"ErrPermission":       &q.ErrPermission,
				"ErrProcessDone":      &q.ErrProcessDone,
				"Interrupt":           &q.Interrupt,
				"Kill":                &q.Kill,
				"Stderr":              &q.Stderr,
				"Stdin":               &q.Stdin,
				"Stdout":              &q.Stdout,
			},
			Funcs: map[string]interface{}{
				"Chdir":           q.Chdir,
				"Chmod":           q.Chmod,
				"Chown":           q.Chown,
				"Chtimes":         q.Chtimes,
				"Clearenv":        q.Clearenv,
				"CopyFS":          q.CopyFS,
				"Create":          q.Create,
				"CreateTemp":      q.CreateTemp,
				"DirFS":           q.DirFS,
				"Environ":         q.Environ,
				"Executable":      q.Executable,
				"Exit":            q.Exit,
				"Expand":          q.Expand,
				"ExpandEnv":       q.ExpandEnv,
				"FindProcess":     q.FindProcess,
				"Getegid":         q.Getegid,
				"Getenv":          q.Getenv,
				"Geteuid":         q.Geteuid,
				"Getgid":          q.Getgid,
				"Getgroups":       q.Getgroups,
				"Getpagesize":     q.Getpagesize,
				"Getpid":          q.Getpid,
				"Getppid":         q.Getppid,
				"Getuid":          q.Getuid,
				"Getwd":           q.Getwd,
				"Hostname":        q.Hostname,
				"IsExist":         q.IsExist,
				"IsNotExist":      q.IsNotExist,
				"IsPathSeparator": q.IsPathSeparator,
				"IsPermission":    q.IsPermission,
				"IsTimeout":       q.IsTimeout,
				"Lchown":          q.Lchown,
				"Link":            q.Link,
				"LookupEnv":       q.LookupEnv,
				"Lstat":           q.Lstat,
				"Mkdir":           q.Mkdir,
				"MkdirAll":        q.MkdirAll,
				"MkdirTemp":       q.MkdirTemp,
				"NewFile":         q.NewFile,
				"NewSyscallError": q.NewSyscallError,
				"Open":            q.Open,
				"OpenFile":        q.OpenFile,
				"OpenInRoot":      q.OpenInRoot,
				"OpenRoot":        q.OpenRoot,
				"Pipe":            q.Pipe,
				"ReadDir":         q.ReadDir,
				"ReadFile":        q.ReadFile,
				"Readlink":        q.Readlink,
				"Remove":          q.Remove,
				"RemoveAll":       q.RemoveAll,
				"Rename":          q.Rename,
				"SameFile":        q.SameFile,
				"Setenv":          q.Setenv,
				"StartProcess":    q.StartProcess,
				"Stat":            q.Stat,
				"Symlink":         q.Symlink,
				"TempDir":         q.TempDir,
				"Truncate":        q.Truncate,
				"Unsetenv":        q.Unsetenv,
				"UserCacheDir":    q.UserCacheDir,
				"UserConfigDir":   q.UserConfigDir,
				"UserHomeDir":     q.UserHomeDir,
				"WriteFile":       q.WriteFile,
			},
			TypedConsts: map[string]interface{}{
				"ModeAppend":     q.ModeAppend,
				"ModeCharDevice": q.ModeCharDevice,
				"ModeDevice":     q.ModeDevice,
				"ModeDir":        q.ModeDir,
				"ModeExclusive":  q.ModeExclusive,
				"ModeIrregular":  q.ModeIrregular,
				"ModeNamedPipe":  q.ModeNamedPipe,
				"ModePerm":       q.ModePerm,
				"ModeSetgid":     q.ModeSetgid,
				"ModeSetuid":     q.ModeSetuid,
				"ModeSocket":     q.ModeSocket,
				"ModeSticky":     q.ModeSticky,
				"ModeSymlink":    q.ModeSymlink,
				"ModeTemporary":  q.ModeTemporary,
				"ModeType":       q.ModeType,
				"O_APPEND":       q.O_APPEND,
				"O_CREATE":       q.O_CREATE,
				"O_EXCL":         q.O_EXCL,
				"O_RDONLY":       q.O_RDONLY,
				"O_RDWR":         q.O_RDWR,
				"O_SYNC":         q.O_SYNC,
				"O_TRUNC":        q.O_TRUNC,
				"O_WRONLY":       q.O_WRONLY,
				"SEEK_CUR":       q.SEEK_CUR,
				"SEEK_END":       q.SEEK_END,
				"SEEK_SET":       q.SEEK_SET,
			},
			UntypedConsts: map[string]ixgo.UntypedConst{
				"DevNull":           {Typ: "untyped string", Value: constant.MakeString(string(q.DevNull))},
				"PathListSeparator": {Typ: "untyped rune", Value: constant.MakeInt64(int64(q.PathListSeparator))},
				"PathSeparator":     {Typ: "untyped rune", Value: constant.MakeInt64(int64(q.PathSeparator))},
			},
		}
	})
}
