// export by github.com/goplus/ixgo/cmd/qexp

//go:build go1.26
// +build go1.26

package os

import (
	q "os"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage(&ixgo.Package{
		Name: "os",
		Path: "os",
		Deps: map[string]string{
			"errors":                   "errors",
			"internal/bytealg":         "bytealg",
			"internal/filepathlite":    "filepathlite",
			"internal/poll":            "poll",
			"internal/strconv":         "strconv",
			"internal/stringslite":     "stringslite",
			"internal/syscall/execenv": "execenv",
			"internal/syscall/unix":    "unix",
			"internal/testlog":         "testlog",
			"io":                       "io",
			"io/fs":                    "fs",
			"runtime":                  "runtime",
			"slices":                   "slices",
			"sync":                     "sync",
			"sync/atomic":              "atomic",
			"syscall":                  "syscall",
			"time":                     "time",
			"unsafe":                   "unsafe",
		},
		Interfaces: map[string]reflect.Type{
			"Signal": reflect.TypeOf((*q.Signal)(nil)).Elem(),
		},
		NamedTypes: map[string]reflect.Type{
			"File":         reflect.TypeOf((*q.File)(nil)).Elem(),
			"LinkError":    reflect.TypeOf((*q.LinkError)(nil)).Elem(),
			"ProcAttr":     reflect.TypeOf((*q.ProcAttr)(nil)).Elem(),
			"Process":      reflect.TypeOf((*q.Process)(nil)).Elem(),
			"ProcessState": reflect.TypeOf((*q.ProcessState)(nil)).Elem(),
			"Root":         reflect.TypeOf((*q.Root)(nil)).Elem(),
			"SyscallError": reflect.TypeOf((*q.SyscallError)(nil)).Elem(),
		},
		AliasTypes: map[string]reflect.Type{
			"DirEntry":  reflect.TypeOf((*q.DirEntry)(nil)).Elem(),
			"FileInfo":  reflect.TypeOf((*q.FileInfo)(nil)).Elem(),
			"FileMode":  reflect.TypeOf((*q.FileMode)(nil)).Elem(),
			"PathError": reflect.TypeOf((*q.PathError)(nil)).Elem(),
		},
		Vars: map[string]reflect.Value{
			"Args":                reflect.ValueOf(&q.Args),
			"ErrClosed":           reflect.ValueOf(&q.ErrClosed),
			"ErrDeadlineExceeded": reflect.ValueOf(&q.ErrDeadlineExceeded),
			"ErrExist":            reflect.ValueOf(&q.ErrExist),
			"ErrInvalid":          reflect.ValueOf(&q.ErrInvalid),
			"ErrNoDeadline":       reflect.ValueOf(&q.ErrNoDeadline),
			"ErrNoHandle":         reflect.ValueOf(&q.ErrNoHandle),
			"ErrNotExist":         reflect.ValueOf(&q.ErrNotExist),
			"ErrPermission":       reflect.ValueOf(&q.ErrPermission),
			"ErrProcessDone":      reflect.ValueOf(&q.ErrProcessDone),
			"Interrupt":           reflect.ValueOf(&q.Interrupt),
			"Kill":                reflect.ValueOf(&q.Kill),
			"Stderr":              reflect.ValueOf(&q.Stderr),
			"Stdin":               reflect.ValueOf(&q.Stdin),
			"Stdout":              reflect.ValueOf(&q.Stdout),
		},
		Funcs: map[string]reflect.Value{
			"Chdir":           reflect.ValueOf(q.Chdir),
			"Chmod":           reflect.ValueOf(q.Chmod),
			"Chown":           reflect.ValueOf(q.Chown),
			"Chtimes":         reflect.ValueOf(q.Chtimes),
			"Clearenv":        reflect.ValueOf(q.Clearenv),
			"CopyFS":          reflect.ValueOf(q.CopyFS),
			"Create":          reflect.ValueOf(q.Create),
			"CreateTemp":      reflect.ValueOf(q.CreateTemp),
			"DirFS":           reflect.ValueOf(q.DirFS),
			"Environ":         reflect.ValueOf(q.Environ),
			"Executable":      reflect.ValueOf(q.Executable),
			"Exit":            reflect.ValueOf(q.Exit),
			"Expand":          reflect.ValueOf(q.Expand),
			"ExpandEnv":       reflect.ValueOf(q.ExpandEnv),
			"FindProcess":     reflect.ValueOf(q.FindProcess),
			"Getegid":         reflect.ValueOf(q.Getegid),
			"Getenv":          reflect.ValueOf(q.Getenv),
			"Geteuid":         reflect.ValueOf(q.Geteuid),
			"Getgid":          reflect.ValueOf(q.Getgid),
			"Getgroups":       reflect.ValueOf(q.Getgroups),
			"Getpagesize":     reflect.ValueOf(q.Getpagesize),
			"Getpid":          reflect.ValueOf(q.Getpid),
			"Getppid":         reflect.ValueOf(q.Getppid),
			"Getuid":          reflect.ValueOf(q.Getuid),
			"Getwd":           reflect.ValueOf(q.Getwd),
			"Hostname":        reflect.ValueOf(q.Hostname),
			"IsExist":         reflect.ValueOf(q.IsExist),
			"IsNotExist":      reflect.ValueOf(q.IsNotExist),
			"IsPathSeparator": reflect.ValueOf(q.IsPathSeparator),
			"IsPermission":    reflect.ValueOf(q.IsPermission),
			"IsTimeout":       reflect.ValueOf(q.IsTimeout),
			"Lchown":          reflect.ValueOf(q.Lchown),
			"Link":            reflect.ValueOf(q.Link),
			"LookupEnv":       reflect.ValueOf(q.LookupEnv),
			"Lstat":           reflect.ValueOf(q.Lstat),
			"Mkdir":           reflect.ValueOf(q.Mkdir),
			"MkdirAll":        reflect.ValueOf(q.MkdirAll),
			"MkdirTemp":       reflect.ValueOf(q.MkdirTemp),
			"NewFile":         reflect.ValueOf(q.NewFile),
			"NewSyscallError": reflect.ValueOf(q.NewSyscallError),
			"Open":            reflect.ValueOf(q.Open),
			"OpenFile":        reflect.ValueOf(q.OpenFile),
			"OpenInRoot":      reflect.ValueOf(q.OpenInRoot),
			"OpenRoot":        reflect.ValueOf(q.OpenRoot),
			"Pipe":            reflect.ValueOf(q.Pipe),
			"ReadDir":         reflect.ValueOf(q.ReadDir),
			"ReadFile":        reflect.ValueOf(q.ReadFile),
			"Readlink":        reflect.ValueOf(q.Readlink),
			"Remove":          reflect.ValueOf(q.Remove),
			"RemoveAll":       reflect.ValueOf(q.RemoveAll),
			"Rename":          reflect.ValueOf(q.Rename),
			"SameFile":        reflect.ValueOf(q.SameFile),
			"Setenv":          reflect.ValueOf(q.Setenv),
			"StartProcess":    reflect.ValueOf(q.StartProcess),
			"Stat":            reflect.ValueOf(q.Stat),
			"Symlink":         reflect.ValueOf(q.Symlink),
			"TempDir":         reflect.ValueOf(q.TempDir),
			"Truncate":        reflect.ValueOf(q.Truncate),
			"Unsetenv":        reflect.ValueOf(q.Unsetenv),
			"UserCacheDir":    reflect.ValueOf(q.UserCacheDir),
			"UserConfigDir":   reflect.ValueOf(q.UserConfigDir),
			"UserHomeDir":     reflect.ValueOf(q.UserHomeDir),
			"WriteFile":       reflect.ValueOf(q.WriteFile),
		},
		TypedConsts: map[string]ixgo.TypedConst{
			"ModeAppend":     {Typ: reflect.TypeOf(q.ModeAppend), Value: constant.MakeInt64(int64(q.ModeAppend))},
			"ModeCharDevice": {Typ: reflect.TypeOf(q.ModeCharDevice), Value: constant.MakeInt64(int64(q.ModeCharDevice))},
			"ModeDevice":     {Typ: reflect.TypeOf(q.ModeDevice), Value: constant.MakeInt64(int64(q.ModeDevice))},
			"ModeDir":        {Typ: reflect.TypeOf(q.ModeDir), Value: constant.MakeInt64(int64(q.ModeDir))},
			"ModeExclusive":  {Typ: reflect.TypeOf(q.ModeExclusive), Value: constant.MakeInt64(int64(q.ModeExclusive))},
			"ModeIrregular":  {Typ: reflect.TypeOf(q.ModeIrregular), Value: constant.MakeInt64(int64(q.ModeIrregular))},
			"ModeNamedPipe":  {Typ: reflect.TypeOf(q.ModeNamedPipe), Value: constant.MakeInt64(int64(q.ModeNamedPipe))},
			"ModePerm":       {Typ: reflect.TypeOf(q.ModePerm), Value: constant.MakeInt64(int64(q.ModePerm))},
			"ModeSetgid":     {Typ: reflect.TypeOf(q.ModeSetgid), Value: constant.MakeInt64(int64(q.ModeSetgid))},
			"ModeSetuid":     {Typ: reflect.TypeOf(q.ModeSetuid), Value: constant.MakeInt64(int64(q.ModeSetuid))},
			"ModeSocket":     {Typ: reflect.TypeOf(q.ModeSocket), Value: constant.MakeInt64(int64(q.ModeSocket))},
			"ModeSticky":     {Typ: reflect.TypeOf(q.ModeSticky), Value: constant.MakeInt64(int64(q.ModeSticky))},
			"ModeSymlink":    {Typ: reflect.TypeOf(q.ModeSymlink), Value: constant.MakeInt64(int64(q.ModeSymlink))},
			"ModeTemporary":  {Typ: reflect.TypeOf(q.ModeTemporary), Value: constant.MakeInt64(int64(q.ModeTemporary))},
			"ModeType":       {Typ: reflect.TypeOf(q.ModeType), Value: constant.MakeInt64(int64(q.ModeType))},
			"O_APPEND":       {Typ: reflect.TypeOf(q.O_APPEND), Value: constant.MakeInt64(int64(q.O_APPEND))},
			"O_CREATE":       {Typ: reflect.TypeOf(q.O_CREATE), Value: constant.MakeInt64(int64(q.O_CREATE))},
			"O_EXCL":         {Typ: reflect.TypeOf(q.O_EXCL), Value: constant.MakeInt64(int64(q.O_EXCL))},
			"O_RDONLY":       {Typ: reflect.TypeOf(q.O_RDONLY), Value: constant.MakeInt64(int64(q.O_RDONLY))},
			"O_RDWR":         {Typ: reflect.TypeOf(q.O_RDWR), Value: constant.MakeInt64(int64(q.O_RDWR))},
			"O_SYNC":         {Typ: reflect.TypeOf(q.O_SYNC), Value: constant.MakeInt64(int64(q.O_SYNC))},
			"O_TRUNC":        {Typ: reflect.TypeOf(q.O_TRUNC), Value: constant.MakeInt64(int64(q.O_TRUNC))},
			"O_WRONLY":       {Typ: reflect.TypeOf(q.O_WRONLY), Value: constant.MakeInt64(int64(q.O_WRONLY))},
			"SEEK_CUR":       {Typ: reflect.TypeOf(q.SEEK_CUR), Value: constant.MakeInt64(int64(q.SEEK_CUR))},
			"SEEK_END":       {Typ: reflect.TypeOf(q.SEEK_END), Value: constant.MakeInt64(int64(q.SEEK_END))},
			"SEEK_SET":       {Typ: reflect.TypeOf(q.SEEK_SET), Value: constant.MakeInt64(int64(q.SEEK_SET))},
		},
		UntypedConsts: map[string]ixgo.UntypedConst{
			"DevNull":           {Typ: "untyped string", Value: constant.MakeString(string(q.DevNull))},
			"PathListSeparator": {Typ: "untyped rune", Value: constant.MakeInt64(int64(q.PathListSeparator))},
			"PathSeparator":     {Typ: "untyped rune", Value: constant.MakeInt64(int64(q.PathSeparator))},
		},
	})
}
